### ISSUE TITLE
vsnprintf is broken

### ISSUE THREAD

**Issue by tehKaiN** [bebbo/amiga-gcc#10]
Not sure if submitted on proper repo (clib2 has issues disabled). Suppose small test code:

``` c
#include <stdio.h>
#include <stdarg.h>

int lva(va_list va) {
	// This should return 8, returns 1
	char szTmp[2];
	return vsnprintf(szTmp, 2, "%s", va);
	
	// This too should return 8
	return vsnprintf(NULL, 0, "%s", va);
}

int l(int a, ...) {
		va_list va;
		va_start(va, a);
		int result = lva(va);
		va_end(va);
		
		return result;
}

void main(void) {
	int len = l(0, "testtest");
	printf("%d", len);
}
```

compiled with: `m68k-amigaos-gcc main.c -o test -noixemul`

This approach is commonly used to measure strings vsprintf output. Stumblet upon it when tried to compile https://github.com/fragglet/lhasa

Quoting http://www.cplusplus.com/reference/cstdio/vsnprintf/ :

> Return Value
> The number of characters that would have been written if n had been sufficiently large, not counting the terminating null character.

**Comment by bebbo** [comment]
the correct repo for -noixemul library issues is https://github.com/bebbo/libnix

**Comment by tehKaiN** [comment]
So should I move issue there? Also, if you don't have time I can try to tackle this issue with pull request.

**Comment by bebbo** [comment]
If you want to fix this, clone libnix and create the pull request.

The issue may live here.

**Comment by tehKaiN** [comment]
Okay, so I've been thinking about that and there is basically only one way to properly implement it:

- allocate resulting string using vasprintf() which:
  - parses format for measuring required buffer size,
  - allocates string for destination,
  - parses format for destination write - basically `sprintf`
- copy constrained length to destination buffer.

This is how original GCC [implements it](https://github.com/gcc-mirror/gcc/blob/master/libiberty/vsnprintf.c). I've thought about parsing format string for counting result length, and then doing it again for filling buffer, but the second run would have additional `if` on every write to destination buffer, so that would be quite a slowdown and would result in noticeably longer function. I don't like prealloc approach using `vasprintf` because of extended memory footprint, but it seems like the fastest option for properly printing stuff like:

``` c
char bfr[4]
vsnprintf(bfr, 4, "%.5f", M_PI);
```

Also, since `vasprintf` and `asprintf` are *nix extension of stdio.h, I guess I should add .c files for them in stdio dir?

**Comment by bebbo** [comment]
I'd rather modify the existing function to count chars to write, but stop writing if the buffer size is exceeded,

**Comment by bebbo** [comment]
right now `vsnprintf` calls`vfprintf` using a FILE with the limited size, to avoid overflow.
There is the macro
```
#define OUT(c)  do                           \
                { if(fputc((c),stream)==EOF) \
                    return outcount;         \
                  outcount++;                \
                }while(0)
```
This macro needs a fix, I simply suggest:
```
  {fputc((c),stream); ++outcount;}
```
then you'll get the length needed, and if the FILE is at EOF, the FILE tells you how many bytes were written.

**Comment by tehKaiN** [comment]
Oh, so fputc checks internally if there is no more room in file and doesn't write if it's full. I've missed it during my research. It would suffice, but take a look on expected `vfprintf` returns:

>  On success, the total number of characters written is returned.
>  If a writing error occurs, the error indicator (ferror) is set and a negative number is returned.

So if we patch vfprintf that way, it will not behave properly ;)

**Comment by bebbo** [comment]
so an additional function might be appropriate which is the current vfprintf with the suggested change. This function returns the need character count.

The new vfprintf can call it and check if the return agains the FILE and return -1 or the count of printed chars. Also all other functions should be able to create the correct return code using that information.

**Comment by tehKaiN** [comment]
Nice! Will do. Looks like you'd do it 10 times quicker than me. ;)

**Comment by bebbo** [comment]
... I am digging deep into the 🥀 gcc code...

**Comment by tehKaiN** [comment]
I've probably fixed it at this point, but I have no time to test it. I'll return to this on Friday evening and I hope there will be pull request soon after.
