### ISSUE TITLE
Unable to build on MacOS (binutils)

### ISSUE THREAD

**Issue by terriblefire** [bebbo/amiga-gcc#106]
libtool: link: gcc-9 -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -I/Users/stephen/git/amiga-gcc/projects/binutils/binutils/../zlib -Os -static-libstdc++ -static-libgcc -Wl,-no_pie -o objdump objdump.o dwarf.o prdbg.o rddbg.o debug.o stabs.o rdcoff.o bucomm.o version.o filemode.o elfcomm.o  ../opcodes/.libs/libopcodes.a ../libctf/libctf.a ../bfd/.libs/libbfd.a -L/Users/stephen/git/amiga-gcc/build-Darwin/binutils/zlib -lz ../libiberty/libiberty.a
Undefined symbols for architecture x86_64:
  "_bswap_32", referenced from:
      _flip_header in libctf.a(ctf-open.o)
      _flip_objts in libctf.a(ctf-open.o)
      _ctf_bufopen in libctf.a(ctf-open.o)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
gmake[4]: *** [Makefile:914: objdump] Error 1
make binutils binutils...failed

I dont have any byteswap.h files installed anywhere that i can locate.

**Comment by bebbo** [comment]
I can't provide support for that os, but I accept pull requests to fix this.

**Comment by terriblefire** [comment]
I will take a look. I submitted this Incase anyone else has the same problems.

**Comment by bebbo** [comment]
It seems to build again: https://travis-ci.org/bebbo/amiga-gcc

**Comment by terriblefire** [comment]
Indeed. It is building. Must have been an upstream bug in binutils.
