### ISSUE TITLE
libgcc requires libpthreads, but does not link it

### ISSUE THREAD

**Issue by Midar** [bebbo/amiga-gcc#107]
libgcc currently depends on pthreads, meaning it is impossible for an app to not link pthreads:

```
/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: /opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/libgcc.a(unwind-dw2.o):unwind-dw2.o:(.text+0x1e3c): undefined reference to `pthread_once'
/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: /opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/libgcc.a(unwind-dw2-fde.o):unwind-dw2-fde.o:(.text+0x27e): undefined reference to `pthread_mutex_unlock'
/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: /opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/libgcc.a(unwind-dw2-fde.o):unwind-dw2-fde.o:(.text+0x314): undefined reference to `pthread_mutex_unlock'
/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: /opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/libgcc.a(unwind-dw2-fde.o):unwind-dw2-fde.o:(.text+0x3c6): undefined reference to `pthread_mutex_unlock'
/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: /opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/libgcc.a(unwind-dw2-fde.o):unwind-dw2-fde.o:(.text+0x3e6): undefined reference to `pthread_mutex_unlock'
/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: /opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/libgcc.a(unwind-dw2-fde.o):unwind-dw2-fde.o:(.text+0x406): undefined reference to `pthread_mutex_unlock'
/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: /opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/libgcc.a(unwind-dw2-fde.o):unwind-dw2-fde.o:(.text+0x11e4): more undefined references to `pthread_mutex_unlock' follow
/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: /opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/libgcc.a(unwind-dw2-fde.o):unwind-dw2-fde.o:(.text+0x368): undefined reference to `pthread_mutex_lock'
/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: /opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/libgcc.a(unwind-dw2-fde.o):unwind-dw2-fde.o:(.text+0x2f4): undefined reference to `pthread_mutex_lock'
/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: /opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/libgcc.a(unwind-dw2-fde.o):unwind-dw2-fde.o:(.text+0x25c): undefined reference to `pthread_mutex_lock'
/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: /opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/libgcc.a(unwind-dw2-fde.o):unwind-dw2-fde.o:(.text+0x11aa): undefined reference to `pthread_mutex_lock'
/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: /opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/libgcc.a(unwind-dw2-fde.o):unwind-dw2-fde.o:(.text+0x132a): undefined reference to `pthread_mutex_lock'
```

If pthreads is a requirement (seems like that could cause trouble with code doing its own threading?), it should at least link it automatically.

**Comment by Midar** [comment]
This goes further: It means libpthread is now required to build a library containing unwind info. libpthread now requires stdio. stdio is not available in libraries, and neither is automatic loading of other libraries.

**Comment by Midar** [comment]
The library problem was actually due to now linking in __register_frame_info via the __init_eh function that previously wasn't included into the library. However, I still think that at the very minimum, -lpthread should be linked in by default.

**Comment by Midar** [comment]
Turns out: Even when exposing the functions via the linklib, calling __register_frame_info now immediately crashes because it wants to use pthreads.

**Comment by Midar** [comment]
I think the correct solution would be to add a gthr-amiga that uses SignalSemaphore rather than having the compiler generate code that depends on libpthread

**Comment by Midar** [comment]
> Turns out: Even when exposing the functions via the linklib, calling __register_frame_info now immediately crashes because it wants to use pthreads.

This was due to the other bug with the too small __data_size symbol. So the only problem is that of not linking -lpthread by default, though ideally, GCC would be patched to just use ObtainSemaphore/ReleaseSemaphore directly.

**Comment by bebbo** [comment]
see b04b2ca22f7095ed039e4b66addd7de11a8749f2

**Comment by Midar** [comment]
The fix has the problem that unwinding is now no longer thread-safe, as is many C++ STL classes. I think using pthreads was fine, it would just need to be linked by default whenever libgcc is linked.

**Comment by bebbo** [comment]
There is too much stuff which starts to link against libpthread. Now it's the previous behaviour.

Forbid/Permit is easier for `onces`.

**Comment by Midar** [comment]
The problem with Forbid()/Permit() is that if it takes a little longer (e.g. reading a file once), it might block the system for quite a while. (Though that is a bad example, as reading a file involves Wait()). Generally, something like this should work:

ObtainSemaphore(once->sema);
if (!once->done) {
    once->done = true;
    func();
}
ReleaseSemaphore(once->sema);

**Comment by bebbo** [comment]
> 
> 
> The problem with Forbid()/Permit() is that if it takes a little longer (e.g. reading a file once), it might block the system for quite a while. (Though that is a bad example, as reading a file involves Wait()). Generally, something like this should work:
> 
> ```
> ObtainSemaphore(once->sema);
> if (!once->done) {
>     once->done = true;
>     func();
> }
> ReleaseSemaphore(once->sema);
> ```

`ObtainSemaphore` and `ReleaseSemaphore` are both calling `Forbid()/Permit()`

So why should this be slower then?
```
void run_once(void (*f)(void), int * once) {
  int run = 0;
  Forbid();
  if (!*once) *once = 1, run = 1;
  Permit();
  if (run) f();
}
```
/shrug

**Comment by Midar** [comment]
Your code is broken because it allows a second thread to return before the once is done.

**Comment by bebbo** [comment]
oh - doc lesen hilft. Dann eben mit Spin-Lock:
```
void run_once(void (*f)(void), volatile int * once) {
  int run = 0;
  Forbid();
  if (!*once) *once = run = 1;
  else while (*once > 0) {
      SysBase->SysFlags |= 1<<15;
      Permit();
      Forbid();
  }
  Permit();
  if (run) f(), *once = -1;
}
```

**Comment by Midar** [comment]
Why would using a spinlock be preferable over a semaphore?

**Comment by bebbo** [comment]
> Why would using a spinlock be preferable over a semaphore?

I also like pizza, well, sometimes.

And I like this code snippet which is not a replacement for a public pthread_once implementation. The onces during startup are commonly used to initialize some static variables and similar stuff, which is done within the current time slice. So the runtime overhead is way less than using semaphores.

> Also, this _still_ allows the once to return on a thread before it is initialized.

please explain the code flaw, if there is one.

> Also, you cannot make it work with Forbid() because the once code might break the Forbid().

How can a function/some code 
 - break `Forbid()/Permit()` of a different Process/Thread?
 - break `Forbid()` of the current Process/Thread, if it's not inside `Forbid()/Permit()`?

**Comment by Midar** [comment]
Oh, I missed the -1 at the end so that you spin. In that case you don't return too early indeed - but you will just waste CPU cycles until you're done. Semaphores use proper waiting for a signal.

As for the Wait(): Well, if you'd just run the once inside Wait() (like you posted above), this will break as soon as a DOS operation is performed by the once.

**Comment by bebbo** [comment]
> 
> 
> Oh, I missed the -1 at the end so that you spin. In that case you don't return too early indeed - but you will just waste CPU cycles until you're done. Semaphores use proper waiting for a signal.
> As for the Wait(): Well, if you'd just run the once inside Wait() (like you posted above), this will break as soon as a DOS operation is performed by the once.

And let's return to the topic: Where and for what purpose does libgcc need a pthread_once replacement.
For these cases (well, those I found) a spin lock is way less overhead.

**Comment by Midar** [comment]
The unwinder in libgcc requires both mutexes and onces :).

**Comment by bebbo** [comment]
> 
> 
> The unwinder in libgcc requires both mutexes and onces :).

It uses the once to intialize the mutex once. So the code above is perfect to ensure the mutex is initialized once.
And for the simple mutex usage, a mapping to the AmigaOS semaphores - without libpthread - is a perfect match too,

**Comment by bebbo** [comment]
and last but not least: consider for a once the more frequent case: the once is already initialized. What yields better performance then? Forbid()/Permit() and checking a flag or a semaphore?

=> the spin lock is the winner here.

**Comment by Midar** [comment]
If you're concerned about performance: Why not only get the Forbid/ObtainSemaphore if its 0?
