### ISSUE TITLE
baserel libraries broken due to wrong __data_size

### ISSUE THREAD

**Issue by Midar** [bebbo/amiga-gcc#108]
__data_size is currently broken, because it is very obviously wrong:

For example, for objfwrt68k.library (with some modifications to kprintf to debug this), I get __data_size=0xA08.

Looking at the file with nm:
```
00000000 D ___EXIT_LIST__
…
00000a08 D _libc
```

From this, we see two things:
 * The data segment is clearly starting at 0x0.
 * The highest address still in the data segment would be (0xA08 - size of object) if the size in __data_size were correct.
 * libc, a struct, is actually at 0xA08 and extends way beyond it. So clearly __data_size is wrong.

This breaks baserel libraries, as those depend on:
 * Figuring out where the data segment is
 * Figuring out the size of the data segment
 * Copying the entire data segment per library open
 * Relocate the copied data segment

Of course, with a wrong __data_size, none of this can work, resulting in a crash as soon as trying to use any baserel library compiled with amiga-gcc.

**Comment by Midar** [comment]
A-ha! I just noticed there's a new one: __bss_size. Apparently, the bss segment is directly following the data segment (good!), but bss and data used to be merged into one size: __data_size. So this breaks existing code. It's easy to work around once known, but I still wonder if it would have made sense to keep the __data_size as is and add a new __data_only_size or something?

**Comment by mheyer32** [comment]
Can you double check your assumptions? I have successfully created -fbaserel libs via gcc in ADoom.
You may also want to check the libnix startup code for libraries and see how they deal with the data segment. Out of curiosity: what is __data_size ?

https://github.com/mheyer32/ADoom

From the Makefile:

https://github.com/mheyer32/ADoom/blob/ded0c173116da879cbbf969cdefb9fb139912868/adoom_src/Makefile#L240

```
doomsound_midi.library: DoomSndFwd.h doomsound_midi.c Makefile
	$(CC) -v $(CFLAGS_DOOMSOUND) -I./ -ramiga-lib -fbaserel doomsound_midi.c -o $@
	$(STRIP) --strip-debug --strip-unneeded $@ -o  $(BINDIR)/$@
```

**Comment by Midar** [comment]
@mheyer32 I just checked and libnix source makes the exact same assumptions:
https://github.com/bebbo/libnix/blob/master/sources/startup/libinitr.c#L117
https://github.com/bebbo/libnix/blob/master/sources/startup/libinitr.c#L143

So, yes, this is also not copying the section bss.

The problem is that for a library with task specific state, you want to have a separate data segment per task. This is achieved by copying the libraries data segment in the library open function and relocating (the relocations are placed in __datadata_relocs by the linker). You can use __a4_init to get the beginning, and __data_size to get the size of the data segment. __data_size used to contain the size of data and bss, but now it only contains the size of data. This results in a memcpy that is too short, leaving an application that opens the library with bogus memory. While technically you don't really need to copy bss (as it will be mostly zero), you would need to at least zero it. Also, you might want to initialize some variables in section bss in your library init function, so then you do need to copy it instead of just zeroing it.

That said: If ADoom still works with latest amiga-gcc, that means that either you don't use section bss, or you have pure luck that that memory just happens to be zero and thus work -- and I guess that also means you don't set anything in bss in your library init.

**Comment by bebbo** [comment]
see 
libnix:e7081bcca080dfb1693da0fbf1e6a9598cebe015
binutils-gdb:66c0bccc231dafada5d8de1039b9bd064bd18373

**Comment by Midar** [comment]
I actually think the new behavior was more correct than the old one, so it's up to you whether to fix libnix for the new one or just revert to the old one. In any case, __bss_size = 0 is somewhat strange though, as bss is there and bigger than 0, it's just folded into data.

**Comment by bebbo** [comment]
it's now the same as it was before.

**Comment by Midar** [comment]
Oh, I didn't realize __bss_size was 0 before. NVM then.
