### ISSUE TITLE
amiga-gcc announces support for _Thread_local but doesn't support it

### ISSUE THREAD

**Issue by Midar** [bebbo/amiga-gcc#109]
amiga-gcc happily compiles code with _Thread_local, meaning configure scripts looking for the feature will pick it up and use it. However, during runtime, _Thread_local is not working and points to bogus data.

I don't see support for TLS in ncrt0.S or pthread.c, so I think this is a feature just enabled in GCC, but not implemented in the runtime. To actually support it in the runtime, the following would need to be done:

* Emit a symbol via the linker that allows getting the size of the tls data (similar to __data_size)
* In the init code:
  * Reserve a register for TLS
  * Allocate space for TLS and assign to said register
* In pthread:
  * In the function wrapper, allocate memory for TLS and set the register before jumping into the actual code

**Comment by bebbo** [comment]
see b04b2ca22f7095ed039e4b66addd7de11a8749f2

**Comment by Midar** [comment]
Would be nice if it could be properly supported, though - maybe convert the bug to a feature request?

**Comment by bebbo** [comment]
There are too many dependencies for switching to the posix thread model.
Single threading is ok.

```
Thread model: single
gcc version 6.5.0b 190814133058 (GCC)
```

**Comment by Midar** [comment]
Well, Amiga threads could be supported though, that would not involve any dependencies ;)

**Comment by Midar** [comment]
Even though the thread model is single now, GCC still announced support for _Thread_local.

**Comment by bebbo** [comment]
> 
> 
> Even though the thread model is single now, GCC still announced support for _Thread_local.

 - as it did before
 - which is emulated
 - see emutls.c

**Comment by bebbo** [comment]
this compiles, links and runs:
```
static _Thread_local int x = 0;
int main () {
    x++;
    return 0;
}
```
So, what's the problem?

**Comment by Midar** [comment]
That it only does so by pure luck. The address register for thread-local storage is never set up. I saw several NULL-dereferences as a result of this.

**Comment by bebbo** [comment]
> 
> 
> That it only does so by pure luck. The address register for thread-local storage is never set up. I saw several NULL-dereferences as a result of this.

please provide an example

**Comment by bebbo** [comment]
no update
