### ISSUE TITLE
unistd.h ignores __NO_NET_API

### ISSUE THREAD

**Issue by Midar** [bebbo/amiga-gcc#112]
unistd.h ignores __NO_NET_API being defined and still declares gethostid, gethostname and getdtablesize. unistd.h should follow sys/socket.h's precedent here to not declare those when __NO_NET_API is defined, as the ones declared in unistd.h clash with those of clib/bsdsocket_protos.h, making it impossible to use sockets directly in a file that also uses unistd.h. This is doubly important because libsocket.a just crashes, while using bsdsocket.library directly works. Even if libsocket.a would work, it would still be a requirement to use bsdsocket.library directly to allow threading (to move the socket between tasks).

**Comment by bebbo** [comment]
`__NO_NET_API` is not a standard

**Comment by bebbo** [comment]
I updated the clib headers to match unistd.h

**Comment by Midar** [comment]
Are you also updating the other ones in sys/socket.h then, to make __NO_NET_API entirely obsolete?

This still means there's a problem with inlining though, which I suppose is why this define was added in the first place.

**Comment by bebbo** [comment]
> 
> 
> Are you also updating the other ones in sys/socket.h then, to make __NO_NET_API entirely obsolete?

guess yes - the Amiga headers should comply with the standard.
 
> This still means there's a problem with inlining though, which I suppose is why this define was added in the first place.

what inlining problem?

**Comment by Midar** [comment]
The problem of using inline/bsdsockets.h

**Comment by bebbo** [comment]
> 
> 
> The problem of using inline/bsdsockets.h

simply include inline/*.h **after** the standard headers.
