### ISSUE TITLE
ndk13-include comes with empty intuition/iobsolete.h

### ISSUE THREAD

**Issue by alexalkis** [bebbo/amiga-gcc#113]
I had to do 
cp /opt/amiga/gcc6/m68k-amigaos/ndk-include/intuition/iobsolete.h /opt/amiga/gcc6/m68k-amigaos/ndk13-include/intuition/iobsolete.h

in order to compile a thing.

**Comment by bebbo** [comment]
`intuition/iobsolete.h` did not exist in kick 1.3

**Comment by alexalkis** [comment]
How would you compile this one?
[gad.zip](https://github.com/bebbo/amiga-gcc/files/3531350/gad.zip)

**Comment by alexalkis** [comment]
Original from here
https://groups.google.com/forum/#!search/amiga$20programming$20source$20C$20calc/net.micro.amiga/7JPeFBg_pAg/TjP7mqxnhwgJ

where it mentions Latice 3.02...maybe it was 1.2 era?

**Comment by bebbo** [comment]
thanks - no I understand the purpose of that header^^

**Comment by alexalkis** [comment]
I don't know.  As you said, and I agree, iobsolete.h did not exist in 1.3.

Though you derive intuition for ndk13 from ndk.  So it won't be possible to duplicate the "original" 1.3 intuition.h   So, I guess iobsolete.h will stand as a workarround, huh?

**Comment by bebbo** [comment]
is it ok now?

**Comment by alexalkis** [comment]
Yeap, sample compiles fine.
Thanks.
