### ISSUE TITLE
MSYS2: gdb not compiling

### ISSUE THREAD

**Issue by skeetor** [bebbo/amiga-gcc#119]
I know that this is rather a problem with MSYS2 and not with your project. However, when I try to do `make all` I get a compiler error when it tries to configure gdb.

```
/d/src/c/gcc/amiga-gcc/projects/binutils/gnulib/import/tempname.c: In function 'try_nocreate':
/d/src/c/gcc/amiga-gcc/projects/binutils/gnulib/import/tempname.c:280:17: error: storage size of 'st' isn't known
  280 |   struct_stat64 st;
      |                 ^~
make[6]: *** [Makefile:1762: tempname.o] Error 1 
```
I don't really want gdb anyway, so how can I disable it?

I had also problems with gcc, but I created some patches, and this works but I have other build errors as well so I try to solve one by one.

**Comment by bebbo** [comment]
it's working out of the box with
`MSYS_NT-10.0 <insert computer name> 2.11.2(0.329/5/3) 2018-11-26 09:22 x86_64 Msys`
and
`MSYS_NT-10.0-18362 <insert computer name> 3.0.6-338.x86_64 2019-04-15 06:44 UTC x86_64 Msys`

...
```
/opt/amiga/bin/m68k-amigaos-gcc -v
Using built-in specs.
COLLECT_GCC=/opt/amiga/bin/m68k-amigaos-gcc
COLLECT_LTO_WRAPPER=C:/msys64/opt/amiga/libexec/gcc/m68k-amigaos/6.5.0b/lto-wrapper
Target: m68k-amigaos
Configured with: /c/msys64/home/test/amiga-gcc/projects/gcc/configure --prefix=/opt/amiga --target=m68k-amigaos --enable-languages=c,c++,objc --enable-version-specific-runtime-libs --disable-libssp --disable-nls --with-headers=/c/msys64/home/test/amiga-gcc/projects/newlib-cygwin/newlib/libc/sys/amigaos/include/ --disable-shared --with-stage1-ldflags='-dynamic-libgcc -dynamic-libstdc++' --with-boot-ldflags='-dynamic-libgcc -dynamic-libstdc++'
Thread model: single
gcc version 6.5.0b 190909113559 (GCC)
...
/opt/amiga/bin/m68k-amigaos-gdb -v
GNU gdb (GDB) 8.3.50.190831-181535-git
...
```

**Comment by skeetor** [comment]
Thanks! Because of your answer I just realized, that I was using MSYS2 Mingw instead of msys. So my build problems and fixes that I did, were actually for mingw, and not msys. SO I will withdraw my PR and see if I can submit my patches to mingw/libiberty.
