### ISSUE TITLE
Compiling libgcc fails at libstdc++-v3/src/c++98/compatibility.cc with lea syntax error

### ISSUE THREAD

**Issue by jopadan** [bebbo/amiga-gcc#123]
[compatibility.s.txt](https://github.com/bebbo/amiga-gcc/files/3613904/compatibility.s.txt)

Compiling on amd64 Linux 5.2.14-gentoo #2 SMP PREEMPT Wed Sep 11 16:08:46 CEST 2019 x86_64 Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz GenuineIntel GNU/Linux

 synax error -- statement lea (%pc, _GLOBAL_OFFSET_TABLE_@GOTPC), a4 ignored

The code is emitted at gcc/config/m68k/m68k.md:7370 and seems to be related to
[https://cygwin.com/ml/crossgcc/2001-10/msg00050.html](url)
I created a report at gcc bugzilla too:
[https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91829](url)

**Comment by bebbo** [comment]
not enough details.

**Comment by bebbo** [comment]
no updates
