### ISSUE TITLE
Slow stderr on 1.3 (unbuffered?)

### ISSUE THREAD

**Issue by alexalkis** [bebbo/amiga-gcc#126]
On the same archive as [source.zip](https://github.com/bebbo/amiga-gcc/files/3671902/source.zip) issue #125 

If you run it on a500+ and just type 
hcc
and then
top
you can visually see that the output for top is very slow (almost like writting character by character)

Now the difference in the source code is that hcc uses printf while top uses fprintf(stderr, ...), so maybe it's a buffer issue?

**Comment by bebbo** [comment]
"The stream stderr is unbuffered. ...
The buffering mode of the standard streams (or any other stream) can be changed using the setbuf(3) or setvbuf(3) call. ..."

**Comment by alexalkis** [comment]
I would expect stdout and stderr to have the same "perfomance".  That's why I registered it as an issue.

Assuming from your reply that it's by design...so closing this :)
