### ISSUE TITLE
Question about AmigaOS inlines

### ISSUE THREAD

**Issue by nonarkitten** [bebbo/amiga-gcc#127]
I noticed recently with gngeo that there were a ton of functions on the end all looking like veneers -- simple functions to pull off the stack and call-by-register to AmigaOS. Okay, so I need to #include <proto/library.h> for each library I want.

But then it was loading A6 all the time, and I though, hey, I can make A6 a global register. Seems like SAS/C used to just do this. Anyway, I ended up with this:

https://franke.ms/cex/z/4T_L4J

That's a lot better! But I'm wondering how can I ensure A6 never get's trashed? Does gcc do this automatically, or do I need the A6 reference in every .c file? What about linked libraries?

**Comment by bebbo** [comment]
Do you have an example where a6 is reloaded?

I replaced your global register with the proper include and a6 is loaded only once: https://franke.ms/cex/z/2ldDPm

**Comment by bebbo** [comment]
maybe that program was linked against the libamiga.a?

**Comment by nonarkitten** [comment]
I could dump a disassembly from gngeo. At the end of the file, there were
dozens of functions like _AlloVec that were just pulling args from the
stack and calling the standard AmigaOS function, and they loaded SysBase
each time. You can see half the effect by removing the #include
<proto/exec.h>. _AllocVec becomes a standard GCC call and I guess it
creates the veneers later? Or like you said uses a different linker
library...?

I can eliminate them bit by bit using the right headers -- maybe once
they're all gone, the A6 issue will go away. What's the 'best practice'
here? Always use the proto/libraries?

**Comment by bebbo** [comment]
Aye - always use
```
#include <proto/exec.h>
#include <proto/whateveryouneed.h>
```
otherwise the stub functions from libamiga.a are pulled in.

**Comment by nonarkitten** [comment]
Thanks! I'll clean that up right away.
