### ISSUE TITLE
-mcrt=nix13 needs mathieeesingbas.library

### ISSUE THREAD

**Issue by alexalkis** [bebbo/amiga-gcc#130]
[piclassic.zip](https://github.com/bebbo/amiga-gcc/files/3772929/piclassic.zip)

if you compile this with
m68k-amigaos-gcc -mcrt=nix13 -o piclassic piclassic.c -lm

when run, it outputs that it needs mathieeesingbas.library but the workbench 1.3 doesn't have that library :)

ummm?

**Comment by bebbo** [comment]
grab a copy and put it there.

**Comment by alexalkis** [comment]
yeah, but mathieeesingbas.library doesn't come with 1.3.
SAS C on 1.3 compiles the code and doesn't need mathieeesingbas.library

sidenote: I am curious, does gcc on m68k has code for floats/doubles basic math and is disabled on amiga just to use libraries (and make exe smaller)?

**Comment by bebbo** [comment]
> 
> 
> yeah, but mathieeesingbas.library doesn't come with 1.3.
> SAS C on 1.3 compiles the code and doesn't need mathieeesingbas.library

you can copy a later version to 1.3 - np.

> sidenote: I am curious, does gcc on m68k has code for floats/doubles basic math and is disabled on amiga just to use libraries (and make exe smaller)?

two reasons to use the libraries:
- slightly smaller code
- more speed if the same program is run with fpu

**Comment by alexalkis** [comment]
Hmm, is it possible to have gcc math code with a command line switch in order to not rely on libs: (and sometimes buggy libraries, as we've established) ??? Or it doesn't worth it?

**Comment by bebbo** [comment]
> 
> 
> Hmm, is it possible to have gcc math code with a command line switch in order to not rely on libs: (and sometimes buggy libraries, as we've established) ??? Or it doesn't worth it?

That's a decision of the library's implementor: clib2 and the default behave different than libnix (but do not support kick1.3 at all...)
