### ISSUE TITLE
a1200 crashes when printf a float

### ISSUE THREAD

**Issue by alexalkis** [bebbo/amiga-gcc#131]
[piclassic.zip](https://github.com/bebbo/amiga-gcc/files/3772929/piclassic.zip)

if you compile this with
m68k-amigaos-gcc -noixemul -O3 -o piclassic piclassic.c -lm

and run it on a1200, you'll see output and if you press enter (I've placed an fgets prior to printf a float) you get a crash.

**Comment by bebbo** [comment]
maybe some bogus math*.library?

**Comment by alexalkis** [comment]
will investigate

**Comment by alexalkis** [comment]
probably it was a bogus library.  Can't reproduce on another setup. Sorry, closing.
