### ISSUE TITLE
Cannot install amiga-gcc

### ISSUE THREAD

**Issue by TCH68k** [bebbo/amiga-gcc#135]
Hello,

I've tried to do the following:

```
git clone https://github.com/bebbo/amiga-gcc
cd amiga-gcc
make all
```

but it failed with these messages:

```
make libSDL12...failed
make[1]: Entering directory '/tmp/amiga-gcc/build-Linux/libSDL12'
/opt/amiga/bin/m68k-amigaos-gcc  -I/opt/amiga/include -I./include/ -I./include/SDL -Os -fomit-frame-pointer -m68040 -mhard-float -DNOIXEMUL -D_HAVE_STDINT_H -DNO_AMIGADEBUG -DAPOLLO_BLIT -I./video/apollo -DENABLE_CYBERGRAPHICS -DNO_SIGNAL_H -D__MEM_AMIGA -DENABLE_AHI  -o audio/SDL_audio.go -c audio/SDL_audio.c
In file included from audio/SDL_audio.c:39:0:
audio/SDL_sysaudio.h:49:25: fatal error: devices/ahi.h: No such file or directory
 #include <devices/ahi.h>
                         ^
compilation terminated.
Makefile.bax:69: recipe for target 'audio/SDL_audio.go' failed
make[1]: *** [audio/SDL_audio.go] Error 1
make libSDL12...failed
use less "log/make libSDL12.log" to view the full log and search for ***
Makefile:836: recipe for target 'build-Linux/libSDL12/_done' failed
make: *** [build-Linux/libSDL12/_done] Error 2
```

Should i provide `ahi.h` or the process supposed to be install it?

Edit: github's codeblock is useless.

**Comment by bebbo** [comment]
- are you sure this is the first error?
- is the prefix folder writeable?

**Comment by TCH68k** [comment]
Yes i am. Here is the full log of the build: http://oscomp.hu/depot/amiga-gcc.log
Also, here is the mentioned libSDL12.log, but contains the very same error message: http://oscomp.hu/depot/make_libSDL12.log

Of course the folder is writeable. A lot of stuff is already created in `/opt/amiga/`.

**Comment by bebbo** [comment]
```
...
Makefile.bax:69: recipe for target 'audio/SDL_audio.go' failed
make[1]: *** [audio/SDL_audio.go] Error 1
make libSDL12...failed
use less "log/make libSDL12.log" to view the full log and search for ***
...
```
so what's inside `"log/make libSDL12.log"` ?

**Comment by TCH68k** [comment]
I've shared the link in my previous post:

> Also, here is the mentioned libSDL12.log, but contains the very same error message: http://oscomp.hu/depot/make_libSDL12.log

**Comment by bebbo** [comment]
oh - sorry :-)

so something in `make sdk=ahi` went wrong... if the ahi headers are missing

**Comment by TCH68k** [comment]
Seems you're right: http://oscomp.hu/depot/sdk_ahi.log

```
/root/amiga-gcc/sdk/install: sor: 34: /opt/amiga/bin/lha: Nincs ilyen fájl vagy könyvtár
```
/opt/amiga/bin/lha does not exists.
I have `lha` v1.14i in `/usr/bin`, i thought the script can use it, but it seems, `lhasa` is not replacable with `lha`. Removed the latter one and installed the former. I'm retrying the build again.

**Comment by bebbo** [comment]
if you don't provide `lha` then a working version is built from source.

**Comment by bebbo** [comment]
```
lha
LHarc    for UNIX  V 1.02  Copyright(C) 1989  Y.Tagawa
LHx      for MSDOS V C2.01 Copyright(C) 1990  H.Yoshizaki
LHx(arc) for OSK   V 2.01  Modified     1990  Momozou
LHa      for UNIX  V 1.00  Copyright(C) 1992  Masaru Oki
LHa      for UNIX  V 1.14  Modified     1995  Nobutaka Watazaki
LHa      for UNIX  V 1.14i Modified     2000  Tsugio Okamoto
LHA-PMA  for UNIX  V 2     PMA added    2000  Maarten ter Huurne
                   Autoconfiscated 2001-2008  Koji Arai
usage: lha [-]<commands>[<options>] [-<options> ...] archive_file [file...]
  commands:  [axelvudmcpt]
  options:   [q[012]vnfto[567]dizg012e[w=<dir>|x=<pattern>]]
  long options: --system-kanji-code={euc,sjis,utf8,cap}
                --archive-kanji-code={euc,sjis,utf8,cap}
                --extract-broken-archive
                --convert-filename-case
                --ignore-mac-files
                --timestamp-archive
                --traditional
                --help
                --version
commands:                           options:
 a   Add(or replace) to archive      q{num} quiet (num:quiet mode)
 x,e EXtract from archive            v  verbose
 l,v List / Verbose List             n  not execute
 u   Update newer files to archive   f  force (over write at extract)
 d   Delete from archive             t  FILES are TEXT file
 m   Move to archive (means 'ad')    o[567] compression method (a/u/c)
 c   re-Construct new archive        d  delete FILES after (a/u/c)
 p   Print to STDOUT from archive    i  ignore directory path (x/e)
 t   Test file CRC in archive        z  files not compress (a/u/c)
                                     g  Generic format (for compatibility)
                                     0/1/2 header level (a/u/c)
                                     e  TEXT code convert from/to EUC
                                     w=<dir> specify extract directory (x/e)
                                     x=<pattern>  eXclude files (a/u/c)
```

**Comment by TCH68k** [comment]
>  if you don't provide `lha` then a working version is built from source.

That did not happen, it did not build it. Also, `lha` was provided (v1.14i), it just was not from the `lhasa` package.
Maybe the problem was, that there was an `lha`, so the script did not build it, but it was the wrong version, so the script could not use it?

Anyway, i've installed `lhasa` and the build is on the way. The crash occurred roughly after 90 min, so, soon we'll know more.

**Comment by bebbo** [comment]
you can speedup the build by using more/all cpu cores.
```
make all -j3
```
will use 3 cores to build.

**Comment by TCH68k** [comment]
Uhhh...i'm stupid, i forgot to pass the multi-core option. Thanks for reminding me.

**Comment by TCH68k** [comment]
Done. Everything worked. Thanks for the help.

Should i provide something to help debug this `lha` vs `lhasa` issue, or it's not needed?
If not, i think the readme should be mention that `lha` in the Debian/Ubuntu repositories will not work with the script, and `lhasa` is mandatory.

**Comment by bebbo** [comment]
Great! You made it!!

I think it's ok. Other folks will find this issue and are able to resolve it.
Eventually I'll ipdate the README^^

**Comment by bebbo** [comment]
BTW: the README already points out that `lhasa` must be used.

**Comment by TCH68k** [comment]
Yeah, it does, but it does not points out, that it cannot be replaced with `lha`.
And now i think, this is a problem, because `lhasa` cannot create archives, just extract them, while `lha` can. I had to remove `lhasa` and install `lha` again. Of course i can live with that, if i have to remove `lha` before compiling amiga-gcc, and reinstall it after it has been compiled, but i think supporting `lha` too would be the better solution.

**Comment by bebbo** [comment]
> .... but i think supporting `lha` too would be the better solution.

that's an `lha` issue: if this tool is able to extract the archives, it can be used.

And if you install neither `lha` nor `lhasa` you'll end up with a self compiled version which can extract these archives and is able to create new ones.
