### ISSUE TITLE
#define AddICRVector is wrong inside ndk-include/inline/cia.h

### ISSUE THREAD

**Issue by Slamy** [bebbo/amiga-gcc#136]
In ndk-include/inline/cia.h it's supposed to be LP3NB which sadly does not exist.
But inside macros.h it says it's LP3UB.
A workaround for me seems to be the replacement of LP3NB by LP3UB.
RemICRVector has a similar issue.

**Comment by bebbo** [comment]
sorry - but your setup seems wrong, on a fresh build macros.h contains the correct ones:
```
/* Only cia.resource/AbleICR() and cia.resource/SetICR() */
#define LP2NB(offs, rt, name, t1, v1, r1, t2, v2, r2)           \
({                                                              \
...
```

**Comment by bebbo** [comment]
```
/* Only cia.resource/AddICRVector() */
#define LP3NB(offs, rt, name, t1, v1, r1, t2, v2, r2, t3, v3, r3) \
({                                                              \
...
```

**Comment by Slamy** [comment]
You were right. I've made a fresh build today. This is solved
