### ISSUE TITLE
Issue when building

### ISSUE THREAD

**Issue by ianshk** [bebbo/amiga-gcc#138]
Getting the following error when I build the project.

Cloning into 'gcc'...
remote: Enumerating objects: 101734, done.
remote: Counting objects: 100% (101734/101734), done.
remote: Compressing objects: 100% (77618/77618), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
make: *** [projects/gcc/configure] Error 128

**Comment by bebbo** [comment]
that's rather a git issue. Keep retrying.

Sorry can't help here.
