### ISSUE TITLE
$(PWD) is not expanded correctly under cygwin

### ISSUE THREAD

**Issue by tehKaiN** [bebbo/amiga-gcc#14]
I've got errors like:

```
D:\prg\_git\amiga-gcc>make all PREFIX=d:/prg/kompilatory/bebbo -j4
cd build/gcc && CFLAGS="-Os" CPPFLAGS="-Os" CXXFLAGS="-Os" LIBCFLAGS_FOR_TARGET="-Os -g -fomit-frame-pointer" /projects/gcc/configure --prefix=d:/prg/kompilatory/bebbo --target=m68k-amigaos --enable-languages=c,c++,objc --enable-version-specific-runtime-libs --disable-libssp --disable-nls
/bin/bash: /projects/gcc/configure: No such file or directory
built d:/prg/kompilatory/bebbo/bin/fd2sfd
built d:/prg/kompilatory/bebbo/bin/fd2pragma
make: *** [Makefile:201: build/gcc/Makefile] Error 127
```

As you can see  in `cd build/gcc && $(E) $(PWD)/projects/gcc/configure $(CONFIG_GCC)` PWD gets expanded to blank string. After changing all PWD occurences to `$(CURDIR)` everything built fine.

I'm also building toolchain under Armbian right now and everything works fine with PWD, so I guess it's Cygwin-related.

**Comment by bebbo** [comment]
I am building with cygwin on different machines and everything is fine.

Maybe your cygwin is bogus? Does `echo $PWD` work for you?

**Comment by tehKaiN** [comment]
Silly me! I forgot to enter sh, compiled directly from cmd while having cygwin's bin directory in PATH. I don't use cygwin on a daily basis (I prefer compiling other stuff natively with mingw), so that's it.
