### ISSUE TITLE
compiling fails on linux

### ISSUE THREAD

**Issue by alexalkis** [bebbo/amiga-gcc#140]
After git pull
make update
make clean
rm -rf /opt/amiga/gcc6

make all -j8 PREFIX=/opt/amiga/gcc6
configure binutils...configure fd2sfd...make fd2sfd...make ira...configure sfdc...fatal: destination path 'libSDL12' already exists and is not an empty directory.
Makefile:853: recipe for target 'projects/libSDL12/Makefile.bax' failed
make: *** [projects/libSDL12/Makefile.bax] Error 128
make: *** Waiting for unfinished jobs....
configure sfdc...done
configure fd2sfd...done
configure binutils...done
make ira...done
make fd2sfd...done

**Comment by bebbo** [comment]
I guess the project libSDL12 has changed without asking me^^

**Comment by RasmusEdgarDSG** [comment]
Removing the .bax extension from the libSDL12 sections of the amiga-gcc main makefile seems to fix the problem.

**Comment by RasmusEdgar** [comment]
Removing the .bax extension from the libSDL12 sections of the amiga-gcc main makefile seems to fix the problem.

**Comment by colmiga** [comment]
Had the same issue. Looking at the commit history of the repo, it appears the Makefile was made to be the same as Makefile.bax and the Makefile.bax file was deleted yesterday, hence the build issues with libSDL.

**Comment by alexalkis** [comment]
fixed. thanks!
