### ISSUE TITLE
ASM includes only in ndk-include

### ISSUE THREAD

**Issue by skeetor** [bebbo/amiga-gcc#141]
When I was looking for the assembler include files, I only found them in the ndk-include directory hierarchy. Are this include files for Amiga OS 2.x+ or can they also be used for 1.3? Or do I have to look elsewhere to get Amiga OS 1.3 include files?

**Comment by bebbo** [comment]
The c-headers for KS1.3 are generated by stripping/patching the KS2.0 headers.
Someone has to provide a similare script + patch files for the ASM headers.

But if you are using these carefully (not using KS2.0 features) the KS2.0 asm headers will work too.

**Comment by skeetor** [comment]
OK. No Problem.
