### ISSUE TITLE
-fprofile-arcs -ftest-coverage doesn't produce any *.gcda files when executed

### ISSUE THREAD

**Issue by Slamy** [bebbo/amiga-gcc#142]
I've tried to use code coverage but it seems to not produce any result files after execution of the binary. As it seems from previous issues that it was supported in the past I decided to create an issue.
Just "hello world" with a single printf compiled with your current HEAD using these parameters:
m68k-amigaos-gcc test.c -fprofile-arcs -ftest-coverage  -lgcov -o test
test.gcno is generated during compilation. When the program is executed I would assume test.gcda to be created.
But maybe I'm missing something here. One issue with your project, even so it's a masterpiece, is the lack of examples. As someone with not that much experience with gcov I also tried executing __gcov_flush(); at the end. But that only seems cause a crash.

**Comment by Slamy** [comment]
At this point I would also like to inform you that it's impossible to build older versions of this repository as "make update" just pulls the current master. I encourage you to switch over to "git submodules" which is the official system of git to have other git projects inside a top level one.
The nice thing about submodules is that it not only references the external repo but also a certain revision. So everytime you check out a specific version of this repository you also get the fitting other repos as well to reproduce older versions.

**Comment by bebbo** [comment]
> as "make update" just pulls the current master. I encourage you to switch over to "git submodules"

To achieve what you call 'impossible' can be done by

```
# reset to current version
make v
# select the versions for a given time stamp
make v D=2019-11-01
```

**Comment by Slamy** [comment]
To begin with it was my goal to maybe assist a bit by making a regression test. Building older versions like 2018-06-09 or such to see which change maybe has broken gcov support.
But I've had several difficulties.
- --depth x had to be removed first from the Makefile to allow selecting older versions.
- make v D=2019-11-01 didn't work on my machine. make just ignores the parameter. I had to insert it directly instead of $(date) to make it change.
- older versions weren't buildable. I've tried some. But maybe it's just that my gcc is not the one you have originally used during 2018. That could break something i guess.

So I'm sorry that I can't help. I'm not even sure if I have used gcov correctly with your toolchain.
With m68k-elf-gcc paired with newlib and libgloss I have to manually call function pointers stored in the .ctors section to actually make gcov initialize itself. The same counts for flushing it.

Well at this point I assume that you are far more familiar with your workflow. So at least I've opened an issue to have you noticed.

**Comment by bebbo** [comment]
please test again

**Comment by Slamy** [comment]
To be sure, I've cloned the repo again and built it from scratch. Sadly the symptoms are the same. No *.gcda file is generated. Do you have tested it by yourself?
I think I can also see whats wrong.

I've compiled a small hello world program with `m68k-amigaos-gcc test.c -fprofile-arcs -ftest-coverage -lgcov -o test -Xlinker -Map=output.map `

According to the map file the gcov functions from libgcov are just stubs.
` .text          0x000000000000035c        0x4 /opt/m68k-amigaos5/lib/gcc/m68k-amigaos/6.5.0b/libgcov.a(_gcov_merge_add.o)
                0x000000000000035c                __gcov_merge_add

 .text          0x0000000000000360        0x4 /opt/m68k-amigaos5/lib/gcc/m68k-amigaos/6.5.0b/libgcov.a(_gcov_flush.o)
                0x0000000000000360                __gcov_flush

 .text          0x0000000000000364        0x4 /opt/m68k-amigaos5/lib/gcc/m68k-amigaos/6.5.0b/libgcov.a(_gcov.o)
                0x0000000000000364                __gcov_init`

Also the static constructor for gcov usually generated by gcc for every C file is missing.
On m68k-elf-gcc this looks like this:
`
.ctors.65435   0x000000000003e74c        0x4 CMakeFiles/main.elf.dir/subApp_gameloop.o

.ctors.65435   0x000000000003e750        0x4 CMakeFiles/main.elf.dir/subApp_horizontalGame.o
`
Maybe this helps. One day after creating this issue here I've fixed it for m68k-elf-gcc. Maybe it's the same problem.

https://github.com/Slamy/m68k-elf-gcc/commit/dff73b786947eb877d0ef5b30fbe4aa214bd9f40

There seems to be a correlation to `--with-headers` which I thought is not needed. But as it turned out it makes a difference.

I got this suggestion from here:
https://gcc.gcc.gnu.narkive.com/5gzkbf7A/newlib-libgcov

**Comment by bebbo** [comment]
I followed this tutorial: https://www.linuxtopia.org/online_books/an_introduction_to_gcc/gccintro_81.html

```
m68k-amigaos-gcc -Wall -fprofile-arcs -ftest-coverage cov.c -noixemul -o cov -lgcov -fprofile-dir=/test
```
note that the files are copied to Amiga into a folder named `test`.
```
cp cov /mnt/d/test/
cp cov.gcno /mnt/d/test/
```
now `cov` is run on the Amiga.
```
3.Work:develop/test> cov
3 is divisible by 3
6 is divisible by 3
9 is divisible by 3
```
then copy the files back
```
cp  /mnt/d/test/cov.g* .
```
and run gcov
```
> m68k-amigaos-gcov cov
File 'cov.c'
Lines executed:85.71% of 7
Creating 'cov.c.gcov'
```
and voilá
```
> cat cov.c.gcov
$ cat cov.c.gcov 
        -:    0:Source:cov.c
        -:    0:Graph:cov.gcno
        -:    0:Data:cov.gcda
        -:    0:Runs:1
        -:    0:Programs:1
        -:    1:#include <stdio.h>
        -:    2:
        -:    3:int
        1:    4:main (void)
        -:    5:{
        -:    6:  int i;
        -:    7:
       10:    8:  for (i = 1; i < 10; i++)
        -:    9:    {
        9:   10:      if (i % 3 == 0)
        3:   11:        printf ("%d is divisible by 3\n", i);
        9:   12:      if (i % 11 == 0)
    #####:   13:        printf ("%d is divisible by 11\n", i);
        -:   14:    }
        -:   15:
        1:   16:  return 0;
        -:   17:}
        -:   18:
```
this looks like the result in the tutorial

**Comment by Slamy** [comment]
I don't get it. It looks so good on your side. I downloaded cov.c and did the same as you.
`/opt/m68k-amigaos5/bin/m68k-amigaos-gcc -Wall -fprofile-arcs -ftest-coverage cov.c -noixemul -o cov -lgcov -fprofile-dir=/test`

`cp cov cov.gcno  ~/Amiga/Work/test`

On the Amiga:
`3.Work:test> cov`

I get the console output like you but no additional file is created.
Have you changed something inside your toolchain to get this working? Or did it work directly out of the box with the last versions also?
Have you maybe forgotten to push the change so it's only working on your machine?

I'm confused.

**Comment by bebbo** [comment]
there was a change to libnix - the initialization for getenv(...) was broken, und thus it failed. (libnix:0e8a2f427e0b830224f9fd4c94a8fa8b2b8b285b)

**Comment by Slamy** [comment]
I've again made a fresh build after a fresh checkout to cure my confusion and it seems there is a regression from today afternoon to today evening.
I get guru 8000 0006 after cov has printed its output whenever I compile with -fprofile-arcs -ftest-coverage.
I do save every new build of your project so I know that it didn't happen before.

**Comment by bebbo** [comment]
please attach one/some of your executables

**Comment by bebbo** [comment]
do you use a sufficient stack size?
```
3.Work:develop/test> stack
Current stack size is 100000 bytes
```

**Comment by Slamy** [comment]
I'm amazed and disturbed at the same time. Mr. bebbo, you are the man.
My stack was 4096 bytes. And I don't even know where this value is coming from and why I should have thought about increasing it in the first place.
And why stack? What is so heavy? 4k of stack should be enough for a 68k application. Concerning gcov I would've assumed that it might be a burden on the heap or on .data.

It does now work. And you were right with -profile-dir=/test. If absent the system tries to write directly to the build folder which is impossible.
Thanks a lot for your support.
