### ISSUE TITLE
Custom startup and linking order

### ISSUE THREAD

**Issue by dwhinham** [bebbo/amiga-gcc#144]
Hi bebbo,

I'm not sure if I'm doing something wrong here so was hoping you could help.
I want to link a custom ASM startup routine with some C code, but even if I put my `startup.o` before the `main.c` in the arguments to `gcc`, I get an executable that crashes.

With this ASM code (**startup.s**):
```
	xdef	_SysBase
        xref    _main
        xref    ___a4_init

		section	.code,code
start:
        lea     ___a4_init,a4
		movea.l	4.L,a0
		move.l	(a0),_SysBase
        jsr     _main
		rts

		section	.data,data
_SysBase:
		dc.l	0
```

and this C code (**main.c**):
```
#include <stdlib.h>

#include <proto/dos.h>
#include <proto/exec.h>

struct DosLibrary* DOSBase;

int main()
{
    DOSBase = (struct DosLibrary*) OpenLibrary("dos.library", 0L);
    if (!DOSBase)
         return EXIT_FAILURE;

    Write(Output(), "Hello world\n", 12);

    return EXIT_SUCCESS;
}
```

built with the following commands:
```
vasmm68k_mot.exe -Fhunk -m68000 -o startup.o startup.s
m68k-amigaos-gcc -nostartfiles -nostdlib -fbaserel -Os -msmall-code -o hello startup.o main.c
ira hello hello.asm
```

I get an executable that looks like this if I disassemble it with IRA:
```
; IRA V2.09 (Sep 10 2019) (c)1993-1995 Tim Ruehsen
; (c)2009-2015 Frank Wille, (c)2014-2017 Nicolas Bastien

ABSEXECBASE	EQU	$4

	SECTION S_0,CODE

__stext:
	DC.W	$646f
	DC.W	$732e
	DC.W	$6c69
	DC.W	$6272
	DC.W	$6172
	DC.W	$7900
LAB_0001:
	DC.W	$4865
	DC.W	$6c6c
	BLE.S	LAB_0004
	DC.W	$776f
	MOVEQ	#108,D1
	BCC.S	LAB_0003
	DC.W	$0000
_main:
	MOVEM.L	D2-D3/A6,-(A7)
	MOVEA.L	-32766(A4),A6
LAB_0003:
	MOVEQ	#0,D0
	LEA	__stext(PC),A1
	JSR	-552(A6)
	MOVE.L	D0,-32762(A4)
	BEQ.S	LAB_0006
LAB_0004:
	MOVEA.L	D0,A6
	JSR	-60(A6)
	MOVEA.L	-32762(A4),A6
	LEA	LAB_0001(PC),A0
	MOVE.L	D0,D1
	MOVE.L	A0,D2
	MOVEQ	#12,D3
	JSR	-48(A6)
	MOVEQ	#0,D0
LAB_0005:
	MOVEM.L	(A7)+,D2-D3/A6
	RTS
LAB_0006:
	MOVEQ	#1,D0
	BRA.S	LAB_0005
	DC.W	$0000


	SECTION S_1,DATA

__etext:
	DS.L	1
_DOSBase:
	DS.L	1


	SECTION S_2,CODE

SECSTRT_2:
	LEA	__etext+32766,A4
	MOVEA.L	ABSEXECBASE,A0
	MOVE.L	(A0),__etext
	JSR	_main
	RTS
	NOP
	END
```

So it looks like the strings for `"dos.library"` and  `"Hello world"` are being put at the start of the program in the code section, but my startup code is being put at the very end.

How do I ensure that my startup code is placed at the beginning of the executable? Am I doing something wrong?

Thanks!

**Comment by bebbo** [comment]
```
    section .text,code
```

**Comment by dwhinham** [comment]
Ahhh, that simple, thankyou for the quick reply - it works!

Is this because GCC's default code section name is ".text", and so if I name the ASM section the same it is automatically merged in the order they appear on the command line?

Thanks again and Merry Christmas 😃
