### ISSUE TITLE
m68k-amigaos-objdump -D issue

### ISSUE THREAD

**Issue by alexalkis** [bebbo/amiga-gcc#145]
Hey happy new year!

If you take this
[main.zip](https://github.com/bebbo/amiga-gcc/files/4020300/main.zip)
and
m68k-amigaos-gcc -s -Os -nostdlib -o foo main.s

and then
m68k-amigaos-objdump -D foo

`  16:   23c0 0000 0087  move.l d0,0x87

  1c:   2c7a 0069       movea.l 0x87(pc),a6
`
16 ommits "(pc)" at the end.

**Comment by bebbo** [comment]
Happy New Year 7E4!

there is no
```
    move.l d0,n(pc)
```
instruction.

**Comment by alexalkis** [comment]
Hmm, I am confused.  So, line at 16 above stores d0 at 0x87 absolute?

**Comment by bebbo** [comment]
> 
> 
> Hmm, I am confused. So, line at 16 above stores d0 at 0x87 absolute?

dont' forget the reloc. It is stored at offset 0x87 from section start. (you should use align 2 for even addresses)

**Comment by alexalkis** [comment]
Oh, ok.  I got it.

**Comment by bebbo** [comment]
hint also display the relocs:
```
m68k-amigaos-objdump -Dr foo
```

**Comment by alexalkis** [comment]
That's good to know. Thanks!
