### ISSUE TITLE
README is missing the rsync dependency

### ISSUE THREAD

**Issue by midwan** [bebbo/amiga-gcc#147]
It seems that `rsync` is also required in order to do a `make all`:

```
~/amiga-gcc$ make all -j6
configure binutils.../bin/bash: rsync: command not found
```

**Comment by bebbo** [comment]
so it seems your `toast os` does not provide it...

**Comment by midwan** [comment]
It does, I installed it and it worked after that. Testing it on WSL Debian under Win10.
I'm just mentioning that to get it included in the readme. ;-)
