### ISSUE TITLE
Support for exceptions

### ISSUE THREAD

**Issue by Slamy** [bebbo/amiga-gcc#148]
Hey bebbo,
I've noticed that you've disabled support for exceptions in C++.
Is there a particular reason for this? I've tried to make a build without -fno-exceptions but it seems that exceptions cause a crash. This might not be a biggy. It just limits the use of the C++ part of this toolchain a bit, as some code heavliy relies on error handling by exceptions.

**Comment by bebbo** [comment]
perdon?

```
$ vi x.cc
#include <stdio.h>
int main () {
  try
  {
    throw 20;
  }
  catch (int e)
  {
          printf("exception with %d\n", e);
  }
  return 0;
}
ESC:wq

$ m68k-amigaos-g++ x.cc -o x -noixemul
$ vamos x
exception with 20
```

**Comment by Slamy** [comment]
You know. Whenever I open up a ticket here I kinda feel like an idiot.
"-noixemul" did the trick. Still someone else might stumble on this so I guess the existence of this issue will help the next person.

**Comment by bebbo** [comment]
> You know. Whenever I open up a ticket here I kinda feel like an idiot.
> "-noixemul" did the trick. Still someone else might stumble on this so I guess the existence of this issue will help the next person.

sorry, I can't make `-noixemul` the default - that's reserved for ixemul, once it builds again

**Comment by Slamy** [comment]
It's no big problem as your toolchain is otherwise very functional. But I believe that an example folder is what this project of yours is really lacking. Something to help outsiders to understand and use it.
2 years ago you had one in your older project. That really helped me getting into this.
