### ISSUE TITLE
Trashed registers when optimizing register-passed float/double arguments

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [bebbo/amiga-gcc#15]
Consider that piece of code:
```
#if 0
/opt/amiga/bin/m68k-amigaos-gcc-6.4.1b -Wall -O1 -fomit-frame-pointer -ffast-math -funroll-all-loops -funsafe-math-optimizations -m68030 -m68881 -S $0 -o -
exit
#endif

float f1(float a __asm("fp0"));
float f2(float a __asm("fp0"));

float f3(float a __asm("fp0")) {
	float v1 = f1(a), v2 = f2(a);
	return v1+v2;
}
```
And compile it (just 'sh' it) and inspect the generated asm:
```
$ sh bug_gcc6/tst.c
#NO_APP
        .text
        .align  2
        .globl  _f3
_f3:
        move.l d2,-(sp)
        jsr _f1                   ; <===== fp0 transhed!!
        move.l d0,d2
        jsr _f2                   ; <===== bug!!! f2 will use a trashed argument
        fsmove.s d2,fp0
        fsadd.s d0,fp0
        fmove.s fp0,d0
        move.l (sp)+,d2
        rts
```

The asm code is totally broken. the value of fp0 in f3() isn't preserved and reused to call f2(). Actually f2 is called with garbage in fp0. It looks like the optimizer did remove some important code because when compiling with -O0, one gets a correct asm:
```
_f3:
        lea (-12,sp),sp
        fmove.s fp0,(sp)
        fmove.s (sp),fp0
        jsr _f1
        move.l d0,8(sp)
        fmove.s (sp),fp0
        jsr _f2
        move.l d0,4(sp)
        fmove.s 8(sp),fp0
        fadd.s 4(sp),fp0
        fmove.s fp0,d0
        lea (12,sp),sp
        rts
```
Notice that this issue doesn't happen when using doubles, but another trouble occurs: one fp-reg isn't preserved!
```
_f3:
        fmovem #20,-(sp)               ; <=== pushes fp4 onto stack, but not fp2!!!
        fmove.x fp0,fp4
        jsr _f1
        move.l d1,-(sp)
        move.l d0,-(sp)
        fmove.d (sp)+,fp2              ; <=== fp2 is modified but not preserved in the prologue of the function
        fmove.x fp4,fp0
        jsr _f2
        move.l d1,-(sp)
        move.l d0,-(sp)
        fmove.d (sp)+,fp0
        fadd.x fp2,fp0
        fmove.d fp0,-(sp)
        move.l (sp)+,d0
        move.l (sp)+,d1
        fmovem (sp)+,#40
        rts
```

BTW: 
1) why does gcc always wants to return floats (and double) in d0(/d1) ? this requires lots of useless stack-moves. It would have been better if gcc returned float/doubles in fp0 when fpu code is generated. 

2) even with double being returned in d0/d1, the above code looks sub-optimal (in addition of being bogus). Once d0/d1 are pushed onto the stack, they don't need to be pop'ed immediately to fp2. If it was differed upto the fadd one woudn't need fp2 at all (fadd.d (sp)+,fp0 doesn't need an fp-reg).

Actually using the stack instead of fp-regs to store the temporary results of fpu computation makes sense since 1) it prevents allocating an extra fp-reg to hold the temporary value (which is no reused) and 2) gcc already uses the stack to converrt data-regs info fp-regs.

**Comment by bebbo** [comment]
This is a gcc issue.

**Comment by Samuel-DEVULDER** [comment]
What does that mean? Did I report to the wrong place ?

**Comment by bebbo** [comment]
see https://github.com/bebbo/gcc/issues/30

**Comment by bebbo** [comment]
updated https://github.com/bebbo/gcc/issues/30
