### ISSUE TITLE
libpthread build failed when build with dockerfile

### ISSUE THREAD

**Issue by bpstudio** [bebbo/amiga-gcc#150]
make libpthread...failed
make[1]: Entering directory `/amiga-gcc/build-Linux/libpthread'
gcc -Wall -I. -g -DDEBUG   -c -o pthread.o pthread.c
pthread.c:26:25: fatal error: dos/dostags.h: No such file or directory
 #include <dos/dostags.h>
                         ^
compilation terminated.
make[1]: *** [pthread.o] Error 1
make libpthread...failed
use less "log/make libpthread.log" to view the full log and search for ***
make: *** [build-Linux/libpthread/_done] Error 2
The command '/bin/sh -c git clone https://github.com/bebbo/amiga-gcc && cd amiga-gcc && make update && make all' returned a non-zero code: 2

**Comment by bebbo** [comment]
`/bin/sh -c git clone https://github.com/bebbo/amiga-gcc && cd amiga-gcc && make update && make all` yields
```
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
...
```

**Comment by bebbo** [comment]
It's still working as expected.
```
tmp$ x=$(date);git clone https://github.com/bebbo/amiga-gcc && cd amiga-gcc && make all -j;echo $x $(date)
...
install libgcc...done
Sat Feb 22 10:07:18 CET 2020 Sat Feb 22 10:20:54 CET 2020
```
( 13mins 36 seconds)

This is the wrong place for Docker Support
