### ISSUE TITLE
Compilation error on commodity library function

### ISSUE THREAD

**Issue by alexalkis** [bebbo/amiga-gcc#151]
[aswarm.zip](https://github.com/bebbo/amiga-gcc/files/4266697/aswarm.zip)
If you type make you get:

ASwarm.c: In function 'BlankerAction':
ASwarm.c:826:26: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
  IE=(struct InputEvent *)CxMsgData(CxMsg);
                          ^
ASwarm.c:826:26: error: '_CxMsgData_v1' undeclared (first use in this function)
  IE=(struct InputEvent *)CxMsgData(CxMsg);
                          ^
ASwarm.c:826:26: note: each undeclared identifier is reported only once for each function it appears in
ASwarm.c:826:26: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
  IE=(struct InputEvent *)CxMsgData(CxMsg);
                          ^
ASwarm.c:826:26: error: '_n1' undeclared (first use in this function)
  IE=(struct InputEvent *)CxMsgData(CxMsg);
                          ^
ASwarm.c:826:26: error: expected ';' before '__asm'
  IE=(struct InputEvent *)CxMsgData(CxMsg);

The tool that creates the inlines has a problem on commodity library?

**Comment by bebbo** [comment]
It's a naming problem:
```
VOID_INTERRUPT BlankerAction(CxMsg *CxMsg,CxObj *CO)
```
The variable `CxMsg` is identical to the type `CxMsg` which is valid in C/C++.
But not for the macros used herein.

**Comment by alexalkis** [comment]
Ah, makes sense. Thanks!
