### ISSUE TITLE
Exe crashes on A500 1.3 (used to work)

### ISSUE THREAD

**Issue by alexalkis** [bebbo/amiga-gcc#152]
git clone https://github.com/alexalkis/a68k
make

The exe crashes on A500.  This used to work.

**Comment by bebbo** [comment]
does it still crash? Guess it's related to changes in libnix lseek - which is still not perfect... but should good enough

**Comment by alexalkis** [comment]
Still crashes.  (-mcrt=nix13 -fbaserel -msmall-code)
I'll try to automate the makefile a bit to produce various versions.

**Comment by bebbo** [comment]
[a68k.zip](https://github.com/bebbo/amiga-gcc/files/4508037/a68k.zip)
that's what I "bake"...
... and gal.asm is compiled ok.
btw: which files are you using to test, and are these files ok?

**Comment by alexalkis** [comment]
[a68k.zip](https://github.com/bebbo/amiga-gcc/files/4509618/a68k.zip)
Ok, this is with a makefile to make several builds.
The exe's that I focused are:
a68k000-1.3, -mcrt=nix13, works
a68k000-1.3s, -mcrt=nix13 -msmall-code, works
a68k000-1.3b, -mcrt=nix13 -fbaserel, crashes
a68k000-1.3sb, -mcrt=nix13 -msmall-code -fbaserel, crashes

Binaries in the archive. Seems like -fbaserel is the cause.

**Comment by alexalkis** [comment]
> [a68k.zip](https://github.com/bebbo/amiga-gcc/files/4508037/a68k.zip)
> that's what I "bake"...
> ... and gal.asm is compiled ok.
> btw: which files are you using to test, and are these files ok?

I also test with gal.asm

**Comment by alexalkis** [comment]
hmmm, lemme repeat the tests, I don't think this VM has the last changes you've made.  Give me 30 mins.

**Comment by alexalkis** [comment]
Also, in A68kdef.h I added
#ifdef AMIGA
#define USEAMIGAOS
#endif

and now the app uses AmigaDOS calls (Open/Seek/Read etc) just in case lseek is broken.

**Comment by alexalkis** [comment]
Yeap.  All tests passed.

When switched off the AmigaDOS calls and fallback in libc calls for stdio it crashes.  I guess your suspicion for lseek still stands.

**Comment by alexalkis** [comment]
wait...you haven't switched to amigados stdio calls....how did yours worked?

**Comment by bebbo** [comment]
that's why I asked - my baked version is running - could you please provide your bad exe?

**Comment by alexalkis** [comment]
[a68k.zip](https://github.com/bebbo/amiga-gcc/files/4511231/a68k.zip)
This crashes on gal.asm at the end of "Pass 1"

**Comment by bebbo** [comment]
that one is running on my kick1.3 system and the output is ok too.

**Comment by alexalkis** [comment]
here is a bootable adf with the problem

boot
cd bin
a68k000-1.3 gal.asm
[a68k.zip](https://github.com/bebbo/amiga-gcc/files/4511809/a68k.zip)

**Comment by bebbo** [comment]
![grafik](https://user-images.githubusercontent.com/16560863/79901758-9c9b7b80-8410-11ea-8cdb-08dc2a951150.png)

**Comment by alexalkis** [comment]
*shrug* 
maybe it's a fs-uae thing...
![fs-uae](https://user-images.githubusercontent.com/16504589/79904513-6e706880-841d-11ea-896b-537504ef1ed9.png)

**Comment by alexalkis** [comment]
yeah, works on winuae :/

**Comment by alexalkis** [comment]
Originally tried on fs-uae 2.8.4 (comes with debian).  Compiled fs-uae 3.0.0, still crashes.
Hmmm, you did run a wrong a68k on your screenshot though (kind of irrelevant cause winuae runs the exe in question fine)
anyways, the "right" exe is "a68k000-1.3" inside the bin directory.

**Comment by alexalkis** [comment]
the thing is at the end of pass1 this line follows
lseek (In.fd, 0L, 0); /* "Rewind" the source file. */

:) talking about coincidence, huh?

**Comment by bebbo** [comment]
> 
> 
> Originally tried on fs-uae 2.8.4 (comes with debian). Compiled fs-uae 3.0.0, still crashes.
> Hmmm, you did run a wrong a68k on your screenshot though (kind of irrelevant cause winuae runs the exe in question fine)
> anyways, the "right" exe is "a68k000-1.3" inside the bin directory.

I did
```
cd bin
a68k000-1.3 gal.asm
```

**Comment by bebbo** [comment]
fix incoming (hopefully)

**Comment by mheyer32** [comment]
I ran the same test on a real A500, Kick 1.3 (030, 2mb fast, 1.5mb chip) and it didn't crash. Same output as shown above. No crash does not necessarily indicate no bug, though :-)

**Comment by mheyer32** [comment]
![277BF526-FB63-441F-B32F-8DC09A1A7505](https://user-images.githubusercontent.com/33539855/79911899-05193700-83d6-11ea-8e49-6aafb44c8825.jpeg)

**Comment by bebbo** [comment]
wait for the libnix fix: ETA 45mins - or switch libnix to devel1

**Comment by alexalkis** [comment]
dunno if it helps, probably not, but for what is worth...here are all invocations under vamos.
Normal runs.
Small-code runs.
pc relative runs.
small-code + pc relative bombs out.
`
alex[1]@debxvm a68k$ vamos a68k000-1.3 samples/gal.asm   
68000 Assembler - version 2.71 (April 16, 1991)
Copyright 1985 by Brian R. Anderson
AmigaDOS conversion copyright 1991 by Charlie Gibbs.

Assembling samples/gal.asm

PASS 1 line 5449
PASS 2 line 5449
End of assembly - no errors were found.
Heap usage:  -w2047,84
Total hunk sizes:  497c code, ce4 data, c5f8 BSS
Speed: 3538 lines per second. (212280 lines per minute)
alex[0]@debxvm a68k$ vamos a68k000-1.3s samples/gal.asm 
68000 Assembler - version 2.71 (April 16, 1991)
Copyright 1985 by Brian R. Anderson
AmigaDOS conversion copyright 1991 by Charlie Gibbs.

Assembling samples/gal.asm

PASS 1 line 5449
PASS 2 line 5449
End of assembly - no errors were found.
Heap usage:  -w2047,84
Total hunk sizes:  497c code, ce4 data, c5f8 BSS
Speed: 3538 lines per second. (212280 lines per minute)
alex[0]@debxvm a68k$ vamos a68k000-1.3b samples/gal.asm 
68000 Assembler - version 2.71 (April 16, 1991)
Copyright 1985 by Brian R. Anderson
AmigaDOS conversion copyright 1991 by Charlie Gibbs.

Assembling samples/gal.asm

PASS 1 line 5449
PASS 2 line 5449
End of assembly - no errors were found.
Heap usage:  -w2047,84
Total hunk sizes:  497c code, ce4 data, c5f8 BSS
Speed: 3448 lines per second. (206880 lines per minute)
alex[0]@debxvm a68k$ vamos a68k000-1.3sb samples/gal.asm 
68000 Assembler - version 2.71 (April 16, 1991)
Copyright 1985 by Brian R. Anderson
AmigaDOS conversion copyright 1991 by Charlie Gibbs.

Assembling samples/gal.asm

PASS 1 line 5449
23:44:08.056    machine:  ERROR:  ----- ERROR in CPU Run #1 -----
23:44:08.056    machine:  ERROR:  Run: 'a68k000-1.3sb': Initial PC=002094, SP=011458
23:44:08.056    machine:  ERROR:  PC=0000baf4  SR=---N-
23:44:08.056    machine:  ERROR:  D0=fffe06a9  D1=ffffffff  D2=0000497c  D3=0000125f  D4=00005615  D5=00000001  D6=00000000  D7=00000400
23:44:08.056    machine:  ERROR:  A0=0000f430  A1=000205c8  A2=fffe06a9  A3=00000000  A4=000155e6  A5=00011152  A6=0001114e  A7=000110c4
23:44:08.056    machine:  ERROR:  SP-32=00ed53 SP-28=20202020 SP-24=20316461 SP-20=74610022 SP-16=0110dc SP-12=000006 SP-08=00c580 SP-04=000000
23:44:08.056    machine:  ERROR:  SP+00=00497c SP+04=00125f SP+08=012e64 SP+12=000000 SP+16=00be82 SP+20=fffe06a9 SP+24=00497c SP+28=00125f
23:44:08.056    machine:  ERROR:  InvalidMemoryAccessError: Invalid Memory Access R(2): fe06b5
23:44:08.057       main:  ERROR:  vamos failed!
23:44:08.057     libmgr:WARNING:  can't expunge: 'dos.library' with open count 1
23:44:08.057     libmgr:WARNING:  shutdown: can't expunge 1 vamos libs/devs!
PASS 2 line alex[1]@debxvm a68k$ 
`

**Comment by alexalkis** [comment]
@mheyer32 thx for the run on the real hardware.  Would it be possible to also run "a68k000-1.3sb gal.asm" please?

Btw, nice speed you got there :)

**Comment by bebbo** [comment]
```
stefan@ZETRA:~/amiga-stuff/a68k$ vamos a68k samples/gal.asm 
68000 Assembler - version 2.71 (April 16, 1991)
Copyright 1985 by Brian R. Anderson
AmigaDOS conversion copyright 1991 by Charlie Gibbs.

Assembling samples/gal.asm

PASS 1 line 5449
PASS 2 line 5449
End of assembly - no errors were found.
Heap usage:  -w2047,84
Total hunk sizes:  497c code, ce4 data, c5f8 BSS
Speed: 3243 lines per second. (194580 lines per minute)
```

**Comment by bebbo** [comment]
speed? there you go:
![grafik](https://user-images.githubusercontent.com/16560863/79913554-1a1cb700-8424-11ea-9fc2-261ce854349f.png)

**Comment by alexalkis** [comment]
heh, I was talking about real hardware '030....

**Comment by bebbo** [comment]
please test - it's live

**Comment by alexalkis** [comment]
YES!
Everything works in fs-uae 2.8.4 and 3.0.0.
All cases. Everything!

**Comment by bebbo** [comment]
note: replacing `stderr` with `stdout` gains speed, since libnix stderr *is* unbuffered. So this is more a benchmark of the runtime lib...

**Comment by alexalkis** [comment]
Yeah, have switched that out 
https://github.com/alexalkis/a68k/commit/8986ae8daa5204f0295db2fb21a2ae9f0594ea3c
