### ISSUE TITLE
printf float does not work

### ISSUE THREAD

**Issue by TCH68k** [bebbo/amiga-gcc#154]
If i do this:
```
printf("%2.2f\n", 3.14);
printf("%2.2d\n", 3.14);
```
The result is this:
```
%2.2f
1074339512
```

**Comment by bebbo** [comment]
you have to add `-lm` for float double support.

But what do you expect by printing doubles as int??

**Comment by TCH68k** [comment]
But i did. If i would not add it, then `sin()`/`cos()` would not work; compiling would fail with these messages:
```
/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: /tmp/cca6vrAt.o: in function `RecalcCameraAngles':
/tmp/cca6vrAt.o:(.text+0xb26): undefined reference to `sin'
/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: /tmp/cca6vrAt.o:(.text+0xac2): undefined reference to `sin'
/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: /tmp/cca6vrAt.o:(.text+0xaf4): undefined reference to `sin'
/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: /tmp/cca6vrAt.o:(.text+0xa90): undefined reference to `cos'
/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: /tmp/cca6vrAt.o:(.text+0xa5e): undefined reference to `cos'
/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: /tmp/cca6vrAt.o:(.text+0xa2c): undefined reference to `cos'
```

Since %f don't work, i've checked a lot of examples, double checking that maybe i did something wrong and found an example which used it for decimals. I had no ida if it is standard, so i tried it.

**Comment by bebbo** [comment]
maybe the order is not ok and thus the `printf` from `libm.a` is not used because the version from `libnix.a` is already used

**Comment by TCH68k** [comment]
Results are the same with both lines:
```
m68k-amigaos-gcc -mcrt=nix20 -mcpu=68020 -march=68020   -lm  main.c  -o main
m68k-amigaos-gcc  -mcpu=68020 -march=68020   -lm -mcrt=nix20 main.c  -o main
```

**Comment by bebbo** [comment]
```m68k-amigaos-gcc -mcrt=nix20 -mcpu=68020 -march=68020  main.c  -o main -lm```
libs always last

**Comment by TCH68k** [comment]
I did not know that, sorry.
It works now, thank you.
