### ISSUE TITLE
soft-float multiplication and division causes GURU 8000000B

### ISSUE THREAD

**Issue by TCH68k** [bebbo/amiga-gcc#155]
I have the following code:
```
#include <stdio.h>

int main(int argc, char *argv[])
{
	float f0, f1;

	f0 = 1.0;
	f1 = 2.0;
	printf("%f\n", f0 * f1);
	return 0;
}
```
I compile it with the following options:
```
m68k-amigaos-gcc -mcrt=nix20 -mcpu=68020 -march=68020 -msoft-float  sft.c -o sft
```
And i get GURU 8000000B, so the FPU trap happened, but did not do the operation. The `math*.library` files are in `LIBS:`. Adding `-lm` did not helped this matter.
Division yields the same. However if change the operation to addition or subtraction then it works. Trigonometric functions also working perfectly (with `-lm` of course).

**Comment by bebbo** [comment]
you have to add `-lm` to get something printed (rather than %f)...

**Comment by bebbo** [comment]
since it's working here - I guess your libs do not match your cpu - or your cpu has no fpu - or ... dunno

**Comment by TCH68k** [comment]
(I could swear i already answered...did my post lost?)

Even if i added `-lm` nothing has changed, but this is irrelevant as it's not `printf` what causes the problem, but the operation itself.

My libs are from WB3.1, so they are most probably pure 68000, since they run on even a stock A500. My CPU do not have an FPU, but i compiled with the `-msoft-float` option, so the presence of an FPU should not be necessary at all.

**Comment by bebbo** [comment]
I'm using these:
[mymathlibs.zip](https://github.com/bebbo/amiga-gcc/files/4294836/mymathlibs.zip)

**Comment by TCH68k** [comment]
Thank you. `mathffp.library` was not among my libraries, by installing it, now the program works. Strange though, this library is not on the WB disks i have. Any of them. I don't even recall if i ever met this library. Whence it came?

BTW, why do you use mixed OS libs? Half of your libs are from 1.2 or 1.3 and the rest is from 2.0+ WB-s

**Comment by bebbo** [comment]
uhm - no idea - I had 68040 version and these and that and 30 years later all is messed up^^
but it's working!!

**Comment by TCH68k** [comment]
I see. Well, yes, what is important, that it works. Thanks again.

**Comment by bebbo** [comment]
I pass on this.

Any *correct* set of libraries will work. And IMHO there are bogus versions.

This can't be fixed on the compiler side.

**Comment by TCH68k** [comment]
What do you mean by correct set of libraries? I used the ones from a vanilla WB 3.1 disk, that cannot be bogus. Besides i've never met with this library before and i've [released programs before which were compiled as both soft and hardfloat](http://bgafc.t-hosting.hu/prgv.php) and they worked with the libs from WB 3.1 and WB 1.3, so SASC somehow managed to compile programs which works with the default set of librares, without an external `mathffp.library`.

However, something is very strange here. Now the same program with the same options does not work. I did not change anything. I've downloaded your libs again, overwrote mine with them and it's still the same. Compiled the program again with the line above and nothing. How this can be possible?

**Comment by TCH68k** [comment]
Okay, i've thrown out `printf` just to be sure. The program is now:
```
int main(int argc, char *argv[])
{
	float f0, f1, f2;

	f0 = 1.0;
	f1 = 2.0;
	f2 = f0 * f1;
	return f2 == 0.0 ? 1 : 0;
}
```
I compile it with:
```
m68k-amigaos-gcc -mcrt=nix20 -mcpu=68020 -march=68020 -msoft-float  sft.c  -o sft  -Wall
```
Assembly:
```
#NO_APP
	.text
	.align	2
	.globl	_main
_main:
	link.w a5,#-12
	move.l d2,-(sp)
	move.l #0x3f800000,(-4,a5)
	move.l #0x40000000,(-8,a5)
	move.l (-8,a5),-(sp)
	move.l (-4,a5),-(sp)
	jbsr ___mulsf3
	addq.l #8,sp
	move.l d0,(-12,a5)
	moveq #1,d2
	clr.l -(sp)
	move.l (-12,a5),-(sp)
	jbsr ___eqsf2
	addq.l #8,sp
	tst.l d0
	jeq .L2
	clr.b d2
.L2:
	clr.l d0
	move.b d2,d0
	move.l (-16,a5),d2
	unlk a5
	rts
```
If i change the program to:
```
int main(int argc, char *argv[])
{
	float f0;

	f0 = 1.0;
	f0 *= 2.0;
	return f0 == 0.0 ? 1 : 0;
}
```
It becomes:
```
#NO_APP
	.text
	.align	2
	.globl	_main
_main:
	link.w a5,#-4
	move.l d2,-(sp)
	move.l #0x3f800000,(-4,a5)
	move.l (-4,a5),d0
	move.l d0,-(sp)
	move.l d0,-(sp)
	jbsr ___addsf3
	addq.l #8,sp
	move.l d0,(-4,a5)
	moveq #1,d2
	clr.l -(sp)
	move.l (-4,a5),-(sp)
	jbsr ___eqsf2
	addq.l #8,sp
	tst.l d0
	jeq .L2
	clr.b d2
.L2:
	clr.l d0
	move.b d2,d0
	move.l (-8,a5),d2
	unlk a5
	rts
```
And this latter one works, due to compile-time optimization. Whatever happens during linking, calling `___mulsf3` will cause OPCODE 1111 trap.

I think i'll set up an SC environment and see if it works if i compile the first source with SC.

**Comment by bebbo** [comment]
My guess:

1. you are using an 68020 without FPU
2. you are using a kickstart/libs which contains FPU instructions.

=> you end up with a linef exception thrown from an insn inside the ROM.

E.g. use Amiga Forever a1200+8mb_31 configuration and you'll get that error.

=> you need a set of *working* kickstart/libraries.

**Comment by bebbo** [comment]
it's `IEEESPMul` in `MathIeeeSingBas.library`

**Comment by TCH68k** [comment]
It's a stock A1200 config with KickStart 3.1 and math libs from WB 3.1. There is no FPU indeed, but it should not be needed at all. I do not use Amiga Forever.

[`mathieeesingbas.library` is also part of the KickStart.](https://wiki.amigaos.net/wiki/Math_Libraries#IEEE_Single-Precision_Basic_Math_Library)

**Comment by bebbo** [comment]
so your kickstart is broken

**Comment by SamuraiCrow** [comment]
Actually, there's one other possibility:  if you have a duplicate library in libs: it will be used instead of the kickstart version.  Lose the disk based version of mathffp.library and it will revert to the ROM version. 
 
  On Fri, Mar 6, 2020 at 9:41 AM, bebbo<notifications@github.com> wrote:   
so your kickstart is broken

**Comment by bebbo** [comment]
> 
> Actually, there's one other possibility:  if you have a duplicate library in libs: it will be used instead of the kickstart version.  Lose the disk based version of mathffp.library and it will revert to the ROM version. On Fri, Mar 6, 2020 at 9:41 AM, bebbo<notifications@github.com> wrote: so your kickstart is broken — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

There is no duplicate lib.

The `jsr -$4E(a6)` in the mathieeesingbas.library is a `jmp $fcac1a` - into the ROM - and there is *surprisingly* an invalid insn: `$fe5e` ...

There are broken Kickstart ROMs

**Comment by TCH68k** [comment]
Well something is definetly broken here, but i don't think it's the KickStart. I just fired up WinUAE again, did not change anything again and now it works. Again. Inconceivable.

However here is the KickStart i use, just to make it real sure that it is broken or not: http://oscomp.hu/depot/KS31_A1200.ROM (Original filename was _"Kickstart v3.1 rev 40.68 (1993)(Commodore)(A1200).rom"_, but FTP did not allowed to upload that, i had to rename it.)

It's MD5 sum is `646773759326fbac3b2311fd8c8793ee`. I've searchded for this sum and found this page: https://github.com/RetroPie/RetroPie-Setup/wiki/Amiga
I am sure, this is a valid 3.1 KickStart ROM for A1200.

**Comment by bebbo** [comment]
try the AROS builtin ROM and it will work.

**Comment by bebbo** [comment]
Kickstart 40.63 will work too.

**Comment by TCH68k** [comment]
I use 40.63, i just linked it in my last post. (http://oscomp.hu/depot/KS31_A1200.ROM) You can check it. The AROS ROM works, but my stuff have to work with the stock configs.
As for why did it worked before, i figured it out i forgot to switch back to that version of the example program which results in a real multiplication and not an addition due to compile-time optimization. The first program is still not working.

**Comment by bebbo** [comment]
That's 40.68. And it's broken.

**Comment by bebbo** [comment]
```
3. Ram Disk:> version
Kickstart 40.68, Workbench 40.42
```

**Comment by TCH68k** [comment]
Yeah sorry, 40.63 is for A500. But i cannot put an A500 ROM into an A1200.
But why would it be broken?
All sources list this ROM as working:
http://files.swos.eu/amiga/kickroms/
https://www.ikod.se/download/
http://amigas.ru/amiftp/index.php?dir=AmiFTP/Amiga%20Kickstart%20Roms%20-%20Complete%20-%20TOSEC%20v0.04/KS-ROMs
All of them have the same MD5 sum: `646773759326fbac3b2311fd8c8793ee`
Why would it be broken?

**Comment by bebbo** [comment]
because it's mathieeesingbas.library does not work.

**Comment by bebbo** [comment]
http://blubbedev.net/e_guide_html/ch_12d.html

**Comment by TCH68k** [comment]
Oh, so it's not that particular ROM image is broken i have, but **ALL** A1200 KickStart 3.1 ROMs. I did not know that. I installed SetPatch 43.6 and now the code is working finally.
Thank you for the help and patience.
