### ISSUE TITLE
dynamic_cast<> behavior unexpected

### ISSUE THREAD

**Issue by Slamy** [bebbo/amiga-gcc#156]
Hi bebbo. I've tried to port antlr4 to AmigaDOS and compiling and linkage went fine but the behaviour at runtime was strange. I've investigated and reduced the issue to a minimal example of a failing dynamic_cast which returns null even so it shouldn't.
The strange thing is that it works in one file but doesn't work in another even so the C++ code and the assembler code (generated with option -S) for both is nearly identical.

I've checked against g++-6 and g++-9 on my linux system to be sure that it should work.
[dynfail.zip](https://github.com/bebbo/amiga-gcc/files/4332669/dynfail.zip)

First the used compiling command for AmigaDOS.
m68k-amigaos-g++ -noixemul dynamicA.cpp dynamicB.cpp
vamos a.out
A 7Derived
A 0x17d70
B 7Derived
B 0

Then on linux.
g++ dynamicA.cpp dynamicB.cpp
./a.out 
A 7Derived
A 0x7fffca466208
B 7Derived
B 0x7fffca466208

I've tried to understand it but I can't find the cause. The implementation of dynamic_cast is not to blame I think, as the function call to it is identical for both files on assembler level.
typeid(x).name() is working in every case, so RTTI is intact.

**Comment by bebbo** [comment]
that's a linker issue - raised by your code. The known way to circumvent this:

* declare ct/dt in a header
* define ct/dt in a source

=> type info is generated only once and thus always complete

**Comment by Slamy** [comment]
I'm sorry but I don't understand the solution. I assumed you mean ct=constructor and dt=destructor and declared them in the header. But the actual implementation was put in dynamicA.cpp.
But this doesn't seems to resolve the issue.
[dyncastfail2.zip](https://github.com/bebbo/amiga-gcc/files/4333351/dyncastfail2.zip)
It would help me if you could provide a working example here as a zip file so I can reproduce your workaround.

Apart from that this is still an issue. Even if a workaround exists, this breaks compatibility with already written software in C++. Is it a known bug in this particular version of the gcc which could be fixed by merging a fix from upstream?
Or is it introduced with the changes applied to the linker which are need for Hunk output?

**Comment by Slamy** [comment]
Ahhh ok it clicked.
But the issue was `virtual void mopped(){};` in the header.
If this is defined in source the problem is removed.
I still would like to have this issue open as long as there is no real fix for it if this is ok for you.

**Comment by bebbo** [comment]
> Apart from that this is still an issue. Even if a workaround exists, this breaks compatibility with already written software in C++.

that's not 100% correct, it breaks compatibility with the i386 target and very few more at gcc 6.* level, since the target needs to support `weak` variables

> Is it a known bug in this particular version of the gcc which could be fixed by merging a fix from upstream?

I'll look into gcc 10...

> Or is it introduced with the changes applied to the linker which are need for Hunk output?

No.

**Comment by bebbo** [comment]
Update: my local version generates now asm with sections supporting this weak feature:

```
.section .gnu.linkonce.r._ZTI4Base
```

Now as and ld needs to support it...

**Comment by bebbo** [comment]
```
A 7Derived
A 0x17da0
B 7Derived
B 0x17da0
```
now I need to get it back from gcc-10 to gcc-6.5...

**Comment by bebbo** [comment]
too much effort required.
use m68k-elf and run the executable through elf2hunk.

**Comment by bebbo** [comment]
your example prints now
```
A 7Derived
A 0x18958
B 7Derived
B 0x18958
```

please test
