### ISSUE TITLE
Can't compile scummvm 2.1 anymore (worked earlier)

### ISSUE THREAD

**Issue by arczi84** [bebbo/amiga-gcc#157]
That's error I get :

https://paste.ofcode.org/zyNry3PCKaSmWRxgT5WXgR

https://github.com/AmigaPorts/scummvm-amigaos3

**Comment by bebbo** [comment]
builds without problem

```
    ...
    C++      ...
    C++      base/version.o
    LINK     scummvm
```

**Comment by arczi84** [comment]
Damn... don't know what now..

**Comment by bebbo** [comment]
you might consider providing a tiny bit more details about your environment...

**Comment by arczi84** [comment]
I would like to tell you version of compiler but that seems to be broken from October.
At least here, so it is all time :
gcc version 6.5.0b 191023121710 (GCC)

I use MSYS2.
I've succefully compiled ScummVM in August last year.

Do you have precompiled last version?

**Comment by arczi84** [comment]
Ok, clean version compiles backends/platform/amigaos3/amigaos3-main.o

I think I mixed AGA with RTG and amigaos3-main.o was compied with AGA but not with RTG.

**Comment by arczi84** [comment]
Does sword2 engine work for you?

He I have compiler error:

`engines/sword2/controls.cpp: In member function 'virtual void Sword2::OptionsDialog::paint()':
engines/sword2/controls.cpp:1006:1: internal compiler error: in schedule_region, at sched-rgn.c:3214
 }`
