### ISSUE TITLE
Conflicting types of 'struct Node'

### ISSUE THREAD

**Issue by arczi84** [bebbo/amiga-gcc#158]
I get  sometimes this conflict, this time in lua.

Can we have some workaround for this?

https://paste.ofcode.org/mkeX3aWEiE5REfjBvR6STj

**Comment by SamuraiCrow** [comment]
You'll have to either rename the "Node" type in Lua or don't include exec/types.h or anything that uses exec/types.h. 
  On Sun, Mar 15, 2020 at 1:20 PM, Artur Jarosik<notifications@github.com> wrote:   


I get sometimes this conflict, this time in lua.

Can we have some workaround for this?

https://paste.ofcode.org/mkeX3aWEiE5REfjBvR6STj

**Comment by arczi84** [comment]
I know, that's what I did.
Just was thinking if we could have workaround for this in gcc.

**Comment by SamuraiCrow** [comment]
It's a namespace conflict in C.  C++ has a namespace function to help prevent this but not C. 
 
  On Sun, Mar 15, 2020 at 2:25 PM, Artur Jarosik<notifications@github.com> wrote:   


I know, that's what I did.
Just was thinking if we could have workaround for this in gcc.

**Comment by bebbo** [comment]
Can be done - needs changes to two files and
```
make clean-ndk
make ndk newlib -j
```
once it's live

**Comment by bebbo** [comment]
it's live: `sys/_timeval.h` no longer includes `devices/timer.h` and thus stuff like `string.h` no longer load `exec/types.h`

This should solve this issue. Please test
