### ISSUE TITLE
cannot find -lnix13, -lnixmain and -lnix

### ISSUE THREAD

**Issue by Nju79** [bebbo/amiga-gcc#159]
Hello Stefan,
I used your step-by-step tutorial to make amiga-gcc. I can make binaries for Kickstart 3.1 without errors, but when I want to compile to Kickstart 1.3 with this command

`m68k-amigaos-gcc hello.c -o fs-uae/hd0/hello -mcrt=nix13`

I got the following errorlines:

`/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: cannot find ncrt0.o: file or directory not found`
`/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: cannot find -lnix13`
`/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: cannot find -lnixmain`
`/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: cannot find -lnix`
`

First errorline I can handle to copy the file to my project directory. But I think, this is a bad step by me. How can I fix all this errors?

**Comment by bebbo** [comment]
there is no need to copy stuff around. Your setup is somehow broken. Please run
```
m68k-amigaos-gcc hello.c -o fs-uae/hd0/hello -mcrt=nix13
```
and provide the full output.

**Comment by Nju79** [comment]
Sometimes we all should reboot the os and start again....
So I did and set the $PATH new to 

`/opt/amiga/bin`

and tested again: Now it works!
