### ISSUE TITLE
Various build issues and assembler error

### ISSUE THREAD

**Issue by softwarefailure** [bebbo/amiga-gcc#16]
I've tried to build amiga-gcc according to the instructions. It didn't go smoothly but there were some issues, namely:

1) First `/opt/amiga` could not be created. I solved this by running `make all` as root.
2) Then `proto/exec.h` could not be found. I solved this by adding the NDK 3.9 includes to `C_INCLUDE_PATH`.
3) Then `libtool` could not be found in `amiga-gcc/build/gcc/m68k-amigaos/libstdc++-v3`. I solved this by copying the `libtool` binary that was in `amiga-gcc/build/binutils/binutils`.

Just when I thought all was solved I got the following error:

```
/home/andreas/amiga-gcc/build/gcc/./gcc/xgcc -shared-libgcc -B/home/andreas/amiga-gcc/build/gcc/./gcc -nostdinc++ -L/home/andreas/amiga-gcc/build/gcc/m68k-amigaos/libstdc++-v3/src -L/home/andreas/amiga-gcc/build/gcc/m68k-amigaos/libstdc++-v3/src/.libs -L/home/andreas/amiga-gcc/build/gcc/m68k-amigaos/libstdc++-v3/libsupc++/.libs -B/opt/amiga/m68k-amigaos/bin/ -B/opt/amiga/m68k-amigaos/lib/ -isystem /opt/amiga/m68k-amigaos/include -isystem /opt/amiga/m68k-amigaos/sys-include -I/home/andreas/amiga-gcc/build/gcc/m68k-amigaos/libstdc++-v3/include/m68k-amigaos -I/home/andreas/amiga-gcc/build/gcc/m68k-amigaos/libstdc++-v3/include -I/home/andreas/amiga-gcc/projects/gcc/libstdc++-v3/libsupc++ -Os -noixemul -Os -noixemul -std=gnu++98 -fno-implicit-templates -Wall -Wextra -Wwrite-strings -Wcast-qual -Wabi -fdiagnostics-show-location=once -frandom-seed=compatibility.lo -g -O2 -c /home/andreas/amiga-gcc/projects/gcc/libstdc++-v3/src/c++98/compatibility.cc  -fPIC -DPIC -o .libs/compatibility.o
/tmp/ccpPIpJC.s: Assembler messages:
/tmp/ccpPIpJC.s:490: Error: syntax error -- statement `lea (%pc, _GLOBAL_OFFSET_TABLE_@GOTPC), a4' ignored
make[5]: *** [compatibility.lo] Fehler 1
make[5]: Verlasse Verzeichnis '/home/andreas/amiga-gcc/build/gcc/m68k-amigaos/libstdc++-v3/src'
make[4]: *** [all-recursive] Fehler 1
make[4]: Verlasse Verzeichnis '/home/andreas/amiga-gcc/build/gcc/m68k-amigaos/libstdc++-v3/src'
make[3]: *** [all-recursive] Fehler 1
make[3]: Verlasse Verzeichnis '/home/andreas/amiga-gcc/build/gcc/m68k-amigaos/libstdc++-v3'
make[2]: *** [all] Fehler 2
make[2]: Verlasse Verzeichnis '/home/andreas/amiga-gcc/build/gcc/m68k-amigaos/libstdc++-v3'
make[1]: *** [all-target-libstdc++-v3] Fehler 2
make[1]: Verlasse Verzeichnis '/home/andreas/amiga-gcc/build/gcc'
make: *** [build/gcc/_libgcc_done] Fehler 2
```

Unfortunately, I don't know how to fix this last build error. What's wrong here?

**Comment by bebbo** [comment]
clone https://github.com/bebbo/amiga-gcc
    cd amiga-gcc
    make update
    make all -j4

you may export PREFIX=/what/u/want to specify your prefix.

Guess you should run `make clean clean-prefix` as root.
Then chown the prefix folder plus your amiga-gcc folder recursively,

Now follow the steps above.

**Comment by softwarefailure** [comment]
And this will fix the assembler error?

**Comment by softwarefailure** [comment]
But I didn't forget "make update". I exactly followed your steps from README.md, including make update.

**Comment by bebbo** [comment]
Which os/environment are you using?

**Comment by softwarefailure** [comment]
Linux Mint 17, KDE, x86 (32-bit).

**Comment by bebbo** [comment]
Well, I created a VM with Mint 18.3 32 bit, 4 cpus. Then
```
sudo mkdir /opt/amiga
sudo chown bebbo /opt/amiga
sudo apt install make git gcc g++ lhasa libgmp-dev libmpfr-dev libmpc-dev flex gettext
git clone https://github.com/bebbo/amiga-gcc
cd amiga-gcc/
make update -j
make all -j4 | tee b.log
```
no errors.
===
So please rinse and repeat and log into a file. If an error occurs, please search the first error in the log, or post the full log file (zipped)

**Comment by softwarefailure** [comment]
Keep in mind that I'm on Linux Mint 17, not 18.3, but I don't think that this is really the issue. I've entered *exactly* your instructions on a live boot image of Mint 17 and I still get the same error: `proto/exec.h` cannot be found. That is error number 2 in my original post. I'm pretty sure that errors number 3 and 4 will follow but I haven't tried that yet because you said that it should build with no errors. So let's go through it one by one. Log is attached.
[b.gz](https://github.com/bebbo/amiga-gcc/files/1855352/b.gz)

**Comment by bebbo** [comment]
Please pull amiga-gcc, rinse and repeat.

**Comment by softwarefailure** [comment]
Thanks, builds correctly now!
