### ISSUE TITLE
No args in main

### ISSUE THREAD

**Issue by skeetor** [bebbo/amiga-gcc#160]
I have this piece of code:

`int main(int argc, char *argv[])
{
	printf("args: %u  %s\n", argc, argv[0]);
	return 0;
}
`
When I call this from CLI I dont get the parameters. argc is 0.

>testprj param

Are commandline parameters not supported?

**Comment by bebbo** [comment]
use `-noixemul`

**Comment by bebbo** [comment]
```
 cat >agc160.c <<EOF
#include "stdio.h"
int main(int argc, char *argv[])
{                               
  printf("args: %u %s\n", argc, argv[0]);
  return 0;                              
}                                        
EOF        
m68k-amigaos-gcc agc160.c -o agc160
vamos agc160 a bb ccc
> args: 4 
m68k-amigaos-gcc agc160.c -o agc160 -noixemul
vamos agc160 a bb ccc
> args: 4 
```

**Comment by skeetor** [comment]
Is there any other way to access the commandline or only via -noixemul?

 
 

Gesendet: Mittwoch, 25. März 2020 um 19:19 Uhr
Von: "bebbo" <notifications@github.com>
An: bebbo/amiga-gcc <amiga-gcc@noreply.github.com>
Cc: skeetor <sparhawk@gmx.at>, Author <author@noreply.github.com>
Betreff: Re: [bebbo/amiga-gcc] No args in main (#160)


 

use -noixemul

**Comment by bebbo** [comment]
it's working with newlib too

guess your version is bogus

**Comment by skeetor** [comment]
So I have to update gcc?

**Comment by skeetor** [comment]
m68k-amigaos-g++  -Wall -pedantic -mcrt=nix13 -fno-exceptions -fno-rtti -mregparm -fno-rtti -O3 -DNDEBUG  CMakeFiles/ImageDump.dir/main.cpp.o CMakeFiles/ImageDump.dir/pngFile.cpp.o  -o ../bin/ImageDump.exe -L/opt/amiga/utils/lib -lAmigaUtils -lAmigaGCCUtils

When I use -noixemul I get a duplicate symbol error, and when I remove -mcrt=nix13 then the binary wont start and gives me an error. Not sure what you mean with newlib.

**Comment by bebbo** [comment]
you must use only one of `-mcrt=nix13`, `-mcrt=nix20`, `-noixemul` or `-mcrt=clib2`.
and if you want to use `-mregparm` you should know where to add `__stdargs` and where not...
your main function is missing `__stdargs`

note that all extern function definitions without an explicit `__stdargs` are treated as functions with register parameters if `-mregparm` is used. Thus your provided libs must match: either compile these with the identical `-mregparm` option or ensure that the prototypes are attributed with `__stdargs`.

**Comment by skeetor** [comment]
Thanks for the explanation. I updated my gcc now, but the info about the __stdargs did it.
