### ISSUE TITLE
1.3 crash with -fbaserel -msmall-code

### ISSUE THREAD

**Issue by alexalkis** [bebbo/amiga-gcc#162]
[scrcol.zip](https://github.com/bebbo/amiga-gcc/files/4487583/scrcol.zip)

Something weird with 1.3.  If you compile without -fbaserel -msmall-code (scrcol.good in archive) it works, otherwise it crashes (scrcol.bad in the archive).  Gurus randomly 00000004, 00000003.

**Comment by bebbo** [comment]
if I omit debug.lib (-DNDEBUG) it runs too

**Comment by alexalkis** [comment]
Still not there.
With omitted debug.lib and NDEBUG defined.
Normal execution seems ok.  But if you run it ("run scrcol"), it crashes on second invocation.  Also first invocation doesn't switch all colors to black for some reason.

PS: The design is, first invocation keeps running in background until second invocation signals it

**Comment by bebbo** [comment]
it seems that with kick 1.3 bss gets not initialized with zeroes

**Comment by alexalkis** [comment]
Researching this a bit. Seems like SAS C, had the "clear bss" in the startup code. (as implied here, https://groups.google.com/d/msg/comp.sys.amiga.programmer/-35PzxA7yWQ/4WIx8Ba0YPUJ )

**Comment by bebbo** [comment]
the startup code also contains code like this, but the __bss_size is set to 0 by the linker script. I tried to fix that once, but that triggered other problems and complaints...
... now I use a new variable __bss_init_size and bss is cleared properly.

please test

**Comment by alexalkis** [comment]
Great.  It works with and without -DNDEBUG and -ldebug.lib.

Thanks!
