### ISSUE TITLE
Strange SDL RTG display

### ISSUE THREAD

**Issue by 8bit-Dude** [bebbo/amiga-gcc#165]
Hi again,
I was able to build the Aminet [SDL RTG](http://aminet.net/package/dev/lib/SDL_RTG) test with GCC. I made two versions: (1) Using GCC's own libSDL, (2) Using the included SDL_RTG_040 lib.

 Scenario (1) gives a very strange full screen result:
![20200503_121651](https://user-images.githubusercontent.com/6440924/80897977-2adcff00-8d39-11ea-8412-a16cbecb622c.jpg)

Scenario (2) gives the correct result (a window showing an image):
![20200503_121852](https://user-images.githubusercontent.com/6440924/80897980-2f091c80-8d39-11ea-9191-46e3b542fd71.jpg)

**Comment by bebbo** [comment]
what are your build commands?
Could you try different optimization levels?

**Comment by 8bit-Dude** [comment]
Thanks for the reply bebbo! 

I used -O3 -m68040.  Removing these flags still gives the same result.

**Comment by arczi84** [comment]
AmigaDev libSDL branch that is used in bebbo gcc has merged my test SAGA branch that  uses hacky Vampire direct draw method. It was not tested well therfore was not ready for merge.
I will revert that merge.

**Comment by arczi84** [comment]
Pushed. Let me know if it works.
https://github.com/AmigaPorts/libSDL12

**Comment by 8bit-Dude** [comment]
That did the trick! SDL is now working correctly (Building with -O3).
By the way, what is the min. CPU model for running this version of SDL?

**Comment by arczi84** [comment]
No, it only supports RTG.
It could be run even on 040 but speed mostly depends of game complexity and optimisation.
My mini slug port and zelda 3T was playable on 80Mhz 060.

**Comment by 8bit-Dude** [comment]
Ok, thanks a lot for these answers. It makes sense. 
If needed, I can always fall back on the AGA port available on Aminet.
