### ISSUE TITLE
Can't get hello world to run on fs-uae (500/500+)

### ISSUE THREAD

**Issue by kallaballa** [bebbo/amiga-gcc#168]
I successfully compiled the following program and tried to run it using fs-uae. I can't seem to get it to work, though I've tried multiple combinations of compiler-flags, kickstarter/workbench and amiga models.

```
#include <iostream>
int main() {
  std::cout << "hello" << std::endl;
  return 0;
}
```

I tried all permutations of the following setup:

Compiler flags: 
```
m68k-amigaos-g++ -s -Os -w -std=c++0x -pedantic -Wall -w -DDEBUG -o test test.cpp
m68k-amigaos-g++ -s -mcrt=nix1 -Os -w -std=c++0x -pedantic -Wall -w -DDEBUG -o test test.cpp
```

Kickstart/Workbench:
```
Kickstart v1.3 r34.5 (1987)(Commodore)(A500-A1000-A2000-CDTV)[!].rom + Workbench v1.3 rev 34.20 (1988)(Commodore)(A500-A2000)(Disk 1 of 2)(Workbench)[m].adf
Kickstart-v3.1-rev40.63-1993-Commodore-A500-A600-A2000.rom +  wb31-workbench.adf
```
fs-uae config with:
```
amiga_model=a500
amiga_model=a500+
```

First thing that caught the eye was that the generated binaries are huge:
with -mcrt=nix13: 864468 bytes (filename: test13)
without -mcrt=nix13: 990036 bytes (filename: test)

... which probably is the reason for the out of memory errors i get with the 500(+) default configuration.

So i added the following to the fs-uae config:
```
chip_memory = 8192
```

Now:
- when i run "test" on the kickstart 1.3 setup, the program returns without any output.
- when i run "test13" on the kickstart 1.3 setup, i get:
```
local.library failed to load
mathieeesingbas.library failed to load
```
- when i run "test" on the kickstart 3.1 setup i get error code "8000 0003"
- when i run "test13" on the kickstart 3.1 setup i get error code "8000 0003"

what am i doing wrong?

**Comment by TheFakeMontyOnTheRun** [comment]
Allow me to suggest you to try with pure C first and then slowly transition to C++, so you can better see what features will and will not work as you progress.
I would also suggest you to try AGA configurations, as means of troubleshooting.

If anything, I would steer clear from iostream on *any* platform :P

**Comment by kallaballa** [comment]
You where right that the problem was <iostream>.
thx!

**Comment by kallaballa** [comment]
Oh i forgot... there was something else necessary to get it to work. i needed to add the following flags: -Wa,-march=68000 -Wa,-mcpu=68000 -march=68000 -mtune=68000 -msoft-float -mcpu=680000
