### ISSUE TITLE
Can't get SDL to work on fs-uae

### ISSUE THREAD

**Issue by kallaballa** [bebbo/amiga-gcc#169]
linking with SDL without using any functions works, but the mere mention of a SDL function creates a disfunctional binary. i say disfunctional, because the program seems to terminate before SDL_Init is even called.

```
#include <cstdio>
#include <SDL/SDL.h>

int main() {
  printf("start\n");
  if (SDL_Init(SDL_INIT_VIDEO) == -1) {
    printf("fail\n");
  } else {
    printf("success\n");
  }
}
```

It doesn't print anything. Without the call to SDL_Init the program prints correctly.

Build with:
`m68k-amigaos-g++ -std=c++0x -pedantic -Wall -fno-rtti -fno-exceptions -mcrt=nix13  -Wa,-march=68000 -Wa,-mcpu=68000 -march=68000 -mtune=68000 -msoft-float -mcpu=68000 -fbbb=+ -Os -w -c -o sdltest.o sdltest.cpp -lm -lSDL -ldebug`

I suspect it might have something to do with my fs-uae configuration which is as follows: 
```
[fs-uae]
amiga_model = A500/512K
base_dir = /home/user/Documents/FS-UAE
cdroms_dir = /home/user/Documents/FS-UAE/CD-ROMs
chip_memory = 2048
config_path = /home/user/Documents/FS-UAE/Configurations/dive.fs-uae
configurations_dir = /home/user/Documents/FS-UAE/Configurations
controllers_dir = /home/user/Documents/FS-UAE/Controllers
end_config = 1
expect_version = 3.0.3
floppies_dir = /tmp/fs-uae-s7erte6a
floppy_image_0 = Save Disk.adf
graphics_card = uaegfx
hard_drive_0 = /home/user/amiga/dive.hdf
hard_drives_dir = /home/user/Documents/FS-UAE/Hard Drives
joystick_port_0 = Mouse
joystick_port_0_mode = mouse
joystick_port_1 = Keyboard
joystick_port_1_mode = joystick
joystick_port_2 = none
joystick_port_2_mode = none
joystick_port_3 = none
joystick_port_3_mode = none
kickstart_file = /tmp/fs-uae-s7erte6a/Kickstart v1.3 r34.5 (1987)(Commodore)(A500-A1000-A2000-CDTV)[!].rom
kickstarts_dir = /home/user/Documents/FS-UAE/Kickstarts
maximized = 1
quick_settings = 0
save_states_dir = /home/user/Documents/FS-UAE/Save States
screenshots_output_prefix = dive
state_dir = /home/user/Documents/FS-UAE/Save States/dive
themes_dir = /home/user/Documents/FS-UAE/Themes
```

Please not the i added the uaegfx graphics card which supposedly is a P96 because [here](http://aminet.net/package/dev/misc/SDL-Amiga) i read that it is compatible.

what am i doing wrong?

**Comment by bebbo** [comment]
I guess SDL does not work with kickstart 1.3.

**Comment by kallaballa** [comment]
i have the same result with "Kickstart-v3.1-rev40.63-1993-Commodore-A500-A600-A2000.rom"

**Comment by bebbo** [comment]
no idea - I'm using WinUAE with UAE Zorro III graphics card - and you code yield "success"

**Comment by bebbo** [comment]
=> get your workbench up and running with your desired graphics card first

**Comment by kallaballa** [comment]
could you please post your full WinUAE configuration?

**Comment by kallaballa** [comment]
> => get your workbench up and running with your desired graphics card first

i got it running with the uaegfx and uae zorro II but i don't get the desired result. are you sure you are using an a500 model?

**Comment by bebbo** [comment]
A500 will work but you need at least 68020 - or compile your own libSDL for 68000

**Comment by SamuraiCrow** [comment]
P96 requires a 68020 at least.  Forget the 68000 configuration.

**Comment by kallaballa** [comment]
I'm now using ClassicWB_P96_v28 with an A4000 configuration and my graphics card is definitely configured and working. but i still can't get the example working. using snoopdos i found out the test program unsuccessfully tries to open timer.device. any suggestions?

My fs-uae config:

```
[fs-uae]
amiga_model = A4000
accelerator_memory = 4096
base_dir = /home/user/Documents/FS-UAE
cdroms_dir = /home/user/Documents/FS-UAE/CD-ROMs
chip_memory = 2048
config_path = /home/user/Documents/FS-UAE/Configurations/dive.fs-uae
configurations_dir = /home/user/Documents/FS-UAE/Configurations
controllers_dir = /home/user/Documents/FS-UAE/Controllers
end_config = 1
expect_version = 3.0.3
floppies_dir = /home/user/amiga
#floppy_drive_0 = wb31-workbench.adf
#floppy_image_0 = wb31-workbench.adf
floppy_image_0 = Save Disk.adf
graphics_card = uaegfx-z3
graphics_memory = 32768
hard_drive_0 = /home/user/amiga/dive.hdf
hard_drives_dir = /home/user/Documents/FS-UAE/Hard Drives
hard_drive_0_priority = 6
joystick_port_0 = Mouse
joystick_port_0_mode = mouse
joystick_port_1 = Keyboard
joystick_port_1_mode = joystick
joystick_port_2 = none
joystick_port_2_mode = none
joystick_port_3 = none
joystick_port_3_mode = none
kickstart_file = /home/user/amiga/Kickstart_v3.1_r40.70_1994_Commodore_A4000.rom
kickstarts_dir = /home/user/Documents/FS-UAE/Kickstarts
maximized = 1
motherboard_ram = 4096
quick_settings = 0
save_states_dir = /home/user/Documents/FS-UAE/Save States
screenshots_output_prefix = dive
sound_card = toccata
state_dir = /home/user/Documents/FS-UAE/Save States/dive
themes_dir = /home/user/Documents/FS-UAE/Themes
zorro_iii_memory = 32768
```

**Comment by kallaballa** [comment]
I also tried it with winuae. didn't make any difference. how do i get a timer.device?

**Comment by kallaballa** [comment]
I think the problem is that libnix tries to open the timer device using `OpenLibrary` instead of `OpenDevice`

https://github.com/bebbo/libnix/blob/b70d5808975b28fe2db9c4ee6ced22734c81f504/sources/stubs/libbases/timer.c#L31

where is the source for this generated code?

**Comment by bebbo** [comment]
That `OpenLibrary` is ok. The program runs as expected. 
[agc169.zip](https://github.com/bebbo/amiga-gcc/files/4622130/agc169.zip)

What stack size are you using?

**Comment by kallaballa** [comment]
The default. could you please post your compiler flags?

**Comment by kallaballa** [comment]
btw. I'm using "m68k-amigaos-gcc (GCC) 6.5.0b 190523234138"

**Comment by bebbo** [comment]
that's not a compiler flag, you need to run `stack 100000` in your shell. Best put it into `S:Shell-Startup`

**Comment by bebbo** [comment]
> 
> 
> btw. I'm using "m68k-amigaos-gcc (GCC) 6.5.0b 190523234138"

No idea how good that version was, recent is
```
gcc version 6.5.0b 191023121710 (GCC)
```

**Comment by kallaballa** [comment]
> > btw. I'm using "m68k-amigaos-gcc (GCC) 6.5.0b 190523234138"
> 
> No idea how good that version was, recent is
> 
> ```
> gcc version 6.5.0b 191023121710 (GCC)
> ```

I'm using the latest release because i have problems building head

**Comment by kallaballa** [comment]
> that's not a compiler flag, you need to run `stack 100000` in your shell. Best put it into `S:Shell-Startup`

Yeah, i understand. But i still would like to now how you build the executable exactly because the one you built works just fine without editing the configuration.

**Comment by bebbo** [comment]
> 
> 
> > > btw. I'm using "m68k-amigaos-gcc (GCC) 6.5.0b 190523234138"
> > 
> > 
> > No idea how good that version was, recent is
> > ```
> > gcc version 6.5.0b 191023121710 (GCC)
> > ```
> 
> I'm using the latest release because i have problems building head

what release???
and what problems with building?

=> your version is bogus.

**Comment by kallaballa** [comment]
> > 
> > I'm using the latest release because i have problems building head
> 
> what release???
https://github.com/bebbo/amiga-gcc/releases/tag/latest-20190526123542

> and what problems with building?
I'll try again and report

> => your version is bogus.
Well as you can see above it is the latest binary release you personally did

**Comment by kallaballa** [comment]
Can i please still have your compiler command line?

**Comment by bebbo** [comment]
> 
> 
> Can i please still have your compiler command line?

your commandline from above

**Comment by bebbo** [comment]
> 
> 
> > > I'm using the latest release because i have problems building head
> > 
> > 
> > what release???
> 
> https://github.com/bebbo/amiga-gcc/releases/tag/latest-20190526123542
> 
> > and what problems with building?
> 
> I'll try again and report
> 
> > => your version is bogus.
> 
> Well as you can see above it is the latest binary release you personally did

ah there^^

try this one instead: https://franke.ms/download/amiga-gcc.tgz

**Comment by kallaballa** [comment]
> try this one instead: https://franke.ms/download/amiga-gcc.tgz

This one gives me tons of errors. The iostream errors i can fix, but the whole _GLIBCXX_EXTERN_TEMPLATE and _GLIBCXX_END_NAMESPACE_VERSION stuff looks bogus.

https://gist.github.com/kallaballa/85afa628d3759747116ddbbfac577976

**Comment by kallaballa** [comment]
but the sdltest does work!

**Comment by bebbo** [comment]
sorry - I have no idea what you are doing.

I pass.

**Comment by SamuraiCrow** [comment]
If it compiles an executable but issues warnings, it just means standard style has been violated.  Warnings!=Errors.

**Comment by bebbo** [comment]
There are no error messages if everything is installed properly. Your example compiles and runs. No errors, no warnings, nada.

**Comment by kallaballa** [comment]
> There are no error messages if everything is installed properly. Your example compiles and runs. No errors, no warnings, nada.

Sorry for the misunderstanding. Yeah it does! I just get the errors when compiling something more complex which compiled fine with my previous setup. I will try to isolate the problem and if i can't figure it out, I'll make a new issue. Also i will retry to build head.

The solution to compiling a working binary from the given source code was to use: https://franke.ms/download/amiga-gcc.tgz instead of https://github.com/bebbo/amiga-gcc/releases/tag/latest-20190526123542

**Comment by kallaballa** [comment]
I had problems with a more complete SDL12/c++ example (https://github.com/kallaballa/FractalDive) using the above toolchain. All problems vanished when i managed to built HEAD on a Debian 10. The reason i didn't built it in the first place was that i wasn't able to build on openSUSE Tumbleweed (I'll create a separate issue).

Anyway, for anyone who wants a quick solution i created an unofficial release with linux binaries: https://github.com/kallaballa/amiga-gcc/releases/tag/latest-20200516174914
