### ISSUE TITLE
m68k-amigaos-ar fails: "file format not recognized"

### ISSUE THREAD

**Issue by softwarefailure** [bebbo/amiga-gcc#17]
When I do

    m68k-amigaos-ar rs libtest.a obj1.o obj2.o

I get the following error:

    libtest.a: File format not recognized

And the file `libtest.a` is 0 bytes then. It's weird. Why does it even look at `libtest.a`? It should create `libtest.a`, not archive it.

**Comment by bebbo** [comment]
please attach the related files

**Comment by softwarefailure** [comment]
Here you go.
[test.zip](https://github.com/bebbo/amiga-gcc/files/1859716/test.zip)

**Comment by bebbo** [comment]
moved to https://github.com/bebbo/amigaos-binutils-2.14/issues/1
