### ISSUE TITLE
[info] Possible reason for Cygwin slow compilation is /tmp size

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [bebbo/amiga-gcc#171]
This is just to tell you that a possible reason for Cygwin slow compilation is /tmp size.
I am not sure, though.
If you start with a big /tmp directory, every gets very slow if your build uses it a lot or if it makes it grow a lot.

**Comment by bebbo** [comment]
The reasons for slow compilation on Windows:

1. Windows
2. Antivirusscanner
3. Loading tons of DLLs per compile

What should be fixed here?

**Comment by Fabrizio-Caruso** [comment]
Sorry, this is a wild guess based on experience with Cygwin and other cross-compilers.
So, my guess is not based on solid facts but on a different problem.
If your installation tool-chain uses /tmp and /tmp has lots of files, then it will be incredible slow.

I use Cygwin to build my universal retro-framework (https://github.com/Fabrizio-Caruso/CROSS-CHASE) with more than a dozen cross-compilers. In my use-cases Cygwin is as fast as L:inux, unless /tmp is full and the cross-compiler X uses it.

Sorry if this is not applicable to your tool-chain.

**Comment by Fabrizio-Caruso** [comment]
I am closing this issue just to give you a possible hint.
Sorry for the inconvenience.
Thanks a lot for your project!
