### ISSUE TITLE
Optimizer with -fbaserel

### ISSUE THREAD

**Issue by alexalkis** [bebbo/amiga-gcc#177]
I was fooling around with compiler-explorer and I've noticed this

https://franke.ms/cex/z/uuzJsc

If you add -fbaserel it then reloads the a6 with _DOSBase for the second DOS call.

**Comment by bebbo** [comment]
can't fix, since
```
  move.l _DOSBase, a6
```
is a read from a non volatile memory location, keeping the value is allowed.

vs
```
  move.l _DOSBase(a4), a6
```
is a indirect read from a non restricted variable, keeping the value is not allowed.

**Comment by alexalkis** [comment]
Hmm, interesting.

As a workarround you can do:
    struct DosLibrary *myDOSBase = DOSBase;
    #define DOSBase myDOSBase

https://franke.ms/cex/z/Qb72N6
