### ISSUE TITLE
Building code with the 'chip' keyword fails

### ISSUE THREAD

**Issue by blitmaps** [bebbo/amiga-gcc#186]
Firstly, amazing work guys, this repo is sweet!

I am learning the A1200 hardware, and I have successfully built some demo programs using this toolchain.

When I try and build any example code with the 'chip' attribute, I get an error.  

For example, building the system-zoetrope-amiga-demo, give me this:

`/home/<me>/amiga-gcc/system-zoetrope-amiga-demo/src/buddha_bitmaps.c:14:12: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'buddhaData'
 UWORD chip buddhaData[192] =
`
Any help would be appreciated, cheers!.

**Comment by bebbo** [comment]
it's `__chip`

**Comment by blitmaps** [comment]
That's fab, thanks for the help!
