### ISSUE TITLE
DBcc is no longer emitted

### ISSUE THREAD

**Issue by nonarkitten** [bebbo/amiga-gcc#187]
https://franke.ms/cex/z/gg_8Ej

gcc-10b shows the sequence subq, cmp, jne
gcc-6.5.0b and 2.95.3 shows the dbra

**Comment by bebbo** [comment]
Thanks for reporting, but gcc-10b is not yet finished^^

Please use 6.5.0b.

**Comment by bebbo** [comment]
fixed in 10.2.1b: http://franke.ms/cex/z/TK1jv7
