### ISSUE TITLE
newlib fails to build

### ISSUE THREAD

**Issue by BSzili** [bebbo/amiga-gcc#191]
After updating newlib now fails to build. There appears to be some kind if clash between the NDK and C library timeval struct.

>m68k-amigaos-g++  -fbaserel -DPACKAGE_NAME=\"newlib\" -DPACKAGE_TARNAME=\"newlib\" -DPACKAGE_VERSION=\"3.0.0\" -DPACKAGE_STRING=\"newlib\ 3.0.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -I. -I/home/BSzili/amiga-gcc/projects/newlib-cygwin/newlib/libc/sys/amigaos -DCOMPACT_CTYPE -DSIGNAL_PROVIDED -fno-builtin      -O2 -fomit-frame-pointer -fno-exceptions -fno-rtti -c -o malloc.o /home/BSzili/amiga-gcc/projects/newlib-cygwin/newlib/libc/sys/amigaos/malloc.cpp
 /home/BSzili/amiga-gcc/projects/newlib-cygwin/newlib/libc/sys/amigaos/malloc.cpp
In file included from /opt/amiga/m68k-amigaos/ndk-include/dos/dosextens.h:26:0,
                 from /opt/amiga/m68k-amigaos/ndk-include/clib/dos_protos.h:21,
                 from /opt/amiga/m68k-amigaos/ndk-include/proto/dos.h:6,
                 from /home/BSzili/amiga-gcc/projects/newlib-cygwin/newlib/libc/sys/amigaos/malloc.cpp:8:
/opt/amiga/m68k-amigaos/ndk-include/devices/timer.h:30:8: error: redefinition of 'struct timeval'
 struct timeval {
        ^~~~~~~
In file included from /opt/amiga/m68k-amigaos/sys-include/sys/select.h:15:0,
                 from /opt/amiga/m68k-amigaos/sys-include/sys/types.h:68,
                 from /opt/amiga/m68k-amigaos/sys-include/stdio.h:61,
                 from /home/BSzili/amiga-gcc/projects/newlib-cygwin/newlib/libc/sys/amigaos/malloc.cpp:4:
/opt/amiga/m68k-amigaos/sys-include/sys/_timeval.h:52:8: error: previous definition of 'struct timeval'
 struct timeval {
        ^~~~~~~

I also tried it with a clean checkout of newlib, but it didn't help.

**Comment by bebbo** [comment]
well, travis states the build is ok: https://travis-ci.org/github/bebbo/amiga-gcc

**Comment by bebbo** [comment]
buest guess: You are missing a `git pull`

**Comment by BSzili** [comment]
Indeed, my timer.h.diff was out of date. Sorry for the false alarm, it built now.
