### ISSUE TITLE
Missing this_thread

### ISSUE THREAD

**Issue by BSzili** [bebbo/amiga-gcc#192]
I'm trying to sleep the current thread the C++11 way, but it looks like this_thread is not implemented. I made a minimal example the fails to compile:
```
#include <chrono>
#include <thread>

int main()
{
	std::this_thread::sleep_for(std::chrono::duration<double>(2));
	return 0;
}
```
When bulding it I get this error:
> $ m68k-amigaos-g++ -noixemul -std=c++11 -o sleepfor sleepfor.cpp
sleepfor.cpp: In function 'int main()':
sleepfor.cpp:6:7: error: 'std::this_thread' has not been declared
  std::this_thread::sleep_for(std::chrono::duration<double>(2));
       ^~~~~~~~~~~

I tried to hack around by defining `-D_GLIBCXX_HAS_GTHREADS -D_GLIBCXX_USE_C99_STDINT_TR1`, but that only made things worse. Is this::thread not supported currently?

**Comment by bebbo** [comment]
c++ threads aren't provided for now. Feel free to provide a patch.

**Comment by BSzili** [comment]
I tried adding --enable-threads=posix to the GCC configure arguments, which allowed building libgcc with gthread support. Unfortunately when I put anything C++ thread related into a program, it will hang before entering the main function. I'm not sure what the issue is, maybe pthreads is just not up to snuff.

**Comment by bebbo** [comment]
I once tried to enable threading... see https://github.com/bebbo/amiga-gcc/issues/109 there is more to do than only provide a valid libpthread...

**Comment by BSzili** [comment]
I see, so the main issue is that gthreads requires compiler-level TLS support.

**Comment by bebbo** [comment]
it hangs here, eh_globals.cc:
```
abi::__cxa_eh_globals*
  get_global() _GLIBCXX_NOTHROW
  {
    static __thread abi::__cxa_eh_globals global;
    return &global;
  }
```

**Comment by bebbo** [comment]
note: using threads or other std::stuff means also you should not use ` -fno-exceptions -fno-rtti`

**Comment by bebbo** [comment]
[test.zip](https://github.com/bebbo/amiga-gcc/files/5404017/test.zip)

your test is now working (with the mandatory changes to the amiga-gcc Makefile and libstdc++/configure)

**Comment by BSzili** [comment]
Thanks, I'll give it a test over the weekend!

**Comment by bebbo** [comment]
There is only one `pthread.h` - maybe you haven't cleand your prefix includes for a while.
![msys](https://user-images.githubusercontent.com/16560863/97741971-e82b9200-1ae3-11eb-8244-79b0c7154d46.png)
