### ISSUE TITLE
error: 'std::pair<_T1, _T2>::second' has incomplete type

### ISSUE THREAD

**Issue by arczi84** [bebbo/amiga-gcc#194]
I get this error when compiling BattleForWesnoth 1.2:

```
D:/amiga-gcc2/lib/gcc/m68k-amigaos/6.5.0b/include/c++/bits/stl_pair.h: In instantiation of 'struct std::pair<gamemap::location, unit>':
unit_map.hpp:52:30:   required from here
D:/amiga-gcc2/lib/gcc/m68k-amigaos/6.5.0b/include/c++/bits/stl_pair.h:211:11: error: 'std::pair<_T1, _T2>::second' has incomplete type
       _T2 second;                /// @c second is a copy of the second object
           ^~~~~~
```
I have not changed anything in the source.

**Comment by bebbo** [comment]
that's not enough info, maybe there is only a forward decl for the second type.

**Comment by arczi84** [comment]
Full error:
`m68k-amigaos-g++ -std=c++14 -w -fbbb=- -fomit-frame-pointer -m68040 -ffast-math -O2  -mhard-float -s -noixemul -DHAVE_CONFIG_H -I. -I..   -I/d/amiga-gcc2/include -ID:/dev/share/netsurf/include/freetype2 -ID:/dev/share/netsurf/include/libpng16 -ID:/dev/share/netsurf/include -I ./sdl_ttf -I../intl -I../intl -I/d/amiga-gcc2/include -I/d/amiga-gcc2/include -I/d/amiga-gcc2/m68k-amigaos/include/ -I/d/amiga-gcc2/m68k-amigaos/sys-include -I/d/amiga-gcc2/include/sdl -I/d/amiga-gcc2/sys-include  -DWESNOTH_PATH=\"/d/amiga-gcc2/share/wesnoth\" -DLOCALEDIR=\"translations\" -DHAS_RELATIVE_LOCALEDIR=1 -DFIFODIR=\"/d/amiga-gcc2/var/run/wesnothd\"  -O2 -W -Wall -ansi     -MT dialogs.o -MD -MP -MF $depbase.Tpo -c -o dialogs.o dialogs.cpp &&\
mv -f $depbase.Tpo $depbase.Po
In file included from D:/amiga-gcc2/lib/gcc/m68k-amigaos/6.5.0b/include/c++/bits/stl_algobase.h:64:0,
                 from D:/amiga-gcc2/lib/gcc/m68k-amigaos/6.5.0b/include/c++/bits/char_traits.h:39,
                 from D:/amiga-gcc2/lib/gcc/m68k-amigaos/6.5.0b/include/c++/string:40,
                 from generic_event.hpp:18,
                 from ai_interface.hpp:19,
                 from ai_dfool.hpp:6,
                 from ai_dfool.cpp:2:
D:/amiga-gcc2/lib/gcc/m68k-amigaos/6.5.0b/include/c++/bits/stl_pair.h: In instantiation of 'struct std::pair<gamemap::location, unit>':
unit_map.hpp:52:30:   required from here
D:/amiga-gcc2/lib/gcc/m68k-amigaos/6.5.0b/include/c++/bits/stl_pair.h:211:11: error: 'std::pair<_T1, _T2>::second' has incomplete type
       _T2 second;                /// @c second is a copy of the second object
`

https://github.com/wesnoth/wesnoth/blob/1.2/src/ai_dfool.hpp

**Comment by bebbo** [comment]
please compile it with `-E` instead of `-c` and provide the output

**Comment by arczi84** [comment]
https://hatebin.com/jeyartqqhu

**Comment by arczi84** [comment]
https://hatebin.com/hlygeafquq

**Comment by bebbo** [comment]
sorry - I was not precise enough with `output`: I'd like to get the generated file with `-E` instead of `-c`

**Comment by arczi84** [comment]
https://hatebin.com/ngeegheqgf

**Comment by bebbo** [comment]
better - but is incomplete at line 2043...
maybe zip it and attach here?

**Comment by arczi84** [comment]
[ai_dfool.zip](https://github.com/bebbo/amiga-gcc/files/5604560/ai_dfool.zip)

**Comment by bebbo** [comment]
thanks - at least it's not a gcc 6.5.0 error, gcc-9.3 reports the same error.

**Comment by bebbo** [comment]
the class unit must be fully defined before using it. try moving the `#include "unit_map.hpp"` behind the class definition of `class unit`...
```
--- old/unit.hpp    2020-11-26 10:24:05.154791300 +0100
+++ new/unit.hpp   2020-11-26 19:56:53.386478900 +0100
@@ -19,7 +19,6 @@
 #include "team.hpp"
 #include "unit_types.hpp"
 #include "image.hpp"
-#include "unit_map.hpp"
 
 class unit;
 class display;
@@ -374,6 +373,9 @@
 
 };
 
+#include "unit_map.hpp"
+
+
 //object which temporarily resets a unit's movement
 struct unit_movement_resetter
 {
```

**Comment by arczi84** [comment]
Yes, that's it!

Now when I fire exe, gcc6 throws bad_lexical_cast error when gcc4 not..
