### ISSUE TITLE
errno is not thread-safe

### ISSUE THREAD

**Issue by Midar** [bebbo/amiga-gcc#195]
It seems there's a symbol errno symbol, instead of it being a define to get thread-local storage

**Comment by bebbo** [comment]
```
/opt/amiga/bin/m68k-amigaos-gcc -v
Using built-in specs.
COLLECT_GCC=/opt/amiga/bin/m68k-amigaos-gcc
COLLECT_LTO_WRAPPER=/opt/amiga/libexec/gcc/m68k-amigaos/6.5.0b/lto-wrapper
Target: m68k-amigaos
Configured with: /home/bebbo/amiga/amiga-gcc/projects/gcc/configure --prefix=/opt/amiga --target=m68k-amigaos --enable-languages=c,c++,objc --enable-version-specific-runtime-libs --disable-libssp --disable-nls --with-headers=/home/bebbo/amiga/amiga-gcc/projects/newlib-cygwin/newlib/libc/sys/amigaos/include/ --disable-shared --with-stage1-ldflags='-dynamic-libgcc -dynamic-libstdc++' --with-boot-ldflags='-dynamic-libgcc -dynamic-libstdc++'
Thread model: single
```

=> last line says: **single**
the headers match.

**Comment by Midar** [comment]
This makes it impossible to use threads at all, even when not using GCC threads and being careful about only using functions that are reentrant. I think it makes sense to have thread model single, but have things still thread-*safe*.

**Comment by bebbo** [comment]
This is the way.

**Comment by Midar** [comment]
Can we at least make errno task-specific? All the other things that are not thread-safe can be worked around with using semaphores, but this one can't. It's fairly easy to do and does not hurt, but allows threaded code.

**Comment by bebbo** [comment]
The work in progress is to support `make THREADS=posix` which result in gcc supporting threads, tls and so on. I guess errno will be a macro then...

**Comment by bebbo** [comment]
With the recent changes in libnix, errno is now a `__thread` variable, if the toolchain was build with `make THREADS=posix`.
Also the FILE based stdio functions are thread safe.

**Comment by bebbo** [comment]
since the provide libpthread starts to work - simple exeamples do work^^ - I'm closing this.
