### ISSUE TITLE
Please update vasm to latest version

### ISSUE THREAD

**Issue by mheyer32** [bebbo/amiga-gcc#197]
Phx added some features to VASM and VLINK and made a bugfix that allows Breathless to compile/assemble

https://github.com/mheyer32/Breathless

**Comment by bebbo** [comment]
uhm - vasm is not my repo -> please request it here: https://github.com/Leffmann/vasm

**Comment by mheyer32** [comment]
I left an issue there: https://github.com/Leffmann/vasm/issues/1

But got zero response. Is this still being maintained?

**Comment by bebbo** [comment]
no idea - I don't use vasm...

**Comment by mheyer32** [comment]
Could the toolchain instead pull from the vasm website instead?
I find it quite convenient that vasm is included - I use it  lot!

**Comment by bebbo** [comment]
you could clone that repo, update it and I'll switch to your repo.

**Comment by mheyer32** [comment]
Done: https://github.com/mheyer32/vasm

But frankly, I think instead of pulling this repo from github, you could as well pull it from hasbenbraten.de directly.

**Comment by mheyer32** [comment]
Thanks!
