### ISSUE TITLE
Different conditions in syslib.h

### ISSUE THREAD

**Issue by OliverUrbann** [bebbo/amiga-gcc#198]
In clib2/stdlib.h line 440:
```
#if defined(__GNUC__) || (defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L))
```

and in sys-include/stdlib.h, which is included in clib2/stdlib.h, line 48:

```
#if __ISO_C_VISIBLE >= 1999
typedef struct
{
  long long int quot; /* quotient */
  long long int rem; /* remainder */
} lldiv_t;
#endif
```

Using gcc with the flag -ansi leads then to an undefined lldiv_t in clib2/include. I've changed the condition in clib2/stdlib.h to be equal and it works so far.

**Comment by bebbo** [comment]
fixed
