### ISSUE TITLE
undefined reference to cexpf, while cexpf not used anywhere in source

### ISSUE THREAD

**Issue by MBeijer** [bebbo/amiga-gcc#20]
Why would the compiler turn this expression into cexpf?

```
projectilelib.o(.text+0x50e8): In function `projectile::move()':
projectilelib.cpp:772: undefined reference to `cexpf'
```
Row 772 in projectilelib.cpp:
`float rad_angle = (angle * M_PI)/180.00;`

Angle is a float, so is M_PI.

**Comment by bebbo** [comment]
please attach a preprocessed file!

**Comment by MBeijer** [comment]
https://www.eevul.net/downloads/projectilelib.o

**Comment by MBeijer** [comment]
I've since updated the source, it's now referring to line 794 (same code though)

**Comment by MBeijer** [comment]
changing the float to a double removes the cexpf reference, and I narrowed it down to have something to do with these lines:
```
        position.x = _speed_x*cos(rad_angle) + position0.x;
        position.y = _speed_x*sin(rad_angle) + position0.y;
```

float + cos / sin = complex or something like that.

**Comment by bebbo** [comment]
the call to `cexpf` is ok, since the code contains:
```
        position.x = _speed_x*cos(rad_angle) + position0.x;
        position.y = _speed_x*sin(rad_angle) + position0.y;
```

If `sin` and `cos` of the same angle is calculated, the `cexpf` function calculates both in one call.

**Comment by MBeijer** [comment]
But still, cexpf is not defined anywhere in libm etc, so it poses a dilemma.

**Comment by bebbo** [comment]
cexpf is one of the complex functions.

**Comment by MBeijer** [comment]
Yeah, but the complex functions seem to be missing from the toolchain altogether, hence the undefined reference. I solved it for now by changing over to double.

**Comment by bebbo** [comment]
I know, and you knew it too: https://github.com/bebbo/amigaos-cross-toolchain/issues/68

> I'll grab a fork of libnix and apply changes to it. Will do a pull request when I'm done. :)

**Comment by bebbo** [comment]
```
extern float cosf(float);
extern float sinf(float);
extern float expf(float);

#define complex _Complex

#define REALPART(z) (__real__(z))
#define IMAGPART(z) (__imag__(z))
#define COMPLEX_ASSIGN(z_, r_, i_) {__real__(z_) = (r_); __imag__(z_) = (i_);}


/* exp(z) = exp(a)*(cos(b) + i sin(b))  */
#if !defined(HAVE_CEXPF)
#define HAVE_CEXPF 1
float complex cexpf (float complex z);

float complex
cexpf (float complex z)
{
  float a, b;
  float complex v;

  a = REALPART (z);
  b = IMAGPART (z);
  COMPLEX_ASSIGN (v, cosf (b), sinf (b));
  return expf (a) * v;
}
#endif
```

**Comment by bebbo** [comment]
the  sad part: with this code there is no benefit from using cexpf...

**Comment by bebbo** [comment]
added libcomplex.a => use -lcomplex to use those functions

**Comment by bebbo** [comment]
removed libcomplex.a - adding all complex stuff to libm.a

**Comment by th-otto** [comment]
Seems to be already solved. but i just stumbled upon this.

I once had a similar problem when porting the Atari toolchain. As with the amiga library, the c-library of atari is missing the complex functions. The solution was to add an

+#undef TARGET_LIBC_HAS_FUNCTION
+#define TARGET_LIBC_HAS_FUNCTION no_c99_libc_has_function

in the target configuration header (gcc/config/m68k/mint.h in my case). For some reason, the optimizer turns a sequence of sin/cos calls into a call to cexp(), and at a later point changes that to a call to sincos(). But if you don't set the above symbol, the library call to cexp() will remain, resulting in an unresolved external.
