### ISSUE TITLE
setup: `make gcc` step fails when homebrew is not installed in /usr/local

### ISSUE THREAD

**Issue by acf** [bebbo/amiga-gcc#203]
Hi Stefan,

I've run through your instructions successfully on both my intel Macs using homebrew but I just tried on an M1 Mac and hit an issue configuring/building gcc.  It complains about gmp.h not being found.

I have checked homebrew and on both Intel and M1 it sports version 6.2.1 of GMP installed with no caveats or issues.

After hitting the wall on `gmake all`and trying some googling I saw some suggestions for running `contrib/download_prerequisites` which I tried.  Got past the `configure gcc` step and into `make gcc`  at which point I hit a similar error "configuring in mpfr", which also complained about gmp.

I'm afraid I'm a bit new to this kind of GNU wizardry so may not be much help in answering further questions, but happy to try or send you the logs I have.

As I say, homebrew seemed happy on both platforms and all worked fine on my intel Macs.

**Comment by bebbo** [comment]
unless someone donates me such a platform, I can't support it. Maybe someone else steps in!?

**Comment by acf** [comment]
Understood.  Sorry I'm not able to be much help here, I'm a bit sketchy on how configure works at all 😳   

If someone can explain to me how the process "decides" that there's no valid GMP I could probably dig further to see what "test" is failing on this system.  Is it as simple as checking for the presence of a header ?  Or is there some version number check somehow ? 

In other words, what specially leads GCC to decide there's no valid GMP ?

**Comment by bebbo** [comment]
> In other words, what specially leads GCC to decide there's no valid GMP ?

* the headers must be present
* some code is compiled and must no yield an error

look at the end of config.log in the gcc's build folder.

**Comment by acf** [comment]
Ok so, the output from `configure\ gcc.log` looks good for `gmp.h`, but mentions `ISL`.

<img width="650" alt="Screenshot 2021-02-11 at 12 59 18" src="https://user-images.githubusercontent.com/218/107639807-4cc0c600-6c69-11eb-9021-53bae980d350.png">

in `make\ gcc.log` however it looks like the error is actually in "configure ISL" ?

<img width="599" alt="Screenshot 2021-02-11 at 13 00 06" src="https://user-images.githubusercontent.com/218/107639925-77ab1a00-6c69-11eb-810e-150b3fbaefe8.png">

Apologies again for being frustratingly bad at this, but again happy to help in any way I can (short of mailing you an M1 Mac :-)

**Comment by bebbo** [comment]
maybe you can install isl to use that prebuilt isl version?

**Comment by acf** [comment]
is that something I would do through homebrew ?

**Comment by bebbo** [comment]
yes, sir.

**Comment by acf** [comment]
<img width="465" alt="Screenshot 2021-02-11 at 13 45 01" src="https://user-images.githubusercontent.com/218/107644467-6107c180-6c6f-11eb-9a77-c0bd4965b7be.png">

**Comment by acf** [comment]
So many moving parts. I take my hat off to you that it works so well on Intel :-)

**Comment by bebbo** [comment]
uhm - out of ideas - maybe it works, if you also build mpfr, mfc and gmp yourself?

use contrib/download_prerequisites  to do that

**Comment by acf** [comment]
Yup, tried that too :-)

**Comment by acf** [comment]
Guess we'll leave it for someone who knows what they are doing and has an M1

**Comment by bebbo** [comment]
that `and` is the problem^^

**Comment by acf** [comment]
yup.  You have the brains and I have the hardware.  I guess they'll get more common over time.  

Oh.

One thing that does suddenly occur to me actually is that my intel MBP is on 10.15 and my M1 is 11.2 🤦   So maybe its BigSur related rather than M1 related. 💡

**Comment by acf** [comment]
ok last investigation.

I went into `projects/gcc` and it has a `gmp-4.3.2` subdir so I tried `./configure --with-gmp = ./gmp-4.3.2` which failed because (when I looked) there's no .h file there.

There is a `.h.in` so on a whim I tried to do a `./configure` inside that `gmp-4.3.2` folder and got this:

`configure: error: Oops, mp_limb_t is 64 bits, but the assembler code in this configuration expects 32 bits.`

So.... the gmp inside gcc can't be configured, which is why gcc is complaining. (I think).  I've gone as far as I can, I think so will leave it alone in case anyone can figure this out :-)

**Comment by acf** [comment]
Guess I can't actually leave it alone.  I edited the makefile in amiga-gcc to call configure for GCC and explicitly pass /opt/homebrew for GMP, MPFR and MCP (because right now the makefile downloads those into projects/gcc instead of using the homebred versions) and I get a *lot* further.

Now I'm hitting this when building GCC (again, just leaving notes for any interested party):

Undefined symbols for architecture arm64:
  "_host_hooks", referenced from:
      __Z20c_common_no_more_pchv in c-pch.o
      __ZN6toplev4mainEiPPc in libbackend.a(toplev.o)
      __Z14gt_pch_restoreP7__sFILE in libbackend.a(ggc-common.o)
      __Z11gt_pch_saveP7__sFILE in libbackend.a(ggc-common.o)
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
gmake[2]: *** [/Users/test/work/amiga-gcc/projects/gcc/gcc/c/Make-lang.in:71: cc1] Error 1
make gcc...failed
use less "log/make gcc.log" to view the full log and search for ***
gmake: *** [Makefile:419: build-Darwin/gcc/_done] Error 2

**Comment by bebbo** [comment]
I just read this:
`compiled by GNU C version Apple LLVM 12.0.0 (clang-1200.0.32.29), GMP version 4.3.2, MPFR version 2.4.2, MPC version 0.8.1, isl version 0.15`
maybe it's helpful

**Comment by acf** [comment]
Read it where ?

**Comment by acf** [comment]
https://github.com/richfelker/musl-cross-make/issues/116. looks like a gcc problem maybe

**Comment by acf** [comment]
OK I'm. little closer.  Its *not* an ARM issue per se.  

https://github.com/bebbo/amiga-gcc/blob/master/Makefile#L402-L405

These lines seem to set up gcc to find gmp etc in the homebrew locations.  Trouble is Homebrew installs in `/opt/homebrew` on Apple Silicon, not `/usr/local`.   

In other words, if homebrew is installed anywhere other than `/usr/local`, those lines don't work.

If I manually change the those lines to point to`/opt/homebrew/lib` and `/opt/homebrew/include` and then run `CC=gcc-10 CXX=g++-10 SHELL=/opt/homebrew/bin/bash gmake update`. I get past the `configure gcc` stage successfully. 

Yay!

When it comes to the `make gcc` stage it runs a `configure isl` however which still failing saying gmp.h can't be found and I also noticed `checking which gmp to use... system` so I assume the --with-gmp information is not being passed on down.

So.

Given I can correct the lines in the amiga-gcc/Makefile to pass the right stuff for ARM during the `configure gcc` stage, what do I need to do to make sure that percolates down into the "inner" configure that's run during the `make gcc` stage ?

**Comment by acf** [comment]
looked in build-Darwin/gcc/Makefile and found that configure-isl is passed the values I passed in at the top 🤔   Though it would be nice to tell `make gcc` just to use the ISL that homebrew already installed.

<img width="960" alt="Screenshot 2021-03-18 at 23 10 42" src="https://user-images.githubusercontent.com/218/111709316-4e207800-883f-11eb-8977-df75a1012a57.png">
