### ISSUE TITLE
"make" from amiga-gcc doesn't work with Visual Studio Code plugin

### ISSUE THREAD

**Issue by hitman-codehq** [bebbo/amiga-gcc#209]
Hello.

A plugin for makefiles has just been released for Visual Studio Code.  A release announcement can be found here:

https://devblogs.microsoft.com/cppblog/now-announcing-makefile-support-in-visual-studio-code

For some strange reason, I was not able to get this to work with the version of make that is delivered with amiga-gcc, in c:\amiga-gcc\bin.  The plugin generates a .log file when it first runs, which contains this:

c:\amiga-gcc\bin\make.exe --dry-run --keep-going --print-directory
_make: *** No rule to make target '  --dry-run --keep-going --print-directory'.  Stop.

In order to get this to work, I had to download the native Win32 version of make from the GnuWin project (versions from both MSYS2 and Cygwin partially work but get cygwin1.dll clash errors when they try to launch m68k-amigaos-g++).

What is strange is that when launched from the command line (using amiga-gcc make), the above command works fine and prints the expected output.  It is only when launched from within the plugin that it doesn't work.  Is the version of make that comes with amiga-gcc compiled differently somehow?

I am running this on Windows 10 BTW.

Although this works with the native GnuWin version of make, it would be nice to get it working with the amiga-gcc version, as it took me a while to figure out how to get it to work.

Many thanks for a great cross compiler.  :-)

**Comment by bebbo** [comment]
use `_make.exe` instead of `make.exe` but add also the parameter `SHELL=path\to\sh.exe`

**Comment by hitman-codehq** [comment]
That works great - thanks!  But what is the background of this exactly, having both _make and make?  It's not entirely obvious what to do, hence my having to annoy you with raising an issue.  :-)

**Comment by bebbo** [comment]
`make.exe` is just a wrapper. otherwise you had to add the `SHELL=...` everytime

**Comment by hitman-codehq** [comment]
Ok, makes perfect sense now.  Thanks for the clarification!

If someone else has this problem, they should hopefully see this issue and its solution here, so I'll close it now.

**Comment by bebbo** [comment]
1. Replace the `bat2exe.exe` with the file from the attached zip
2. remove the `make.exe` file
3. start the `cmdline.bat` to open a shell with path

this rebuilds the `make.exe` using the newer `bat2exe.exe`.

If the program name was quoted, the trailing quote was not removed and the whole command line is treated as a single parameter.

=> now make.exe should run


[bat2exe.zip](https://github.com/bebbo/amiga-gcc/files/6061841/bat2exe.zip)

**Comment by hitman-codehq** [comment]
Hello again.

I finally got some time to try out your new bat2exe.exe and now running make.exe directly runs perfectly!  Thanks very much for your help.  :-)

Stupid Windows Defender gets a false positive when downloading the archive but then Defender often does with software like this that does executable "magic".  Also with demo scene crunched files.  I'll see if they have a page where you can upload false positives and will upload the archive.
