### ISSUE TITLE
Problems when adding support for identify.library

### ISSUE THREAD

**Issue by tehKaiN** [bebbo/amiga-gcc#214]
I'm trying to use the following library: http://aminet.net/package/util/libs/Identify

I've added identify.sdk:

```
Short: identify.library
Version: 1
Url: http://aminet.net/util/libs/Identify.lha

Identify/include/clib/identify_protos.h
Identify/include/fd/identify_lib.fd = identify.fd
Identify/include/proto/identify.h
Identify/include/pragmas/identify_pragmas.h
Identify/include/libraries/identify.h

fd2sfd : identify.fd clib/identify_protos.h
sfdc : identify.sfd
stubs : identify.sfd
```

Then I issue the `make sdk=identify` on my current installation and it builds with nix20 just fine, but then, when running the executable I get `Identify.library failed to load` error, even though I have the identify.library in my libs: directory. This is not the error from my OpenLibrary, but probably something from startup code.

What am I missing?

**Comment by bebbo** [comment]
try lower case maybe?

**Comment by tehKaiN** [comment]
I've changed sdk def to one without uppercase where possible:

```
Short: identify.library
Version: 1
Url: http://aminet.net/util/libs/Identify.lha

identify/include/clib/identify_protos.h
identify/include/fd/identify_lib.fd = identify.fd
identify/include/proto/identify.h
identify/include/pragmas/identify_pragmas.h
identify/include/libraries/identify.h

fd2sfd : identify.fd clib/identify_protos.h
sfdc : identify.sfd
stubs : identify.sfd
```

I can't change URL because it won't resolve, but it still creates `build/identify/identify.c` which tries to do OpenLibrary on `Identify.library`. Where does it take the library name from?

**Comment by bebbo** [comment]
```
/* Automatically generated header (sfdc 1.11)! Do not edit! */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#if defined (__libnix__)

#include <stabs.h>
void* IdentifyBase[2] = { 0, "Identify.library" };
```
there is the problem

**Comment by bebbo** [comment]
```
fd2sfd)
				fd=${a[1]}
				proto=${a[2]}
				file=$(basename $fd)
				name=${file%???} 
```

the name is taken from the file name and it starts with an upper case ...

**Comment by tehKaiN** [comment]
So perhaps sdk could have another line for .library name, and if it's omitted it would fall back to old behavior?

**Comment by bebbo** [comment]
go ahead and provide the patch^^

**Comment by tehKaiN** [comment]
I will if you don't have time. Not today, perhaps tomorrow. ;)

**Comment by tehKaiN** [comment]
We've wrongly diagnosed the problem!

`$3/bin/fd2sfd -o $3/m68k-amigaos/lib/sfd/$name.sfd $3/m68k-amigaos/lib/fd/$fd $3/m68k-amigaos/include/$proto`

this expands to:

`/opt/amiga/bin/fd2sfd -o /opt/amiga/m68k-amigaos/lib/sfd/identify.sfd /opt/amiga/m68k-amigaos/lib/fd/identify.fd /opt/amiga/m68k-amigaos/include/clib/identify_protos.h`

no uppercase at this point, but the result is:

```
* This SFD file was automatically generated by fd2sfd from
* /opt/amiga/m68k-amigaos/lib/fd/identify.fd and
* /opt/amiga/m68k-amigaos/include/clib/identify_protos.h.
==base _IdentifyBase
==basetype struct Library *
==libname Identify.library <----- uppercase is here
==include <exec/types.h>
==include <utility/tagitem.h>
* "identify.library"
==bias 30
==public
LONG IdExpansion(struct TagItem * TagList) (a0)
==varargs
LONG IdExpansionTags(Tag TagList, ...) (a0)
STRPTR IdHardware(ULONG Type, struct TagItem * TagList) (d0,a0)
==varargs
STRPTR IdHardwareTags(ULONG Type, Tag TagList, ...) (d0,a0)
LONG IdAlert(ULONG ID, struct TagItem * TagList) (d0,a0)
==varargs
LONG IdAlertTags(ULONG ID, Tag TagList, ...) (d0,a0)
LONG IdFunction(STRPTR LibName, LONG Offset, struct TagItem * TagList) (a0,d0,a1)
==varargs
LONG IdFunctionTags(STRPTR LibName, LONG Offset, Tag TagList, ...) (a0,d0,a1)
ULONG IdHardwareNum(ULONG Type, struct TagItem * TagList) (d0,a0)
==varargs
ULONG IdHardwareNumTags(ULONG Type, Tag TagList, ...) (d0,a0)
void IdHardwareUpdate() ()
==end
```

the .fd looks like this:

```
* "identify.library"
##base _IdentifyBase
##bias 30
##public
IdExpansion(TagList)(a0)
IdHardware(Type,TagList)(d0,a0)
IdAlert(ID,TagList)(d0,a0)
IdFunction(LibName,Offset,TagList)(a0,d0,a1)
IdHardwareNum(Type,TagList)(d0,a0)
IdHardwareUpdate()()
##end
```

the .h looks like this:

```
#ifndef  CLIB_IDENTIFY_PROTOS_H
#define  CLIB_IDENTIFY_PROTOS_H

/*
**      $VER: identify_protos.h 8.1 (30.10.97)
**
**      (C) Copyright 1996-1997 Richard Krber
**          All Rights Reserved
*/
LONG IdAlert(ULONG, struct TagItem *);
LONG IdAlertTags(ULONG, ULONG,...);
LONG IdExpansion(struct TagItem *);
LONG IdExpansionTags(ULONG,...);
LONG IdFunction(STRPTR, LONG, struct TagItem *);
LONG IdFunctionTags(STRPTR, LONG, ULONG,...);
STRPTR IdHardware(ULONG, struct TagItem *);
STRPTR IdHardwareTags(ULONG, ULONG,...);
ULONG IdHardwareNum(ULONG, struct TagItem *);
ULONG IdHardwareNumTags(ULONG, ULONG,...);
void IdHardwareUpdate(void);

#endif
```

where does the uppercase come from? I've looked at the fd2sfd:


```c
	 switch (parsing)
	 {
	    case name:
	       switch (buf[0])
	       {
		  case '#':
		     if (strncmp("##base", buf, 6)==0)
		     {
			bnext=buf+6;
			while (*bnext==' ' || *bnext=='\t' || *bnext=='_')
			   bnext++;
			strcpy(BaseName, bnext);
			BaseName[strlen(BaseName)-1]='\0';
		     }
```

this parses the .fd's line `##base _IdentifyBase`. Fills BaseName with `IdentifyBase`. Then we have:

```c
   if (strlen(fdfilename)>7 &&
   !strcmp(fdfilename+strlen(fdfilename)-7, "_lib.fd"))
   {
     // this is skipped
   }
   else
   {
     // we doing this:
      strcpy(BaseNamU, BaseName); // BaseNamU = "IdentifyBase"
      if (strlen(BaseNamU)>4 && strcmp(BaseNamU+strlen(BaseNamU)-4, "Base")==0)
	 BaseNamU[strlen(BaseNamU)-4]='\0'; // BaseNamU = "Identify"
      strcpy(BaseNamL, BaseNamU); // BaseNamL = "Identify"
      strcpy(BaseNamC, BaseNamU);
   }
```

then it's used here:

```c
      fprintf(outfile, "==libname %s.%s\n",
	      strcmp(BaseNamL, "cardres") == 0 ? "card" : BaseNamL, type);
```

I see mixed indentation whitespace inside fd2sfd fd parsing code's part listed above, so you or someone else have modified it. I see no comments why, so I'd rather not do things blindly and break anyone's intentional change in the process. How this can be fixed?

Or perhaps, the proper approach to fixing this is to modify the ctor so that it case-insensitive find a .library file and then pass the found name to OpenLibrary()? or perhaps that would be too slow?

Funny thing is, I've changed the identify.library in my `libs:` to Identify.library and it doesn't help. Perhaps this is red herring and the issue is something else?

**Comment by bebbo** [comment]
you'd have to patch the libraries internal name to start with an uppercase 'I'

**Comment by tehKaiN** [comment]
so the case-insensitive thingy and my rename couldn't work. I'm afraid the issue needs a proper fix then. ;)

**Comment by bebbo** [comment]
I guess fd2sfd needs a fix^^

**Comment by tehKaiN** [comment]
okay, this is nuts. Everything is dependent on getting BaseNamU from here:

```c
   if (strlen(fdfilename)>7 &&
      !strcmp(fdfilename+strlen(fdfilename)-7, "_lib.fd"))
   {
      // Extract .library name directly from .fd file name
      // e.g. muimaster_lib.fd -> extracts "muimaster"
      char *str=fdfilename+strlen(fdfilename)-8;
      while (str!=fdfilename && str[-1]!='/' && str[-1]!=':')
	 str--;
//lcs      strncpy(BaseNamL, str, strlen(str)-7);
      strncpy(BaseNamU, str, strlen(str)-7);
      BaseNamU[strlen(str)-7]='\0';
      strcpy(BaseNamL, BaseNamU);
      strcpy(BaseNamC, BaseNamU);
   }
   else
   {
      // Use library name from from inside .fd (line "==base")
      // e.g. "##base _CyberGfxBase" -> uses "CyberGfx"
      strcpy(BaseNamU, BaseName);
      if (strlen(BaseNamU)>4 && strcmp(BaseNamU+strlen(BaseNamU)-4, "Base")==0)
         BaseNamU[strlen(BaseNamU)-4]='\0';
      strcpy(BaseNamL, BaseNamU);
      strcpy(BaseNamC, BaseNamU);
   }
```

If I change `else` branch to convert things to lowercase, then I'll fix loading identify.library but break CyberGfx.library. No idea how to fix it. Okay, I have one idea, but it's hacky as hell.

- identify.fd has following line: `* "identify.library"`
- I could scan .fd for line `* {FOO}library` and if it's found, use `{FOO}` as library file name candidate
- if fd file matches `{libname}_lib.fd`, use `{libname}` as a name for .library
- if no match and name candidate is set, use it
- if no match and no candidate, use library base - fallback for CyberGfx

any thoughts?

**Comment by tehKaiN** [comment]
I'm no RTG user, so I've asked around a bit and looked here and there and it looks like the cgx lib is usually named `cybergraphics.library` and not `CyberGfx.library`. E.g. here https://github.com/bebbo/amiga-gcc/issues/21 the last comment confirms it.

Any thoughts? Perhaps the cgx behavior is erratic from the start, so I could fix that too - if it would just extract name using patterns `{libname}_lib.fd` and `{libname}.fd`.

**Comment by tehKaiN** [comment]
I made a PR for fd2inline . Let's see what happens but I'm afraid adtools won't be responding too soon. :(
