### ISSUE TITLE
Something is very wrong with float operations with soft-float.

### ISSUE THREAD

**Issue by TCH68k** [bebbo/amiga-gcc#216]
Here is an archive with the source code, build script and built binary. It still uses your `mathieeesingbas.library` (https://github.com/bebbo/libnix/issues/36). I don't know if it's the latest, this is the only one i found.

Sometimes, some operations are nonsensical.

76 / 518 which should be smaller than zero become a gigantic number.
http://oscomp.hu/depot/76_div_518_is_nonsense.png

A negative value was evaluated as larger than plus three (the corrected x at step 1), also, a nonzero value raised to the second power become zero (corrected x at step 2 was 9.43 and the power is -0).
http://oscomp.hu/depot/nonzero_x_pow2_is_zero_and_negative_is_bigger_than_three.png

**Comment by bebbo** [comment]
> 
> 
> Here is an archive with the source code, build script and built binary.

where is here?

**Comment by bebbo** [comment]
[mathieeesingbas.zip](https://github.com/bebbo/amiga-gcc/files/6315521/mathieeesingbas.zip)

there's a difference between little and big endian^^

**Comment by TCH68k** [comment]
Sorry, i've forgot to put the archive link into the post; i was very tired...
But it does not matter anymore, as this instance of `mathieeesingbas.library` has fixed the problems, thank you.

How endianity came into the picture? The other issue mentioned nothing about endianity and Amigas are all big-endian. Why was the other instance in little endian?

**Comment by bebbo** [comment]
> 
> 
> Sorry, i've forgot to put the archive link into the post; i was very tired...
> But it does not matter anymore, as this instance of `mathieeesingbas.library` has fixed the problems, thank you.
> 
> How endianity came into the picture? The other issue mentioned nothing about endianity and Amigas are all big-endian. Why was the other instance in little endian?

the code for the lib is for both endianesses... so it needs the proper defines^^
