### ISSUE TITLE
compiled code misbehaves again

### ISSUE THREAD

**Issue by githubaf** [bebbo/amiga-gcc#22]
Since I use amiga-gcc instead of toolchain the compiler produces erroneous code again. I cannot say when the issue first appeared in amiga-gcc. Older versions fail to compile my code because of missing includes (ahi for instance) ) (I could try to copy the missing includes manually if you want)

Newer versions of the compiler lead to stuttering espeak. (I let espeak create wav-files, so this is not a speed issue)

I compile with -O2, but the problem is the same with -O0.

Then I checked the toolchain repository and found there where updates, too.

In the toochain-repository the problems where introduced on April 8th,
"update to a reasonable version from amiga-gcc"
268fed6bcfca3f34cb22c89f100507cfe87f03cd

Commits before work correctly.

**Comment by bebbo** [comment]
The current version `gcc version 6.4.1b 20180401-215902` and the older amigaos-toolchain-version `gcc version 6.4.1b 20180311-223423` are creating identical output for espeak-amiga.

BTW: why does your repo not compile out of the box?

**Comment by githubaf** [comment]
You are right, the issue is not in the compiler, so this issue can be closed.
It is in libnix. I will open a new issue there.

>BTW: why does your repo not compile out of the box? 
What do you mean?
cd src
make -f Makefile.amiga

**Comment by bebbo** [comment]
ah `cd src`
