### ISSUE TITLE
pointer targets in initialization differ in signedness

### ISSUE THREAD

**Issue by githubaf** [bebbo/amiga-gcc#223]
Maybe more a question, but...

consider the following "program"
```
// m68k-amigaos-gcc -Wall -noixemul chartest.c -o chartest

#include <exec/types.h>
#include <stdio.h>

STRPTR p1="Hallo";   // --> warning: pointer targets in initialization differ in signedness [-Wpointer-sign]

int main(void)
{
        printf("%s\n",p1);
        return 0;
}
```
The compiler complains about "pointer targets in initialization differ in signedness"

For instance OpenLibrary() expects the Libname as STRPTR. I could always cast, but that cannot be the correct way!?
What could be done here instead of just supressing the warning at all with [-Wno-pointer-sign]?

Could the headerfile be changed??

STRPTR is typedefed as 
typedef unsigned char  *STRPTR;
in exec/types.h. Changing that to just 
typedef char  *STRPTR;  // without "unsigned"
would fix the warning. The same is true for CONST_STRPTR.

**Comment by bebbo** [comment]
sure - could be changed...
... but the Amiga NDK wants you to suffer. Even the NDK3.2 sticks to this...

**Comment by githubaf** [comment]
According to Olsen we have to live with that...
Ok, thanks anyway. I will supress the warning then.

**Comment by bebbo** [comment]
you could modify it in your version and look how it behaves...
... or use c++ then it's signed char^^
