### ISSUE TITLE
SDL_FULLSCREEN doesn't render in the center of the screen

### ISSUE THREAD

**Issue by kallaballa** [bebbo/amiga-gcc#224]
In my project: https://github.com/kallaballa/FractalDive i use SDL1 to render a fractal zoom. I am using paletted (8-Bit) mode and in order to get a more beautiful palette i choose to use fullscreen mode. My problem is that the fractals are renderer in the upper left corner instead of the center. and in the center there is a black rectangle where the rendering actual should show. 
Another interesting fact is that mouse events are only received in the center black rectangle.
![bla](https://user-images.githubusercontent.com/287266/122598415-165ae380-d06d-11eb-87c8-8eabb086bec5.png)

I am using version 6.5.0b.
my shortened emulator config:
```
[fs-uae]
amiga_model = A4000
chip_memory = 2048
fast_memory = 4096
graphics_card = uaegfx
graphics_memory = 32768
hard_drive_0 = dive.hdf
kickstart_file = Kickstart_v3.1_r40.70_1994_Commodore_A4000.rom
```

**Comment by bebbo** [comment]
does a working Amiga version exist to compare it to?

**Comment by kallaballa** [comment]
Do you mean OS version?
