### ISSUE TITLE
Unable to compile for the full range of Kickstart versions.

### ISSUE THREAD

**Issue by darrenfreeman** [bebbo/amiga-gcc#225]
My goal is to create a single executable, which will run on any Kickstart from 1.0-3.1, and detect which Kickstart version is in use. It will either disable certain features, or use shims, to get around missing features of the earlier Kickstarts.

I am working with the simplest test code, which is:

`int main(int argc, char **argv) { return 0; }`

No includes, just that.

If compiled without `-mcrt=nix13`, then it will immediately crash on a 1.3 machine. So, I am forced to use `-mcrt=nix13`. This has a side-effect of not working with `-noixemul`, and so inflating the executable to around 20 KB, even for this do-nothing test.

The problem with this approach is that I don't then have access to later functions, such as AllocBitMap. I can make my own include file which copies the definitions for just those things that I need... but is this the intended approach?

Is it supposed to just *crash* on a 1.3 machine, without nix1.3? Can I mix nix1.3 with the later includes?

Can I just not use nix at all? What are the consequences?

**Comment by bebbo** [comment]
`-noixemul` is a synonym for `-mcrt=nix20` -> you can only use one of these variants.
And yes: `-noixemul` will crash on KICK1.3 since it uses KICK2.0 functions.

for KICK1.3 use `-mcrt=nix13` - only this and only once. If it works with even older Kickstarts is out of my scope.

**Comment by darrenfreeman** [comment]
How can I produce an executable that works on any Kickstart version, and has access to later functions after checking for their existence?

Can I use nix1.3 with the later includes? Is it possible to not use nix1.3 at all, and use purely native OS functions?

I was able to call AllocBitMap by pasting the definitions, from newer includes, into my code. Is this the correct approach?

**Comment by bebbo** [comment]
please ask in an Amiga forum, e.g. http://eab.abime.net/
