### ISSUE TITLE
clib2 build broken after ndk3.2 update

### ISSUE THREAD

**Issue by alexalkis** [bebbo/amiga-gcc#228]
amiga_invertstring.c:102:9: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
  for(cp = (*strp) ; (*cp) ; cp++)
         ^
amiga_invertstring.c:116:11: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
   (*strp) = cp; /* point to char following '>' */
           ^
amiga_invertstring.c:120:11: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
   (*strp) = cp - 1;   /* ++will point to terminating null */
           ^
amiga_invertstring.c: At top level:
amiga_invertstring.c:142:1: error: conflicting types for 'InvertString'
 InvertString(STRPTR str, CONST struct KeyMap *km)
 ^~~~~~~~~~~~
In file included from amiga_invertstring.c:44:0:
/opt/amiga/gcc6/m68k-amigaos/ndk-include/clib/alib_protos.h:94:30: note: previous declaration of 'InvertString' was here
 __stdargs struct InputEvent *InvertString( CONST_STRPTR str, CONST struct KeyMap *km );
                              ^~~~~~~~~~~~
make[2]: *** [GNUmakefile.68k:87: large_data_020/libamiga_objs/amiga_invertstring.o] Error 1

**Comment by bebbo** [comment]
maybe you forgot to update clib2?

**Comment by alexalkis** [comment]
doesn't "make update" updates all the subprojects?

**Comment by bebbo** [comment]
yes it does - I'm only guessing

did you start with a clean prefix?

**Comment by bebbo** [comment]
> ```/opt/amiga/gcc6/m68k-amigaos/ndk-include/clib/alib_protos.h:94:30: note: previous declaration of 'InvertString' was here
__stdargs struct InputEvent *InvertString( CONST_STRPTR str, CONST struct KeyMap *km );```

looks like an old header - __stdargs is not there yet!

**Comment by bebbo** [comment]
switching NDK -> `make clean-prefix`

**Comment by alexalkis** [comment]
I rm'ed the whole prefix

**Comment by bebbo** [comment]
you removed `$PREFIX` - which is maybe something different

```
struct InputEvent *InvertString( STRPTR str, CONST struct KeyMap *km );
```
is the new  proto - your's not

**Comment by alexalkis** [comment]
Source code has

```
struct InputEvent *
#ifdef APTR_TYPEDEF
InvertString(STRPTR str, CONST struct KeyMap *km)
#else
InvertString(CONST_STRPTR str, CONST struct KeyMap *km)
#endif
```

**Comment by bebbo** [comment]
that's current - but your `m68k-amigaos/ndk-include/clib/alib_protos.h` is old

**Comment by alexalkis** [comment]
then alib_protos.h is generated wrong

**Comment by bebbo** [comment]
why generated?
```
@cp -p projects/$(NDK_FOLDER_NAME_H)/proto/alib.h $(PREFIX)/m68k-amigaos/ndk-include/proto
```

**Comment by alexalkis** [comment]
how you specify to the toolchain what NDK to use? or it provides both?

**Comment by bebbo** [comment]
ok - sorry - though you were building with NDK=3.2

my fault.

**Comment by alexalkis** [comment]
How would I do that though? Not that I want to, but how?

**Comment by alexalkis** [comment]
i.e. what NDK does the "make all" assume?

**Comment by bebbo** [comment]
default is still 3.9. you'd have to add NDK=3.2 for the new NDK - where still some adjustments are missing.

Please update clib2 and build - sorry

**Comment by alexalkis** [comment]
Breaks in another point now.

```
make[1]: Entering directory '/home/alex/t/amiga-gcc/build-Linux/libdebug'
m68k-amigaos-gcc -W -Wall -Wstrict-prototypes  -DUSE_SERIAL -c /home/alex/t/amiga-gcc/projects/libdebug/debug.c -o kdebug.o
/home/alex/t/amiga-gcc/projects/libdebug/debug.c:113:6: error: conflicting types for 'KDoFmt'
 VOID KDoFmt(CONST_STRPTR formatString, CONST_APTR dataStream,
      ^~~~~~
In file included from /home/alex/t/amiga-gcc/projects/libdebug/debug.c:82:0:
/opt/amiga/gcc6/m68k-amigaos/ndk-include/clib/debug_protos.h:44:6: note: previous declaration of 'KDoFmt' was here
 VOID KDoFmt( CONST_STRPTR formatString, CONST APTR dataStream, CONST APTR putChProc, APTR putChData );
      ^~~~~~
/home/alex/t/amiga-gcc/projects/libdebug/debug.c: In function 'KDoFmt':
/home/alex/t/amiga-gcc/projects/libdebug/debug.c:124:3: warning: function declaration isn't a prototype [-Wstrict-prototypes]
   RawDoFmt(formatString, dataStream,
   ^~~~~~~~
/home/alex/t/amiga-gcc/projects/libdebug/debug.c:124:3: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
/home/alex/t/amiga-gcc/projects/libdebug/debug.c: At top level:
/home/alex/t/amiga-gcc/projects/libdebug/debug.c:93:17: error: conflicting types for 'KPutFmt'
 #define F(name) K ## name
                 ^
/home/alex/t/amiga-gcc/projects/libdebug/debug.c:162:6: note: in expansion of macro 'F'
 VOID F(PutFmt)(CONST_STRPTR formatString, CONST_APTR values) {
      ^
In file included from /home/alex/t/amiga-gcc/projects/libdebug/debug.c:82:0:
/opt/amiga/gcc6/m68k-amigaos/ndk-include/clib/debug_protos.h:32:6: note: previous declaration of 'KPutFmt' was here
 VOID KPutFmt( CONST_STRPTR formatString, CONST APTR values );
      ^~~~~~~
make[1]: *** [Makefile:37: kdebug.o]
```

**Comment by bebbo** [comment]
ah yes - maybe I should patch the ndk 3.9 headers...

**Comment by bebbo** [comment]
`git pull` should solve it now

**Comment by alexalkis** [comment]
Yeap, everything builds now.  Thanks!

**Comment by bebbo** [comment]
thank you for reporting - sorry for the inconvenience

**Comment by alexalkis** [comment]
You are welcome.  And no inconvenience at all, thanks for your work on this.
