### ISSUE TITLE
Crashes for a simple program

### ISSUE THREAD

**Issue by m0ppers** [bebbo/amiga-gcc#23]
I have a very minimal program that creates reproducable hard crashes for me in UAE:

```
#include <stdio.h>

class TestClass {
  public:
    TestClass(): count(0), structs() {
    }

    typedef struct {
        char path[256];
        char name[256];
        int test;
    } TestStruct;

    TestStruct structs[10];
    int count;
};

int main() {
    TestClass c;
    for (int i=0;i<10;i++) {
        printf("%s %s %d\n", c.structs[i].path, c.structs[i].name, c.structs[i].test);
    }
    return 0;
}
```

Didn't yet go down to assembly level. Will probably do so in the following days but maybe you have an immediate idea.

Compiled like this:

```
/home/mop/m68k-amigaos-gcc6/bin/m68k-amigaos-g++ -noixemul -m68030 -m68881 /mnt/d/le3d-amiga/testi.cpp -o testi
```

It seems to be related to the memory allocations of the struct array. The `structs()` should auto initialize every struct (and all its members recursively) to zero and does so on linux.

**Comment by bebbo** [comment]
what stacksize are you using? try `stack 200000` and run it again.

**Comment by m0ppers** [comment]
wow...didn't know that (pretty new to the amiga stuff)...thank you...works
