### ISSUE TITLE
Build fails due to NDK 3.9 download issues

### ISSUE THREAD

**Issue by obarthel** [bebbo/amiga-gcc#230]
I originally ran into this on my development machine (macOS Big Sur 11.5.2, etc.) but it seems that the same issue appears if you start from scratch on a Debian 10.10 system, with all the recommended packages installed to build the compiler.

Please note that this is not an issue of a missing git pull or rebase. It follows the instructions given on the project's home page on a VM set up from scratch to build the compiler, today.
[build-attempt.txt](https://github.com/bebbo/amiga-gcc/files/6992654/build-attempt.txt)

**Comment by bebbo** [comment]
thanks - fixed

**Comment by obarthel** [comment]
Turns out that the issue is back again today. It started over with a checkout of "amiga-gcc" and it now stops at the point where it tries to 
[download from the URL http://www.haage-partner.de//home/olsen/amiga-gcc/download/AmigaOS/NDK3.9.lha](https://github.com/bebbo/amiga-gcc/files/7006135/ndk-download.txt). Somehow the current directory name gets caught up in the download operation.

**Comment by bebbo** [comment]
fixed
