### ISSUE TITLE
Build fails if the working if make called with sudo

### ISSUE THREAD

**Issue by obarthel** [bebbo/amiga-gcc#231]
I have been trying my best to build the compiler and everything on my Mac at home but it never worked, always stopping with a baffling error message. Turns out that the reason for that was that I already had an "amiga-gcc" directory in my "Documents" directory and had checked out your project into "amiga-gcc-beppo".

Trying to reproduce the problem I had set up a Debian Linux 10.10 virtual machine and today succeeded in building & installing the compiler with "sudo make all", having checked out your project into "amiga-gcc".

Then I rolled back the virtual machine to its prior state and repeated the same steps, this time checking out the project into "amiga-gcc-beppo", followed by "make update" and "sudo make all". The build failed quickly at the "make fd2sfd..." stage:
[build-attempt.txt](https://github.com/bebbo/amiga-gcc/files/6999969/build-attempt.txt)

I then rolled back the virtual machine again, checked out your project into "amiga-gcc" and repeated everything. "sudo make all" eventually succeeded. Then I performed a "sudo make clean", renamed the directory to "amiga-gcc-beppo" and followed it with "sudo make all". This attempt then failed completely as the first one had. I followed this up with "sudo make clean", renaming the "amiga-gcc-beppo" directory back to "amiga-gcc" and starting over. This completed successfully.

Don't ask how long this took 😁

**Comment by bebbo** [comment]
the last two lines do read:
```
use less "log/make fd2sfd.log" to view the full log and search for ***
make: *** [Makefile:501: build-Linux/fd2pragma/fd2pragma] Error 1
```

=> what's the content of `log/make fd2sfd.log` ?

**Comment by bebbo** [comment]
and why `sudo make all` ?

also use `-j` with a reasonable count to speed it up...

**Comment by obarthel** [comment]
> the last two lines do read:
> 
> ```
> use less "log/make fd2sfd.log" to view the full log and search for ***
> make: *** [Makefile:501: build-Linux/fd2pragma/fd2pragma] Error 1
> ```
> 
> => what's the content of `log/make fd2sfd.log` ?

You won't like it because it repeats what has already been printed on the console 😉 :

install: cannot stat 'build-Linux/fd2pragma/fd2pragma': No such file or directory

**Comment by obarthel** [comment]
> and why `sudo make all` ? there is no need for sudo - maybe this causes problems!?

This is needed if you build as an unprivileged user, or otherwise the build will collapse with baffling error messages very quickly 😢 

The Makefile uses `mkdir -p $(PREFIX)/bin/` which won't work unless the directory referenced by $(PREFIX) (which would be `/opt/amiga` by default) already exists and is world- or user-writable.

This was not the case for my Mac setup at home (no "/opt/amiga" directory there), and neither for the "build this over and over again on a freshly installed Debian 10.10 Linux system" exercise 😉 

> also use `-j` with a reasonable count to speed it up...

Could have been worse, and I didn't grant the VM more than 1 CPU to begin with, because I didn't think it would have been necessary. How wrong I was 😉

**Comment by bebbo** [comment]
> 
> 
> > and why `sudo make all` ? there is no need for sudo - maybe this causes problems!?
> 
> This is needed if you build as an unprivileged user, or otherwise the build will collapse with baffling error messages very quickly 😢
> 
> The Makefile uses `mkdir -p $(PREFIX)/bin/` which won't work unless the directory referenced by $(PREFIX) (which would be `/opt/amiga` by default) already exists and is world- or user-writable.
> 
> This was not the case for my Mac setup at home (no "/opt/amiga" directory there), and neither for the "build this over and over again on a freshly installed Debian 10.10 Linux system" exercise 😉
> 
> > also use `-j` with a reasonable count to speed it up...
> 
> Could have been worse, and I didn't grant the VM more than 1 CPU to begin with, because I didn't think it would have been necessary. How wrong I was 😉

The README.MD contains a section about the prefix...
```
The build performs the installation automatically, there is no separate make install step. Because of this, you must make sure that the target PREFIX directory is writable for the user who is doing the build. If the PREFIX directory points to a directory where the user already has appropriate permissions the below steps can be ommited and the directory will be created by the build process.

sudo mkdir /opt/amiga
sudo chgrp users /opt/amiga
sudo chmod 775 /opt/amiga
sudo usermod -a -G users username
```

**Comment by obarthel** [comment]
Hold on, I still need to verify if the sudo thing has any impact on the build failing if the directory the project was checked out it into is different from "amiga-gcc"!

**Comment by bebbo** [comment]
> 
> 
> Hold on, I still need to verify if the sudo thing has any impact on the build failing if the directory the project was checked out it into is different from "amiga-gcc"!

it's the `sudo` - juet verified it on a fresh debian vm - and the issue isn't closed - just tagged^^
(and with sufficient cpu power the full build time is ~ 6 mins)

**Comment by obarthel** [comment]
I'm sorry that these 30 minutes have stretched "a bit" ☹️ 

I can confirm that the "sudo make all" in my tests yesterday was indeed responsible for the build going off the rails. Furthermore, when building & installing with just "make all" it is possible to rename the directory into which the working tree was checked out. So "sudo" has a lot to answer for.

**Comment by bebbo** [comment]
fixed
