### ISSUE TITLE
Line-by-line Profiling

### ISSUE THREAD

**Issue by githubaf** [bebbo/amiga-gcc#236]
Is Line-by-line Profiling possible with  m68k-amigaos-gprof?
There is the option "-l" or "--line" and m68k-amigaos-gprof does not complain about them, but I could not see any difference in the output.

**Comment by bebbo** [comment]
how do you build the profiled program?

**Comment by bebbo** [comment]
`~/test` is a link to WinUAE folder, also named test on Amiga side.
```
m68k-amigaos-gcc -Os collatz.c -noixemul -o collatz -pg -g -fprofile-dir=/test
cp collatz ~/test/
```
run the program on the Amiga side
```
cp ~/test/gmon.out .
m68k-amigaos-gprof -l collatz
```

the output contains line numbers:
```
...
Each sample counts as 0.02 seconds.
  %   cumulative   self              self     total           
 time   seconds   seconds    calls  ns/call  ns/call  name    
 54.88      0.90     0.90 62135400    14.48    14.48  step (collatz.c:7 @ c8)
 20.73      1.24     0.34                             nseq (collatz.c:30 @ 126)
 15.85      1.50     0.26                             step (collatz.c:10 @ dc)
  8.54      1.64     0.14                             step (collatz.c:14 @ e2)
  0.00      1.64     0.00   499999     0.00     0.00  nseq (collatz.c:20 @ ee)
  0.00      1.64     0.00        1     0.00     0.00  main (collatz.c:39 @ 152)
...
```

**Comment by githubaf** [comment]
This works really beautifully! Thanks for your example.
My fault was propably a missing "-g". Both -pg and -g are necessary.
If we compare the outputs with and without '-l', we see the sum of self-seconds of all lines of a certain function is equal to the total time spent in that function. Nice!

btw, the "-fprofile-dir=/test" in your example seem not be necessary for profiling. -fprofile-dir specifies the directory, where the executable should store it's gcda-files when compiled for code-coverage. (So it must be path valid and existing on Amiga. The produced gcda-Files the need to be copied to Linux afterwards)
