### ISSUE TITLE
__floatsisf __fixsfsi __floatsidf __umoddi3__udivdi3 and others are missing

### ISSUE THREAD

**Issue by mheyer32** [bebbo/amiga-gcc#237]
Something in the toolchain has changed,  I can no longer link https://github.com/mheyer32/ADoom or Dopus5.
libdebug.a seems also missing.

Anything i can do about it?

**Comment by bebbo** [comment]
ADoom gets build as usual here...

... do you start from scratch? If not maybe `make update-repos && make update` might help

**Comment by mheyer32** [comment]
I completely nuked the amiga-gcc directory and started from scratch.
It seems I had a build failure, but overlooked it. It happened a few pages up in the console :-)
When I ran into this issue, I just re-ran (without clearing) the build and then it finished.
This is what I saw on the console:

```
sdk sdi...failed
Short: A set of C macro/defines to make amiga development easier.
Version: 1.7
~/amigatoolchain/amiga-gcc/projects ~/amigatoolchain/amiga-gcc
Cloning into 'SDI'...
sdk sdi...failed
use less "log/sdk sdi.log" to view the full log and search for ***
make clib2... sdk mmu... sdk mui...install libpthread...Makefile:963: recipe for target 'sdk' failed
make[2]: *** [sdk] Error 1
sdk warp3d...make[2]: Leaving directory '/home/matze/amigatoolchain/amiga-gcc'
Makefile:136: recipe for target 'x' failed
make[1]: *** [x] Error 2
make[1]: Leaving directory '/home/matze/amigatoolchain/amiga-gcc'
Makefile:971: recipe for target 'sdi' failed
make: *** [sdi] Error 2
make: *** Waiting for unfinished jobs....
make[2]: Entering directory '/home/matze/amigatoolchain/amiga-gcc'

```
