### ISSUE TITLE
Coverage combined with -Wl,-Map=espeak.map,--trace crashes Linker

### ISSUE THREAD

**Issue by githubaf** [bebbo/amiga-gcc#24]
I am using -Wl,-Map=espeak.map,--trace to get interesting output when linking.

Now I tried coverage and the linker coredumps...
The crash does not happen when either 
-Wl,-Map=espeak.map,--trace
or
the coverage options
are removed.

To reproduce use the coverage-example:

m68k-amigaos-gcc -Wall -fprofile-arcs -ftest-coverage cov.c -noixemul -lgcov -o cov -fprofile-generate=. -Wl,-Map=espeak.map,--trace 

collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
compilation terminated.

**Comment by bebbo** [comment]
fixed in binutils 2.29 and ported back to binutils 2.14

**Comment by githubaf** [comment]
Just checked. It still coredumps for me . Do I have the right version?

I have

/projects/binutils$ git log 
commit 81e03077bde34d5ed8c77ad10185407e69f5da2c
Author: Bebbo <bebbo@bejy.net>
Date:   Sat Jun 2 22:56:07 2018 +0200

    fix structure - it's defined elsewhere too... so append at end

/home/developer/opt/m68k-amigaos_03Jun18/bin/m68k-amigaos-gcc -noixemul -m68000         -g                   -Wl,-Map=espeak.map,--trace    -o espeak speak.o compiledict.o dictionary.o intonation.o readclause.o setlengths.o numbers.o synth_mbrola.o synthdata.o synthesize.o translate.o mbrowrap.o tr_languages.o voices.o wavegen.o phonemelist.o klatt.o sonic.o portaudio.o portaudio_audev.o portaudio_ahidev.o subtask_support.o mkstemp.o amiga_version.o AddSineWaves.o -lgcov -lm  -ldebug 
collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped

**Comment by bebbo** [comment]
no idea - I shoud patch the binutils version too...

but `m68k-amigaos-gcc -Wall -fprofile-arcs -ftest-coverage cov.c -noixemul -lgcov -o cov -Wl,-Map=some.map,--trace` does no longer crash here

**Comment by githubaf** [comment]
Your last version from yesterday, June9th 2018 solved the problem enventually. Crash is gone.
Thank you very much!
