### ISSUE TITLE
error: variable or field '_SubTime_re2' declared void

### ISSUE THREAD

**Issue by darrenfreeman** [bebbo/amiga-gcc#242]
I just did a make update, and now compilation is failing for this macro from `/opt/amiga/m68k-amigaos/ndk13-include/inline/timer.h`:

```
m68k-amigaos-gcc -mcrt=nix13 -std=c99 -O1 -fstrength-reduce -fomit-frame-pointer -mtune=68020-60 -c -o timing.o timing.c

...

error: variable or field '_SubTime_re2' declared void
   SubTime(&timeReq.tr_time, &startTime);
   ^
error: variable or field '_SubTime_re' declared void
   SubTime(&timeReq.tr_time, &startTime);
   ^
```

This code was compiling and working fine before, and I can't see how it's anything other than a change to the compiler, or to the ndk1.3 includes.

**Comment by darrenfreeman** [comment]
I restored a backup of my `amiga-gcc` repo and installation, and just did a git pull on `gcc`, and `make install`. This compiles as expected.

**Comment by darrenfreeman** [comment]
The minimal git pull that triggers this bug, is a git pull on `NDK_3.9`.

**Comment by darrenfreeman** [comment]
NDK_3.9 commit ce57d355fc39d128c99da30855dbb8d67665a70b is the last one that works.

ebed8dfa395dd19769ddd7e77ef9a1cfe4cd2c86 (the next commit) breaks my code.


Bisected by repeatedly restoring from a working backup, and then `git pull` / `checkout` on `NDK_3.9`, then `make all`.

**Comment by bebbo** [comment]
could you attach the source or at least a partial source?

**Comment by darrenfreeman** [comment]
This should be sufficient:

```
#include <stdio.h>
#include <proto/exec.h>
#include <proto/timer.h>

struct Device *TimerBase;
struct timerequest timeReq;
static struct timeval startTime;

void fail()
{
  SubTime(&timeReq.tr_time, &startTime);
}
```

**Comment by darrenfreeman** [comment]
ce57d355fc39d128c99da30855dbb8d67665a70b is not working if I check it out on a pristine repo, and I haven't found an earlier commit that works. Seems like it can't download the NDK archive.

I have been able to confirm this commit is the latest that works, starting from a good backup that was checked out on June 30th.

**Comment by bebbo** [comment]
thank you for reporting. The fix is in the build queue
