### ISSUE TITLE
Cannot compile on MacOS

### ISSUE THREAD

**Issue by hitman-codehq** [bebbo/amiga-gcc#247]
After a recent pull request I found that I was no longer able to compile on MacOS.  I get the following:

extract ndk13...failed
/* Timer support functions in amiga.lib (V36 and higher only) */
/*  Commodities functions in amiga.lib (V36 and higher only) */
/*  in V36.  These functions would work with compatibly-implemented */
sed: RE error: illegal byte sequence
/*--- functions in V36 or higher (Release 2.0) ---*/
sed: RE error: illegal byte sequence
sed: 1: "/opt/amiga/m68k-amigaos ...": command a expects \ followed by text
sed: 1: "/opt/amiga/m68k-amigaos ...": command a expects \ followed by text
sed: 1: "/opt/amiga/m68k-amigaos ...": command a expects \ followed by text

Some investigation tracked this down to commit 99f6fb690910033dac08b9a28bb5ffb795ddcd49 which is a fix for #242.  Reverting this fix works but would of course break #242.

Another fix is in the attached patch.  On line 754 of Makefile, instead of grepping for V36 and performing two different sed updates depending on whether it is present, remove the "if grep V36" check and perform the same sed filter regardless.  It seems that by only doing the removal of __stdargs in the else statement, some characters are left in the stream and it doesn't work.

I was going to submit a pull request with (perhaps) a better solution but unfortunately I never used sed before and no matter how much I read about sed I cannot figure out what the '/#ifndef[[:space:]]*CLIB/,/V36/p' command does!  So I'll just report the problem here.

Of course, if you have a better solution for the problem then I'm happy to test it on MacOS.

[sed_fix.patch.txt](https://github.com/bebbo/amiga-gcc/files/7355394/sed_fix.patch.txt)

**Comment by bebbo** [comment]
```
patch -N Makefile provided.patch
patching file Makefile
Hunk #1 FAILED at 751.
1 out of 1 hunk FAILED -- saving rejects to file Makefile.rej
```

**Comment by hitman-codehq** [comment]
Perhaps you have some changes in your devel1 branch?  I have recreated this fix as a pull request instead.

Do you think the solution is correct?

**Comment by bebbo** [comment]
I pushed a change - could you test it, please?

**Comment by hitman-codehq** [comment]
Hi @bebbo, I have been travelling and was unable to work on this until I returned home to my PC.

I tried the workaround with LC_CTYPE but it didn't work.  Some googling brings up lots of people having similar problems on macOS.  Also, there are some other compatibility problems with the BSD sed that would need to be worked around.

In the end the only way was to switch to use GNU sed on macOS.  I've made another pull request with this change.  I tested on Linux and macOS and the header files (including those in ndk13-include) are identical on both systems with the patch.  When applying my patch to the Linux version, it also generates identical header files.

**Comment by bebbo** [comment]
merged the pull request

**Comment by hitman-codehq** [comment]
Thanks @bebbo, I'm happy to make a little contribution to your super Amiga compiler.  :-)

**Comment by bebbo** [comment]
Thanks @hitman-codehq, the macOS users can rejoice again.
