### ISSUE TITLE
amiga-gcc 6.5.0 fails on pointer to typedef

### ISSUE THREAD

**Issue by johnhce** [bebbo/amiga-gcc#254]
```
struct OOGAObject
{
   ClassNode         *pClass;
   struct TagItem    *aTags;              // holds attr/value pairs
};
typedef struct OOGAObject OOGAObject;

struct OOGAWindow
{
   OOGAObject  OOGAObject;    // An OOGAWindow is an OOGAObject
   OOGAObject *pCurrOO;       // current object		<-- ERROR OCCURS HERE -----------------

   struct MUIS_Listtree_TreeNode *pTN;    // GUI treenode root of this window
};
typedef struct OOGAWindow  OOGAWindow;
```
The code compiles if I change line 11 to:
struct OOGAObject *pCurrOO;

**Comment by bebbo** [comment]
looks like the compiler is right and you fixed your problem already.

In C you write it without `struct` if the type is a `typedef` for a `struct`, otherwise the `struct` is mandatory.

**Comment by bebbo** [comment]
the typedef needs a different name than the struct

**Comment by bebbo** [comment]
sorry for the wrong guesses...
... where is the problem exactly? The code compiles:

https://franke.ms/cex/z/Gse4Mz

**Comment by johnhce** [comment]
I get an error: Type 'OOGAObject' could not be resolved.
It seems like an object declared whose type is a typedef is OK but a pointer to the typedef is not.

**Comment by bebbo** [comment]
do you use the current version? what's the output of
```m68-amigaos-gcc -v
...
gcc version 6.5.0b 211101102139 (GCC) 
```

**Comment by johnhce** [comment]
:~/amigadev/amiga-gcc/bin$ ./m68k-amigaos-gcc -v
Using built-in specs.
COLLECT_GCC=./m68k-amigaos-gcc
COLLECT_LTO_WRAPPER=/home/john/amigadev/amiga-gcc/libexec/gcc/m68k-amigaos/6.5.0b/lto-wrapper
Target: m68k-amigaos
Configured with: /home/bebbo/amiga/amiga-gcc/projects/gcc/configure --prefix=/opt/amiga --target=m68k-amigaos --enable-languages=c,c++,objc --enable-version-specific-runtime-libs --disable-libssp --disable-nls --with-headers=/home/bebbo/amiga/amiga-gcc/projects/newlib-cygwin/newlib/libc/sys/amigaos/include/ --disable-shared --enable-threads=no --with-stage1-ldflags='-dynamic-libgcc -dynamic-libstdc++' --with-boot-ldflags='-dynamic-libgcc -dynamic-libstdc++'
Thread model: single
gcc version 6.5.0b 210929093931 (GCC)

**Comment by bebbo** [comment]
please try a more recent version and if the problem persists provide some code which does not compile on https://franke.ms/cex/
