### ISSUE TITLE
Add AmiSSL to supported SDKs

### ISSUE THREAD

**Issue by coldacid** [bebbo/amiga-gcc#255]
Could we have AmiSSL added to the SDKs that can be installed with the system provided by this project? Thanks.

**Comment by bebbo** [comment]
as long there is no free TCP/IP stack available that works with AmiSSL: no.

**Comment by polluks** [comment]
Well, there is the [Roadshow demo](http://roadshow.apc-tcp.de/download-en.php).
For developing we just need an SDK and we have it.

**Comment by bebbo** [comment]
won't fix
