### ISSUE TITLE
Building on Solaris 11.4/SPARC gcc driver invokes cc1 with bad arguments

### ISSUE THREAD

**Issue by nbriggs** [bebbo/amiga-gcc#257]
The `/opt/amiga/bin/m68k-amigaos-gcc` driver is attempting to invoke `/opt/amiga/libexec/gcc/m68k-amigaos/6.5.0b/cc1` with an incorrect set of arguments -- it first shows up when it is trying to cross-compile the "newlib" code, where it does (command and "truss" output):
```
% m68k-amigaos-gcc  -fbaserel -I/export/home/briggs/amiga-gcc/build-SunOS/newlib/libb/newlib/targ-include -I/export/home/briggs/amiga-gcc/projects/newlib-cygwin/newlib/libc/include -DPACKAGE_NAME=\"newlib\" -DPACKAGE_TARNAME=\"newlib\" -DPACKAGE_VERSION=\"3.0.0\" -DPACKAGE_STRING=\"newlib\ 3.0.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -I. -I/export/home/briggs/amiga-gcc/projects/newlib-cygwin/newlib/libc/argz -DCOMPACT_CTYPE -DSIGNAL_PROVIDED -fno-builtin      -fbaserel -c -o lib_a-dummy.o /export/home/briggs/amiga-gcc/projects/newlib-cygwin/newlib/libc/argz/dummy.c
cc1: fatal error: PACKAGE_NAME="newlib": No such file or directory
compilation terminated.
```

```
19240/1:        execve("/opt/amiga/libexec/gcc/m68k-amigaos/6.5.0b/cc1", 0x1001FE798, 0x1001FE0C8)  argc = 40
19240/1:         argv: /opt/amiga/libexec/gcc/m68k-amigaos/6.5.0b/cc1 -quiet -I
19240/1:          /export/home/briggs/amiga-gcc/build-SunOS/newlib/libb/newlib/targ-include
19240/1:          -I
19240/1:          /export/home/briggs/amiga-gcc/projects/newlib-cygwin/newlib/libc/include
19240/1:          -I . -I
19240/1:          /export/home/briggs/amiga-gcc/projects/newlib-cygwin/newlib/libc/argz
19240/1:          -imultilib libb -isystem -D PACKAGE_NAME="newlib" -D
19240/1:          PACKAGE_TARNAME="newlib" -D PACKAGE_VERSION="3.0.0" -D
19240/1:          PACKAGE_STRING="newlib 3.0.0" -D PACKAGE_BUGREPORT="" -D
19240/1:          PACKAGE_URL="" -D COMPACT_CTYPE -D SIGNAL_PROVIDED
19240/1:          /export/home/briggs/amiga-gcc/projects/newlib-cygwin/newlib/libc/argz/dummy.c
19240/1:          -quiet -dumpbase dummy.c -mcpu=68000 -auxbase-strip
19240/1:          lib_a-dummy.o -fno-builtin -fbaserel -o /var/tmp//ccvtbgkb.s
19240/1:         envp:
19240/1:          COLLECT_GCC_OPTIONS='-I' '/export/home/briggs/amiga-gcc/build-SunOS/newlib/libb/newlib/targ-include' '-I' '/export/home/briggs/amiga-gcc/projects/n
ewlib-cygwin/newlib/libc/include' '-D' 'PACKAGE_NAME="newlib"' '-D' 'PACKAGE_TARNAME="newlib"' '-D' 'PACKAGE_VERSION="3.0.0"' '-D' 'PACKAGE_STRING="newlib 3.0.0"' '-
D' 'PACKAGE_BUGREPORT=""' '-D' 'PACKAGE_URL=""' '-I' '.' '-I' '/export/home/briggs/amiga-gcc/projects/newlib-cygwin/newlib/libc/argz' '-D' 'COMPACT_CTYPE' '-D' 'SIGN
AL_PROVIDED' '-fno-builtin' '-fbaserel' '-c' '-o' 'lib_a-dummy.o' '-mcpu=68000'
19240/1:          COLLECT_GCC=m68k-amigaos-gcc _=/usr/bin/truss SAVEHIST=1000
```
where the problem is the `-isystem` is not being passed a directory argument, so it eats the next `-D` argument as the directory and then fails because `PACKAGE_NAME="newlib"` isn't a file.

Any guesses why this is happening?

**Comment by bebbo** [comment]
Wow, Solaris!

**Comment by bebbo** [comment]
maybe https://github.com/bebbo/gcc/blob/gcc-6-branch/libiberty/make-relative-prefix.c needs an adjustment for Solaris.

**Comment by bebbo** [comment]
or this one? https://github.com/bebbo/gcc/blob/gcc-6-branch/libiberty/lrealpath.c

well - only guessing...

**Comment by nbriggs** [comment]
Thanks... I will check and write back.  I've built (non cross-compiling) gcc versions 5, 7, 9, 10, and 11 on this system all without having to make any code adjustments, so I'll be pretty surprised if this breaks in that area, unless it's cross-compiling configuration related.

**Comment by bebbo** [comment]
I guess it's related to my change to lookup the prefix based on the executable location.

**Comment by nbriggs** [comment]
Ah, OK, makes sense then.  It looks as though you depend on `/proc/self/exe` -- which isn't available on Solaris 11, though it does have `/proc/self/execname` which can be read as a text file with the full path of the executable.

**Comment by nbriggs** [comment]
Ah, there's also `/proc/self/path/a.out` which is a symlink to the executable name, which matches up with your `./libiberty/make-relative-prefix.c:  n = readlink( "/proc/self/exe", buf, 1023);` usage... which is where I'm just going looking at the code now.

**Comment by nbriggs** [comment]
Yeah, it should probably be more forthcoming about a -1 return from readlink instead of just returning NULL -- at that point nothing good can happen.   It's not exactly obvious how to identify from the gcc preloaded defines that this is a newish solaris box.   We have
```
% gcc -dM -E - < /dev/null | ggrep -i -e svr -e sun -e solar      
#define __sun 1
#define __SVR4 1
#define sun 1
#define __svr4__ 1
#define __sun__ 1
```
So perhaps after the `#elif defined(__MACH__)` it should check `#elif defined(__sun__) && defined(__svr4__)` and use the alternative path to the link.

I'll test that out.

**Comment by nbriggs** [comment]
OK -- I went for this minimal change and I'm at least able to compile a simple program:
```
% git diff 
diff --git a/libiberty/make-relative-prefix.c b/libiberty/make-relative-prefix.c
index 6bd152616..393f889b1 100644
--- a/libiberty/make-relative-prefix.c
+++ b/libiberty/make-relative-prefix.c
@@ -246,6 +246,8 @@ make_relative_prefix_1 (const char *progname, const char *bin_prefix,
 #elif defined(__MACH__)
   n = 1022;
   n |= _NSGetExecutablePath(buf, &n);
+#elif defined(__SVR4)
+  n = readlink( "/proc/self/path/a.out", buf, 1023);
 #else
   n = readlink( "/proc/self/exe", buf, 1023);
 #endif
```
I notice that in `projects/binutils/gdb/testsuite/gdb.base/sym-file-loader.c` it uses:

```
#ifdef __linux__
# define SELF_LINK "/proc/self/exe"
#elif defined NETBSD
# define SELF_LINK "/proc/curproc/exe"
#elif defined __OpenBSD__ || defined __FreeBSD__ || defined __DragonFly__
# define SELF_LINK "/proc/curproc/file"
#elif defined SunOS
# define SELF_LINK "/proc/self/path/a.out"
#endif
```
though SunOS is not normally predefined by any of the compilers that I'm aware of... must be an explicitly `-D`'d symbol.
