### ISSUE TITLE
[Solaris 11.4] fd2sfd configuration fails, leading to install failure

### ISSUE THREAD

**Issue by nbriggs** [bebbo/amiga-gcc#258]
```
% make fd2sfd                   
configure fd2sfd...
configure fd2sfd...done
make fd2sfd...
make fd2sfd...done
install fd2sfd...
install fd2sfd...failed
make[1]: Entering directory '/export/home/briggs/amiga-gcc/build-SunOS/fd2sfd'
/usr/gnu/bin/install -c -d /opt/amiga/bin /opt/amiga/share/fd2sfd
# Install tools
/usr/gnu/bin/install -c -s fd2sfd /opt/amiga/bin
/usr/gnu/bin/install -c cross/bin/gg-fix-includes /opt/amiga/bin
install: cannot stat 'cross/bin/gg-fix-includes': No such file or directory
make[1]: *** [Makefile:44: install] Error 1
install fd2sfd...failed
use less "log/install fd2sfd.log" to view the full log and search for ***
make: *** [Makefile:486: /opt/amiga/bin/fd2sfd] Error 2
```
which likely stems from (contents of `configure fd2sfd.log`):
```
creating cache ./config.cache
checking host system type... sparc-sun-solaris2.11
checking target system type... m68k-unknown-amigaos
checking build system type... sparc-sun-solaris2.11
checking whether make sets ${MAKE}... yes
checking for gcc... gcc
checking for gcc... (cached) gcc
checking whether the C compiler (gcc -Os ) works... yes
checking whether the C compiler (gcc -Os ) is a cross-compiler... no
checking whether we are using GNU C... yes
checking whether gcc accepts -g... yes
checking for a BSD compatible install... /usr/gnu/bin/install -c
updating cache ./config.cache
creating ./config.status
creating Makefile
creating fd2sfd.readme
creating gg-fd2sfd.spec
mkdir: cannot create directory 'cross/bin': No such file or directory
creating cross/bin/gg-fix-includes
./config.status: line 170: cross/bin/gg-fix-includes: cannot create [No such file or directory]
```

**Comment by bebbo** [comment]
please report this here: https://github.com/cahirwpz/fd2sfd

**Comment by bebbo** [comment]
guess:
```
$(INSTALL_SCRIPT) cross/bin/gg-fix-includes $(bindir) 
```
should be
```
$(INSTALL_SCRIPT) $(srcdir)/cross/bin/gg-fix-includes $(bindir) 
```

**Comment by isoriano1968** [comment]
@nbriggs this one compiles now fine on Solaris 11.4.42 CBE

But it would be great if you could share the configs you did to build on Solaris.

**Comment by nbriggs** [comment]
@isoriano1968 - hmm, I updated to the latest amiga-gcc (master, f10c22508fda50d36015f26b5cb3d825de0377fa) and things fail in different ways -- binutils/gdbsupport/agent.o won't build (../gnulib/config.h:1693:72: error: ‘malloc’ attribute argument 1 is ambiguous) and fd2sfd still doesn't install (bebbo's guess about the fix is not right, and cahirwpz hasn't fixed it).

**Comment by isoriano1968** [comment]
Yo

> @isoriano1968 - hmm, I updated to the latest amiga-gcc (master, [f10c225](https://github.com/bebbo/amiga-gcc/commit/f10c22508fda50d36015f26b5cb3d825de0377fa)) and things fail in different ways -- binutils/gdbsupport/agent.o won't build (../gnulib/config.h:1693:72: error: ‘malloc’ attribute argument 1 is ambiguous) and fd2sfd still doesn't install (bebbo's guess about the fix is not right, and cahirwpz hasn't fixed it).

You are right, I was mislead by the circumstance that fd2sfd is in /opt/amiga/bin .. in gdb I do get the same error as you.

Btw. did you had to change aout-amiga.c as well due to the "extern PTR" declaration? That was failing first.

**Comment by nbriggs** [comment]
Yes, I did have to change the "extern PTR" declaration to get to the point that other things failed.
I'm starting again from a completely clean repo (and sub projects) and doing "make min" instead of "make all" to see how far it gets.

**Comment by isoriano1968** [comment]
Sounds good, Bebbo has also a more "recent" gcc cc in the works ..but I think we would have to update our pre-installed gcc toolchain first.

**Comment by nbriggs** [comment]
The Solaris system I'm using has gcc 12.2.0 installed (along with 7.5.0, 9.3.0, 10.3.0, and 11.2.0).   I'm told by an Oracle dude that they plan (but do not yet have a schedule for) another Solaris 11.4 CBE release, since 11.4.42 CBE is getting pretty long in the tooth now.  It's a bit of a pain to build more recent versions of open source software in their "userland" checked out from git, so a precompiled set of packages would be very welcome.

**Comment by nbriggs** [comment]
@isoriano1968 - "make min" in a pristine  repo (and sub project repos) seems to be OK.  I'll open another issue for the oddities I noticed.
