### ISSUE TITLE
Duplicate Node and List  structs  

### ISSUE THREAD

**Issue by arczi84** [bebbo/amiga-gcc#259]
I have encountered few times when those structs names conflicted with compiled source code structs.
Should they be changed to for example to NodeA and ListA or is there better solution?

**Comment by bebbo** [comment]
do you mean the exec stuff?

**Comment by arczi84** [comment]
yes

**Comment by bebbo** [comment]
I usually work around using def/undef around the amiga headers, like
```
#define Node __AmigaNode
#include <exec/types.h>
#undef
```

**Comment by arczi84** [comment]
Thanks, I will use it.
