### ISSUE TITLE
How to tell compiler to load in CHIP ram?

### ISSUE THREAD

**Issue by coppersoft** [bebbo/amiga-gcc#266]
Hello all,

probably not an issue but a question. I've used vbcc a lot to cross-dev in C for Amiga, and I'd love to try g++ too.
In vbcc there is "__chip" directive that tells the compiler to load that particular variable (for example an array, often used to define copperlists) in CHIP ram.

What is the equivalent with amiga-gcc?

Thank you in advance.

Lorenzo

**Comment by bebbo** [comment]
it's `__chip`

**Comment by coppersoft** [comment]
Thank you!

So it's the same as vbcc?

Something like this is legal?

`UWORD __chip copperlist[] = {`

**Comment by bebbo** [comment]
> UWORD __chip copperlist[] = {

yes, this create asm code like:
```
        .globl  _copperlist
        .section .datachip
        .align  2
_copperlist:
...
```
and the given data ends up in the chip data segment.
