### ISSUE TITLE
sdk-p96 download error

### ISSUE THREAD

**Issue by githubaf** [bebbo/amiga-gcc#282]
Seems Icomp has changed something?
First wget complained about the self signed certificate. After telling wget to accept that certificate I get the "Not Found" error.

wget https://wiki.icomp.de/w/images/e/e9/Develop.lha -O download/Develop.lha
--2022-05-30 08:39:25--  https://wiki.icomp.de/w/images/e/e9/Develop.lha
Resolving wiki.icomp.de (wiki.icomp.de)... 81.95.0.34
Connecting to wiki.icomp.de (wiki.icomp.de)|81.95.0.34|:443... connected.
WARNING: cannot verify wiki.icomp.de's certificate, issued by ‘CN=81.95.0.34,O=81.95.0.34,C=DE’:
  Self-signed certificate encountered.
    WARNING: certificate common name ‘81.95.0.34’ doesn't match requested host name ‘wiki.icomp.de’.
HTTP request sent, awaiting response... 404 Not Found
2022-05-30 08:39:25 ERROR 404: Not Found.

**Comment by bebbo** [comment]
it's `http` not `https`
http://wiki.icomp.de/w/images/e/e9/Develop.lha

**Comment by githubaf** [comment]
Seems it was my mistake then. (I patched somthing to do https and this was a side effect.)
Sorry for confusion!

**Comment by bebbo** [comment]
> Hm, you changed `git clone ${a[1]}:${a[2]} || (rm -rf $file; exit 1)` to `git clone https:${a[2]} || (rm -rf $file; exit 1)`
> 
> So all "git" and "http" from sdk/xxx.sdk become "https" now. That seems to cause the trouble with icomp.

uhm? Archive files aren't cloned with git, these are downloaded with wget.

**Comment by githubaf** [comment]
Hm, I mixed something up on my side. Sorry for confusion!
