### ISSUE TITLE
Compiling using MUI 3.8 SDK issues

### ISSUE THREAD

**Issue by walkero-gr** [bebbo/amiga-gcc#283]
Today I set up an environment using the current repo code (not a release one) which I build just fine under Linux.
I am trying to compile one of my programs, which uses MUI, and with the MUI 3.8 SDK I get the following errors. This does not happen with late MUI 5.0 SDK. 

Is this logical or should I change something?

```
In file included from /opt/sdk/MUI_3.8/C/Include/proto/muimaster.h:6:0,
                 from src/funcs.c:40:
/opt/sdk/MUI_3.8/C/Include/inline/muimaster.h: In function 'MUI_AslRequest':
/opt/sdk/MUI_3.8/C/Include/inline/muimaster.h:55:19: warning: missing terminating " character
   __asm volatile ("
                   ^
/opt/sdk/MUI_3.8/C/Include/inline/muimaster.h:55:19: error: missing terminating " character
/opt/sdk/MUI_3.8/C/Include/inline/muimaster.h:56:3: error: expected string literal before 'jsr'
   jsr a6@(-0x36)"
   ^~~
/opt/sdk/MUI_3.8/C/Include/inline/muimaster.h:56:9: error: stray '@' in program
   jsr a6@(-0x36)"
         ^
/opt/sdk/MUI_3.8/C/Include/inline/muimaster.h:56:17: warning: missing terminating " character
   jsr a6@(-0x36)"
                 ^
/opt/sdk/MUI_3.8/C/Include/inline/muimaster.h:56:17: error: missing terminating " character
In file included from /opt/sdk/MUI_3.8/C/Include/proto/muimaster.h:6:0,
                 from src/funcs.c:40:
/opt/sdk/MUI_3.8/C/Include/inline/muimaster.h: In function 'MUI_CreateCustomClass':
/opt/sdk/MUI_3.8/C/Include/inline/muimaster.h:83:19: warning: missing terminating " character
   __asm volatile ("
                   ^
/opt/sdk/MUI_3.8/C/Include/inline/muimaster.h:83:19: error: missing terminating " character
/opt/sdk/MUI_3.8/C/Include/inline/muimaster.h:84:3: error: expected string literal before 'jsr'
   jsr a6@(-0x6c)"
   ^~~
/opt/sdk/MUI_3.8/C/Include/inline/muimaster.h:84:9: error: stray '@' in program
   jsr a6@(-0x6c)"
         ^
/opt/sdk/MUI_3.8/C/Include/inline/muimaster.h:84:17: warning: missing terminating " character
   jsr a6@(-0x6c)"
                 ^
/opt/sdk/MUI_3.8/C/Include/inline/muimaster.h:84:17: error: missing terminating " character
```

This is the code the inline/muimaster.h has in the complaining methods
```
  __asm volatile ("
  jsr a6@(-0x36)"
  : "=r" (res)
  : "r" (a6), "r" (a0), "r" (a1)
  : "d0", "d1", "a0", "a1" );
```
Thank you for your help.

**Comment by bebbo** [comment]
you have to use the proper headers for amiga-gcc. use 
```
make sdk=mui
```
To install the mui lib and headers as needed for amiga-gcc.

AFAIK there are further pitfalls. Have a look into https://github.com/githubaf/3DNature or ask @githubaf directly.
His way to include the headers:
```
#ifdef __GNUC__
    //#include <proto/muimaster_lib.h>   // ALEXANDER: Fehler in GCC-MUI-SDK???
    #include <libraries/mui.h>
    //#warning "GCC MUI-Include problem in Header.h??? "
#else
    #include <proto/muimaster.h>
#endif
```
Also the mui version may cause issues, MUIMASTER_VMIN must be low enough to use your version. I personally use 0...
```
   (MUIMasterBase = OpenLibrary((STRPTR)MUIMASTER_NAME, MUIMASTER_VMIN)
```

**Comment by bebbo** [comment]
ok, try this one:
```
#include <libraries/mui.h>
#define NO_INLINE_STDARG
#define NO_INLINE_VARARGS
#include <proto/muimaster.h>
```

**Comment by walkero-gr** [comment]
@bebbo 
Thank you so much for your help and replies. Unfortunately, none of the above helped. 
Checking the MUI 3.8 examples, most of them are using the following includes

```
#include <libraries/mui.h>

#ifndef __GNUC__
#include <clib/muimaster_protos.h>
#else
#include <inline/muimaster.h>
#endif
```

and the `proto/muimaster.h` also includes the `inline/muimaster.h` when there is GNUC defined. But this file is the one that has the issues I mentioned above.
So, I assume that with gcc we should include those files.

Is the GCC 6 known to be able to compile the MUI 3.8 example code?

**Comment by bebbo** [comment]
I am pretty sure that the example won't compile out of the box with amiga-gcc.
You have to fix the includes.

For the attached example - grabbed from https://github.com/emartisoft/AmigaOS3.X-MUI-Examples - then modified, this
```
m68k-amigaos-gcc -Os -noixemul mui02.c -o mui02 -lmui
``` 
creates a working program.
[02_Button.zip](https://github.com/bebbo/amiga-gcc/files/8924910/02_Button.zip)
