### ISSUE TITLE
clobber conflict (AmiTCP netinclude inlines)

### ISSUE THREAD

**Issue by neuweiler** [bebbo/amiga-gcc#284]
I'm trying to compile the Genesis (AmiTCP) source with amiga-gcc. It works with SASC as it uses pragma's but on GNU is uses inline includes from AmiTCP's netinclude. I get the following errors for almost all inline functions:

```../../netinclude/inline/socket.h: In function 'CloseSocket':
../../netinclude/inline/socket.h:39:2: error: asm clobber conflict with output operand
  __asm __volatile ("jsr a6@(-0x78)"
  ^~~~~
```
the respective code:
```
extern __inline LONG
CloseSocket (BASE_PAR_DECL LONG d)
{
	BASE_EXT_DECL
	register res __asm("d0");
	register struct Library *a6 __asm("a6") = BASE_NAME;
	register LONG d0 __asm("d0") = d;
	__asm __volatile ("jsr a6@(-0x78)"
	: "=r" (res)
	: "r" (a6), "r" (d0)
	: "d0", "d1", "a0", "a1");
	return res;
}

```

I read on [stackoverflow](https://stackoverflow.com/questions/26942064/how-do-i-tell-gcc-asm-that-an-input-register-is-clobbered) that GNU doesn't like the usage of an input register as an output register. But I'm at a loss here on what to change in the code so it works with SASC and GNU.

**Comment by bebbo** [comment]
> Genesis (AmiTCP) source

is that available somewhere? Then I could look into it...

**Comment by neuweiler** [comment]
Yes, it's here http://aminet.net/comm/tcp/AmiTCP-SDK-4.3.lha under netinclude/inline.
