### ISSUE TITLE
NDK3.2 R4 not supported

### ISSUE THREAD

**Issue by christoph-fassbach** [bebbo/amiga-gcc#285]
Hi!

NDK3.2R3 was removed from aminet and R4 was uploaded.
A clean/fresh installation fails therefore.

Cheers,

Christoph

**Comment by christoph-fassbach** [comment]
See https://github.com/bebbo/amiga-gcc/pull/286

**Comment by bebbo** [comment]
the provided patch does not pass the build-test:
```
patch ndk...
patch ndk...failed
patching file /home/appveyor/projects/amiga-gcc/projects/NDK_3.9/Include/fd/expansion_lib.fd
Hunk #1 FAILED at 3.
patch: **** Can't reopen file /home/appveyor/projects/amiga-gcc/projects/NDK_3.9/Include/fd/expansion_lib.fd : No such file or directory
patch ndk...failed
use less "log/patch ndk.log" to view the full log and search for ***
install fd2sfd...Makefile:717: recipe for target '/home/appveyor/projects/amiga-gcc/projects/NDK_3.9/Include.info' failed
make: *** [/home/ap
```

**Comment by christoph-fassbach** [comment]
yep, as stated in the PR; 
NDK 3.9 broken but 3.2 fixed.

3.9 extracts a folder, 
3.2 needs to be extracted into a folder. 

I was a bit surprised it was already merged as is, I am not fully done yet. 

I am sorry if that now caused any trouble, gimme another few hours.

**Comment by christoph-fassbach** [comment]
See #287 here and https://github.com/bebbo/clib2/pull/1 please.
These should do the job, I hope.

I should have communicated more clearly before, I am too much used of code reviews, 
distrusting everybody and stuff ... 

:)

**Comment by bebbo** [comment]
guess this is fixed.
