### ISSUE TITLE
The make update failure

### ISSUE THREAD

**Issue by toptan** [bebbo/amiga-gcc#290]
Using latest master as of July 5th.

Trying to build tool chain in Fedora 36 docker. The error is:

`NDK_3.9/Tutorials/Printer/English/Drivers.doc	- Melting  :  ...
NDK_3.9/Tutorials/Printer/English/Drivers.doc	- Melting  :  ooo
NDK_3.9/Tutorials/Printer/English/Drivers.doc	- Melted  
LHa: Error: iconv_open() failure: Invalid argument

NDK_3.9/Tutorials/Printer/English/Preferences.doc	- Melting  :  .
NDK_3.9/Tutorials/Printer/English/Preferences.doc	- Melting  :  o
NDK_3.9/Tutorials/Printer/English/Preferences.doc	- Melted  
unpack ndk...failed
use less "log/unpack ndk.log" to view the full log and search for ***
make[1]: *** [Makefile:717: /root/amiga-gcc/projects/NDK_3.9/Include.info] Error 1
make[1]: Leaving directory '/root/amiga-gcc'
make: *** [Makefile:306: update-ndk] Error 2
`
Last lines from "log/unpack ndk.log" are:
`NDK_3.9/Tutorials/ARexx/Host/Hosts_and_Clients.doc      - Melting  :  .
NDK_3.9/Tutorials/ARexx/Host/Hosts_and_Clients.doc      - Melting  :  o
NDK_3.9/Tutorials/ARexx/Host/Hosts_and_Clients.doc      - Melted  
LHa: Error: iconv_open() failure: Invalid argument

NDK_3.9/Tutorials/ARexx/Host/RexxShell  - Melting  :  .
NDK_3.9/Tutorials/ARexx/Host/RexxShell  - Melting  :  o
NDK_3.9/Tutorials/ARexx/Host/RexxShell  - Melted  
LHa: Error: iconv_open() failure: Invalid argument

NDK_3.9/Tutorials/ARexx/Host/RexxShell.c        - Melting  :  .
NDK_3.9/Tutorials/ARexx/Host/RexxShell.c        - Melting  :  o
NDK_3.9/Tutorials/ARexx/Host/RexxShell.c        - Melted  
LHa: Error: iconv_open() failure: Invalid argument

NDK_3.9/Tutorials/Printer/Deutsch/Applikationen.dok     - Melting  :  ...
NDK_3.9/Tutorials/Printer/Deutsch/Applikationen.dok     - Melting  :  ooo
NDK_3.9/Tutorials/Printer/Deutsch/Applikationen.dok     - Melted  
LHa: Error: iconv_open() failure: Invalid argument

NDK_3.9/Tutorials/Printer/Deutsch/Preferences.dok       - Melting  :  .
NDK_3.9/Tutorials/Printer/Deutsch/Preferences.dok       - Melting  :  o
NDK_3.9/Tutorials/Printer/Deutsch/Preferences.dok       - Melted  
LHa: Error: iconv_open() failure: Invalid argument

NDK_3.9/Tutorials/Printer/Deutsch/Treiber.dok   - Melting  :  ...
NDK_3.9/Tutorials/Printer/Deutsch/Treiber.dok   - Melting  :  ooo
NDK_3.9/Tutorials/Printer/Deutsch/Treiber.dok   - Melted  
LHa: Error: iconv_open() failure: Invalid argument

NDK_3.9/Tutorials/Printer/English/Applications.doc      - Melting  :  ...
NDK_3.9/Tutorials/Printer/English/Applications.doc      - Melting  :  ooo
NDK_3.9/Tutorials/Printer/English/Applications.doc      - Melted  
LHa: Error: iconv_open() failure: Invalid argument

NDK_3.9/Tutorials/Printer/English/Drivers.doc   - Melting  :  ...
NDK_3.9/Tutorials/Printer/English/Drivers.doc   - Melting  :  ooo
NDK_3.9/Tutorials/Printer/English/Drivers.doc   - Melted  
LHa: Error: iconv_open() failure: Invalid argument

NDK_3.9/Tutorials/Printer/English/Preferences.doc       - Melting  :  .
NDK_3.9/Tutorials/Printer/English/Preferences.doc       - Melting  :  o
NDK_3.9/Tutorials/Printer/English/Preferences.doc       - Melted  
(END)
`

**Comment by toptan** [comment]
Important info docker container is from fedora:latest

**Comment by toptan** [comment]
Additional info on fedora:35 after dnf install findutils all is good. I suggest amending README at least for Fedora versions less than 36. Working on figuring out Fedora 36

**Comment by bebbo** [comment]
I removed `lhasa` from the dockerfile.

**Comment by toptan** [comment]
The docker file for my container built from Fedora 36 had a typo. Sorry for false alarm.
