### ISSUE TITLE
Docker container issues - proposals

### ISSUE THREAD

**Issue by walkero-gr** [bebbo/amiga-gcc#291]
I am trying to setup a dev environment based on the Dockerfile in the repo. Unfortunately, when I try to compile even a hello world code, I get the following error

`/opt/amiga/libexec/gcc/m68k-amigaos/6.5.0b/cc1: error while loading shared libraries: libmpc.so.3: cannot open shared object file: No such file or directory`

Also, I would recommend two changes:
- At line 16 to add the number of threads after -j (https://github.com/bebbo/amiga-gcc/blob/master/Dockerfile#L16), i.e. 4, because like that it gets all the cores, and then gets all the memory and and swap memory on systems, until it makes it unusable
- Add `/opt/amiga/bin` in PATH, with something like  `ENV PATH="/opt/amiga/bin:$PATH"` added at the end of the dockerfile

**Comment by bebbo** [comment]
The environment to use the created binaries has to provide all necessary libraries.

**Comment by bebbo** [comment]
bump
