### ISSUE TITLE
-fbaserel and A4 usage

### ISSUE THREAD

**Issue by githubaf** [bebbo/amiga-gcc#296]
Not sure if I am using it incorrectly of if the compiler should care about it...

I am also not sure if I am interpreting the problem correctly...

In WCS I have an assembly function that uses a lot of parameters in explicitely given registers. One of them is A4.
I compile the whole project with -fbaserel.

There is a global variable *WCSScrn pointing to the screen. That variable is completely wrong after a call (via another function) to the assembly function. The program crashes then, of course. I put it into compiler explorer and there I see A4 is changed (because it is a parameter) and later used for access to WCSScrn again - which is now wrong.

http://franke.ms/cex/z/qx383Y

Should the compiler know that A4 has to be saved/restored when -fbaserel is used? Is that my duty to save A4 before calling the assembly function?

Would you have look, please?

**Comment by bebbo** [comment]
There is a reason that the inline macros neither use a4/a5.
But invoking `__restore_a4();` right after that asm call should resolve your problem.

http://franke.ms/cex/z/dGWW8E

**Comment by githubaf** [comment]
Thanks, __restore_a4() solved a part of the problem.
What is special about a5?

**Comment by mheyer32** [comment]
A5 is used by the compiler as frame pointer. It used to completely ignore assignments to A5, regardless of -fomit-frame-pointer.
But it seems, this behavior changed. Compiler explorer shows that it does assign A5

**Comment by githubaf** [comment]
@mheyer32 
Thanks for the reply. I wondered because bebbo wrote "There is a reason that the inline macros neither use a4/a5."
Then I have seen a call to Jsr(a5) that crashed my program. I added a global variabled "unsigned long A5" and did an
```
asm("move.l  A5,_A5");;
AssemblyFunction(REG(a0, void *Plane0), REG(a1, void *Plane1),
 REG(a2, void *Plane2), REG(a3, void *Plane3),
 REG(a4, void *PlaneM), REG(a5, unsigned long int PixCnt),
 REG(a6, void *InPtr));
asm("move.l _A5,A5";
#ifdef __baserel__
   __restore_a4();
#endif
```
and that seemed to help.


But the program still crashed. I investigaed further, added several KPrintF() to show the values of the parameters. I stopped in the assembly function an displayed the registers. They contained nonesense. I added more KPrintF()s an and suddenly it worked without any Enforcer-Hits. Eventually it turned out to be an **optimization issue**.

Please find the new example in the compiler explorer:

http://franke.ms/cex/z/veno3G

When compiled without optimization (second window) the program works. The assembly function gets the correct values in the parameter-registers.
When compiled with -O2 (right window), the registers **A0...A4 contain wrong values**, because first A5 is correcly calclulated (as parameter) but then used a basis for A0...A4.

**Comment by bebbo** [comment]
The `a5` register belongs to the compiler. And with baserel/resident also the `a4` register.
Simply don't use theses registers for parameters.

Also using that many registers for parameters is not smart, since all these registers must be free in the calling functions and may cause overhead by using temp stack variables.

If you need to pass many parameters use the stack or an array. In your assembly method you are free to push/pop any register and use all at will. You can load many registers from the passed stack variable with one `movem`, simply provide these in the correct order.

```
  void * regs[8];
  regs[0] = ...;

  regs[7] = ...;

  asmFunction(regs);
```
with
```
void asmFunction(void ** regs ASM("a0"));
```
and there
```
_asmFunction:
  movem.l a2-a7,-(a7)
  movem.l (a0),a0-a7


  movem.l (a7)+,a2-a7
```

**Comment by githubaf** [comment]
I see. Thanks for the hint how to do it right!
The assembly function was not my code and I tried to avoid touching it ;-)

**Comment by githubaf** [comment]
Thanks for your patience. 
Bebbo:s suggestion works nicely and is so easy and clean.
