### ISSUE TITLE
Profiling with -pg does not work any longer

### ISSUE THREAD

**Issue by githubaf** [bebbo/amiga-gcc#299]
I compile a test program with -pg option. Latest toolchain.
`m68k-amigaos-gcc  -O0 -Wall --pedantic prof_test.c -noixemul -o prof_test -pg`

The program works as usual but does not produce a gmon.out at the end. That worked in the past.
I see no "gcc profiler" vblank interrupt while the program is running.

Profiling works when compiled with with the toolchain from April 20th 2022. Newer toolchains all seem to have the issue.
Is there a new mandatory compiler/linker option or has it degraded?

```
// https://de.wikipedia.org/wiki/Collatz-Problem

#include <stdio.h>

unsigned int Collatz_Step(unsigned int n)
{
    if(n%2==0)
    {
        return n/2;
    }

    return 3*n+1;
}

unsigned int Collatz_Len(unsigned int Number)
{
    unsigned int Value=Number;
    unsigned int Len=1;

    while (1)
    {
        Value=Collatz_Step(Value);
        Len++;
        if(Value==1)
        {
            break;
        }
    }
    return Len;
}


int main(void)
{
    unsigned int i, Len, MaxLen=0;
    for (i=1;i<=30000;i++)
    {
        Len=Collatz_Len(i);
        if(Len>MaxLen)
        {
            MaxLen=Len;
            printf("Collatz seq-len for %u = %u\n",i,Len);
        }
    }
    return 0;
}


```

**Comment by arczi84** [comment]
I think -g is also needed.

**Comment by bebbo** [comment]
I see - since the change is not live yet for all libs, the `gmon.o` is built using the constructors, not the sections...
... fix should be in 42 mins

**Comment by githubaf** [comment]
Yes, it is working again. Thank you!
