### ISSUE TITLE
undefined reference to `exit'

### ISSUE THREAD

**Issue by MBeijer** [bebbo/amiga-gcc#3]
```
Linking milkytracker
obj/m68k-amigaos/Release/milkytracker/CGX_Main.o(.text+0x188c): undefined reference to `exit'
obj/m68k-amigaos/Release/milkytracker/CGX_Main.o(.text+0x1fa2): undefined reference to `exit'
obj/m68k-amigaos/Release/milkytracker/CGX_Main.o(.text+0x20e6): undefined reference to `exit'
../lib/libppui.a(DisplayDeviceFB_SDL.o)(.text+0x25e): undefined reference to `exit'
../lib/libppui.a(DisplayDeviceFB_SDL.o)(.text+0x51a): undefined reference to `exit'
../lib/libppui.a(DisplayDeviceFB_SDL.o)(.text+0x42a): more undefined references to `exit' follow
/opt/m68k-amigaos/m68k-amigaos/libnix/lib/libnix/libnix.a(open.o)(.text+0x3ca): undefined reference to `_WBenchMsg'
/opt/m68k-amigaos/m68k-amigaos/libnix/lib/libnix/libnix.a(open.o)(.text+0x420): undefined reference to `exit'
/opt/m68k-amigaos/m68k-amigaos/libnix/lib/libnix/libnix.a(abort.o)(.text+0x3a): undefined reference to `exit'
/opt/m68k-amigaos/m68k-amigaos/libnix/lib/libnix/libnix.a(raise.o)(.text+0x9c): undefined reference to `exit'
collect2: error: ld returned 1 exit status
milkytracker.make:500: recipe for target '../bin/milkytracker.68k' failed
make[1]: *** [../bin/milkytracker.68k] Error 1
Makefile:48: recipe for target 'milkytracker' failed
make: *** [milkytracker] Error 2
```

**Comment by bebbo** [comment]
just did a
```
make clean clean-prefix
make all -j8
make all-sdk
```

then did a fresh clone from AmigaPorts and found that sdl and libdebug is missing => added libdebug and a sdl.sdk

note: you should rather include "SDL/SDL.h" not "SDL.h" - I added a redirecting include for now.

milkytracker is linked properly.

**Comment by MBeijer** [comment]
libdebug is linked properly in my makefile, nothing has changed there. I
simply git-pulled amiga-gcc, did a make clean and make -j8 and got this
issue after that.
And I'd rather not change SDL.h to SDL/SDL.h since I intend to move this
upstream when I feel it's done. The less superficial changes the better.

Does clean-prefix remove the entire folder /opt/amiga? If so I'd rather not
use that, as I store my global includes and libs in there on the first
level.

**Comment by bebbo** [comment]
Yes, clean-prefix removes the entire folder! Be careful!

I plan to keep the $(PREFIX)/include and $(PREFIX)/lib - but that lib folder is not yet searched...

Try `make clean-libnix` then `make libnix`.

**Comment by MBeijer** [comment]
Oh, my bad. Libnix is failing because I'm working on adding cexpf... duh.

**Comment by bebbo** [comment]
if we had sdk files for all your installed headers and libraries, clean-prefix would'nt be a problem.

**Comment by MBeijer** [comment]
My plan was to eventually push that kind of stuff the amiga-cross-toolchain, but I guess it would be done here instead. :)

Libraries that are rather common that I've sorted out how to compile for Amiga without any fuzz:
- libz
- libz2
- libSDL
- libSDL_image
- libSDL_gfx
- libSDL_mixer
- libSDL_ttf

The end goal is that I want to include pkgconfig support, so it's easier porting software later. 
You basically just need a folder in lib called pkgconfig. Within that folder are files named <library-name>.pc, with the following content:
```
**$ cat /opt/m68k-amigaos/lib/pkgconfig/zlib.pc** 
prefix=/opt/m68k-amigaos
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=/opt/m68k-amigaos/include

Name: zlib
Description: drawing and graphical effects extension for SDL
Version: 1.2.11
Libs: -L${libdir} -lz
Cflags: -I${includedir}/
```
or
```
**$ cat /opt/m68k-amigaos/lib/pkgconfig/SDL_gfx.pc** 
prefix=/opt/m68k-amigaos
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=/opt/m68k-amigaos/include

Name: SDL_gfx
Description: drawing and graphical effects extension for SDL
Version: 2.0.26
Requires: sdl >= 1.2.0
Libs: -L${libdir} -lSDL_gfx
Cflags: -I${includedir}/SDL
```

I'd like to make this toolchain as feature-complete as possible. :)

**Comment by bebbo** [comment]
ok, I will try to use pkgconfig.

And:
```Cflags: -I${includedir}/SDL```

I think this folder is missing in milkytracker's include list.

**Comment by MBeijer** [comment]
No, it should be included with premake4.lua + build_gmake. I use that
almost daily.

**Comment by bebbo** [comment]
it's this one? ```pkg-config```

And I think you should use the ${prefix} in the include dirs.

**Comment by MBeijer** [comment]
huh, now I'm lost?

**Comment by MBeijer** [comment]
The includedir mentioned in the .pc-file is defined further up in the same file. I just lazily didn't add $(prefix) to the includedir define, because it served my purpose.

I am working on getting CMake to properly build MilkyTracker for Amiga. CMake uses pkg-config to find libs amongst other things. Until then, everything is predefined to /opt/m68k-amigaos via the premake build system.
