### ISSUE TITLE
Build errors on cygwin / win10

### ISSUE THREAD

**Issue by tehKaiN** [bebbo/amiga-gcc#30]
Everything was done on fresh copy of repo and clean prefix folder. First of all, config.guess aren't working on cygwin 64bit - I've forgot to copy exact message, but it was the same as [here](https://superuser.com/questions/1082150/cygwin-doesnt-recognize-config-guess-when-installing-haskell-package). Then, after 32-bit reinstall I've had a problem with lha during `make update` - it successfully cloned and built, but `install` didn't have expected result since I've got "lha: command not found" error. After manually doing `install` NDK extracted painlessly. Unfortunately I've stumbled upon other errors - looks like include path is not working properly.

[Dump of console contents](https://github.com/bebbo/amiga-gcc/files/2004752/build.log)

After starting once again with fresh copy of repo on console with admin rights, there was no problem with lha so I guess it's some kind of permissions business.

Also, README is missing cygwin info - I think it could be copied from old repo.

Regarding PATH and PREFIX vars, I'm starting my cmd with shortcut pointing to `C:\WINDOWS\system32\cmd.exe /c "SET PATH=c:/prg/kompilatory/bebbo/bin;c:/prg/kompilatory/cygwin/bin;%PATH%&& set PREFIX=/cygdrive/c/prg/kompilatory/bebbo&& START cmd.exe"`, note that double amptersands don't have space on left side intentionally. Printing prefix is also visible on top of log.

As a side note I'm wondering if it would be possible to build this toolchain in MinGW - it would be easier to integrate with IDEs which don't quite like parsing `/cygdrive` paths in warning/error messages.

**Comment by bebbo** [comment]
please add the git hash of your amiga-gcc version

**Comment by tehKaiN** [comment]
I'm on 97e59baf76de6bef7e9219f4bdc1211550983cce and done `make update` quite recently (2-5hrs ago?).

**Comment by bebbo** [comment]
hm - include path should be fixed in gcc. https://github.com/bebbo/gcc/commit/73ca543cf13340e43fe59f02717bc81fbad0ea09

**Comment by bebbo** [comment]
maybe you have an older version in your search path?

**Comment by tehKaiN** [comment]
Okay, I've checked and I've had windows version of bin directory path in PATH, so I've removed it and still the result is the same. This is on fresh windows install so I don't have any other toolchain versions on HDD.

Can you confirm that you can build it on cygwin with having prefix directory empty and just cloning the repo, calling `make update` and `make all` so that we could definitely say that I have something messed up in my os?

**Comment by bebbo** [comment]
I will test with cygwin64... hang on

**Comment by bebbo** [comment]
I build successfully with cygwin64 on windows 10

**Comment by tehKaiN** [comment]
Everything now works on cygwin32 too - thanks!
