### ISSUE TITLE
Creating self-relocating .library with EH is no longer possible

### ISSUE THREAD

**Issue by Midar** [bebbo/amiga-gcc#300]
Creating a self-relocating .library with EH used to be possible with amiga-gcc, however, these days, it results in the following linker warning:

`.text reloc for __EH_FRAME_BEGINS__ is out of range: 00000000`

That doesn't seem right. Interestingly, there is no such warning for __EH_FRAME_OBJECTS__? So whatever was changed only broke __EH_FRAME_BEGINS__. I haven't managed to track down which change broke this.

**Comment by bebbo** [comment]
so to say: it's more OS4/amiga-ppc compatible atm ;-)

**Comment by Midar** [comment]
Hah, good one! ;) But still a regression unfortunately :(

**Comment by Midar** [comment]
So what changed here? Is there any way to work around it?

**Comment by bebbo** [comment]
... to keep data segments minimal, all const stuff ends up in the .text segment.
no idea without looking at the code...

does your code try to load that via a4? then it will fail.

**Comment by bebbo** [comment]
change
```
extern const void * _EH_FRAME_BEGINS__;
```
into
```
extern const void * const _EH_FRAME_BEGINS__;
```

**Comment by Midar** [comment]
Hmm, that seems to make the warning go away again, but it still fails at
```
        if ((size_t)_EH_FRAME_BEGINS__ != (size_t)_EH_FRAME_OBJECTS__)
                return false;
```
The first one used to be the count, is that no longer the case?

**Comment by bebbo** [comment]
comparing pointers without de-referencing? the pointers *are* different.

And the counters are gone, since the constructors are a relict from the past.
Well, you can create counters using the linker scripts but that raises different problems,

current lib code is:
```
void __init_eh() {
    void ** frame = _EH_FRAME_BEGINS__;
    void ** object = _EH_FRAME_OBJECTS__;
    
    while (*frame) {
      __register_frame_info(*frame++, *object++);
    }
}
```

**Comment by Midar** [comment]
That seems to have worked, thanks. However, I need to change it back to non-const and get a warning, because otherwise I get an immediate crash.

**Comment by Midar** [comment]
Unrelated: Why are there .a files checked into the repository under lib?

**Comment by bebbo** [comment]
> Unrelated: Why are there .a files checked into the repository under lib?

because these aren't build?

**Comment by Midar** [comment]
It seems that there's even more broken in amiga-gcc. It now opens the library but then just hangs. When compiling it without library support, it just says "Program aborted" - that is even if I #define abort to something that prints an error, and it never gets printed. The same code worked with older amiga-gcc and works perfectly fine when compiled for MorphOS using the MorphOS SDK. Is there any way to figure out where this abort call is coming from?

**Comment by bebbo** [comment]
you need something like:

amiga-library.m
```
#ifdef OF_AMIGAOS_M68K
__attribute__((section(".list___CTOR_LIST__")))
const uintptr_t __CTOR_LIST__ = 0;
__attribute__((section(".list___EH_FRAME_BEGINS__")))
const uintptr_t _EH_FRAME_BEGINS__ = 0;
__attribute__((section(".list___EH_FRAME_OBJECTS__")))
uintptr_t _EH_FRAME_OBJECTS__ = 0;
#endif
```
and use it like
```
			for (const uintptr_t *frame = 1 + &_EH_FRAME_BEGINS__;
			    *frame != 0;)
				libc.__deregister_frame_info((const void *)*frame++);
```

plus an end file:
amiga-end.m
```
#ifdef OF_AMIGAOS_M68K
__attribute__((section(".list___CTOR_LIST__")))
long a_random_name1 = 0;
__attribute__((section(".list___EH_FRAME_BEGINS__")))
long a_random_name2 = 0;
__attribute__((section(".list___EH_FRAME_OBJECTS__")))
long a_random_name3 = 0;
#endif
```

**Comment by bebbo** [comment]
I could remove the requirement of an end file. Read here: https://github.com/bebbo/amiga-gcc/wiki/Constructors,-Destructors,-Managed-Lists
