### ISSUE TITLE
simple std::out fail

### ISSUE THREAD

**Issue by krabobmkd** [bebbo/amiga-gcc#302]
Hello, I'm investigating what I can do and port with this compiler, I did a cmake toolchain that works good on linux QtCreator, I'm already happy, great job, C++14 on Amiga at last.Yet I have crash in all config i've tested, as soon as I use std::cout :
```

#include <iostream>
using namespace std;

int main(int argc, char **argv) {
    cout << "hello" << endl;
    return 0;
}
```

... it popup a software failure on the workbench with "error n°80000008" which is documented as: "Privilege violation error, dead end.".
I tried several cpu/fpu options and emulator configuration (os3.9, os3.2, 68030, 68060fpu), with a 130kb stack, and it does the same.
 
Yet the following code works, if it helps: 
```

#include <iostream>
#include <sstream>
#include <stdio.h>
using namespace std;

int main(int argc, char **argv) {
    
    stringstream sout;
    sout << "hello" << endl;
    fprintf(stdout,"%s",sout.str().c_str());

    return 0;
}

```

**Comment by bebbo** [comment]
guess you need to add `-noixemul`?

```
m68k-amigaos-g++ test.cc -noixemul -o test -Os
```
is working for me

**Comment by krabobmkd** [comment]
Ah ! Ok, I guess you can close this one.
