### ISSUE TITLE
Another FPU problem

### ISSUE THREAD

**Issue by githubaf** [bebbo/amiga-gcc#303]
I have another problem with WCS and FPU and have currently no idea how to investigate further :-(

I compiled and linked without -ffastmath and without -flto for all tests. I tested on WinUAE with 68040, other s tested on real machines with 68060.

The compiler and linker command lines look like these:

```
m68k-amigaos-gcc -I/home/developer/Desktop/SelcoGit/3DNature/Amiga -O2 -Wall -c -fmessage-length=0 -funsigned-char -o Fractal.o ../Fractal.c -noixemul -m68020 -m68881 -fomit-frame-pointer -fbaserel -mregparm -Winline -g

m68k-amigaos-gcc  -o "WCS"  ./Fractal.o ./MuchMoreObejctFiles.o  -noixemul -m68020 -m68881 -fomit-frame-pointer -fbaserel -lm -lmui -mregparm  -g -ldebug  -Wl,-Map=WCS.map

```
The wcs program calculated very strange looking mountains.  I have also a 68040 target and that produces correct images. So I tried using the linker call from my 68040 target:

```
m68k-amigaos-gcc  -o "WCS"  ./Fractal.o ./MuchMoreObejctFiles.o  -noixemul -m68040 -fomit-frame-pointer -fbaserel -lm -lmui -mregparm  -g -ldebug  -Wl,-Map=WCS.map

```

The combination "compiled with -m68020 -m68881 and linked with -m68040" worked and the image is OK. 
I looked into the mapfile for the differences and found

-m68020 -m68881
LOAD /home/developer/opt/m68k-amigaos_31Jul22/lib/gcc/m68k-amigaos/6.5.0b/libb/libm020/libm881/libgcc.a

vs.

-m68040
LOAD /home/developer/opt/m68k-amigaos_31Jul22/lib/gcc/m68k-amigaos/6.5.0b/libb/libgcc.a

So my questions:
- Is it correct to compile and to link with only -m68040 if I want an FPU-only version for an Amiga with a full featured 68040, i.e. including FPU?
Or do I need to add -m68881 to the linking call even for 68040 and 68060? 
Shouldn't for 68040 also a libm020/libm881 library be used?
( If I add -m68881 to the linking call I see lib/gcc/m68k-amigaos/6.5.0b/libb/libm020/libm881/libgcc.a as shown above)

*If I add -m68881 to the linking call however, all program versions always produce bad mountains. 

I guess there is in issue in libb/libm020/libm881/libgcc.a ?

*If I use a very old toolchain (27Nov21) to compile and link, the mountains are correct!

Do you have an idea what I could do or what I should test? Are my command lines correct?

**Comment by githubaf** [comment]
I think I found the critical files.
As I wrote the picture is correct when I link with lib/gcc/m68k-amigaos/6.5.0b/libb/libgcc.a instead of libb/libm020/libm881/libgcc.a

So I started exchanging the object files in libb/libm020/libm881 against file object files from lib/gcc/m68k-amigaos/6.5.0b/libb/libgcc.a

The result is: 
If I replace *only* _floatundidf.o and xfpgnulib__floatunsidf.o with the variants from lib/gcc/m68k-amigaos/6.5.0b/libb/libgcc.a, then the picture is ok again. So something must go wrong, when these two files are built during the compilation of the tool chain.

```
rw-r--r-- 0/0    188 Jan  1 00:00 1978 xfpgnulib__floatunsidf.o     OK /home/developer/opt/m68k-amigaos_31Jul22/lib/gcc/m68k-amigaos/6.5.0b/libb/libgcc.a
rw-r--r-- 0/0    180 Jan  1 00:00 1978 xfpgnulib__floatunsidf.o    BAD /home/developer/opt/m68k-amigaos_31Jul22/lib/gcc/m68k-amigaos/6.5.0b/libb/libm020/libm881/libgcc.a

rw-r--r-- 0/0    236 Jan  1 00:00 1978 _floatundidf.o               OK /home/developer/opt/m68k-amigaos_31Jul22/lib/gcc/m68k-amigaos/6.5.0b/libb/libgcc.a
rw-r--r-- 0/0    144 Jan  1 00:00 1978 _floatundidf.o              BAD /home/developer/opt/m68k-amigaos_31Jul22/lib/gcc/m68k-amigaos/6.5.0b/libb/libm020/libm881/libgcc.a
```
Here are the bad and good pictures.

![CanyonSet000_BadRocks_BadSky](https://user-images.githubusercontent.com/28429123/188516371-6274150e-a58d-4817-950e-84d28152ef80.png)
![CanyonSet000_floatundidfunsidf](https://user-images.githubusercontent.com/28429123/188516375-247bee20-3b11-4117-aabc-06c017a9c263.png)

**Comment by bebbo** [comment]
uh oh - the bad versions are returning the value in fp0... since the return type is double and fpu is on...

=> all the libs need some more love...

**Comment by bebbo** [comment]
the real question is: 
 - what is calling that function?
 - why, since with fpu that function should not be used
 - or if it still is used, the caller should expect the return value in fp0 too

**Comment by githubaf** [comment]
I am away until the 16th so I can test or investigate after that date.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: bebbo ***@***.***> Datum: 08.09.22  10:41  (GMT+01:00) An: bebbo/amiga-gcc ***@***.***> Cc: githubaf ***@***.***>, Author ***@***.***> Betreff: Re: [bebbo/amiga-gcc] Another FPU problem (Issue #303) 
the real question is:

what is calling that function?
why, since with fpu that function should not be used
or if it still is used, the caller should expect the return value in fp0 too

**Comment by bebbo** [comment]
see here: https://github.com/bebbo/gcc/issues/188

**Comment by githubaf** [comment]
Looks good now!
