### ISSUE TITLE
internal compiler error: in print_operand_address2, at config/m68k/m68k.c:5445

### ISSUE THREAD

**Issue by krabobmkd** [bebbo/amiga-gcc#308]
... Recently, smartphones are tending to generate the brand new image format HIEC instead of JPEG, and this format propagates through oses at light speed, and as I can check my phone images through my A4000 / Deneb USB in MTP mode, I went to see if I could generate a HIEC datatype (and maybe a heic to jpg converter), for 68060 with libheif from https://github.com/strukturag/libheif ...

Note: I've juste made a "make update, make all"
 on my ubuntu with the cmake toolchain config I did,  to point amiga-gcc, bitsctream.cc (the first source from libheif) fails with this logs, that verbose all options.

Note: ...It fails on:  **"internal compiler error: in print_operand_address2, at config/m68k/m68k.c:5445"**
I understand this m68k.c is on the gcc source side... there is a gcc_assert at this line... (maybe I have a wrong option with far pointers ? ) so I guess I may post an issue here for the moment.

`[  3%] Building CXX object libheif/CMakeFiles/heif.dir/bitstream.cc.o
Using built-in specs.
COLLECT_GCC=/opt/amiga/bin/m68k-amigaos-g++
Target: m68k-amigaos
Configured with: /home/krabob/Code/gcc-amiga/amiga-gcc/projects/gcc/configure --prefix=/opt/amiga --target=m68k-amigaos --enable-languages=c,c++,objc --enable-version-specific-runtime-libs --disable-libssp --disable-nls --with-headers=/home/krabob/Code/gcc-amiga/amiga-gcc/projects/newlib-cygwin/newlib/libc/sys/amigaos/include/ --disable-shared --enable-threads=no --with-stage1-ldflags='-dynamic-libgcc -dynamic-libstdc++' --with-boot-ldflags='-dynamic-libgcc -dynamic-libstdc++' : (reconfigured) /home/krabob/Code/gcc-amiga/amiga-gcc/projects/gcc/configure --prefix=/opt/amiga --target=m68k-amigaos --enable-languages=c,c++,objc --enable-version-specific-runtime-libs --disable-libssp --disable-nls --with-headers=/home/krabob/Code/gcc-amiga/amiga-gcc/projects/newlib-cygwin/newlib/libc/sys/amigaos/include/ --disable-shared --enable-threads=no --with-stage1-ldflags='-dynamic-libgcc -dynamic-libstdc++' --with-boot-ldflags='-dynamic-libgcc -dynamic-libstdc++'
Thread model: single
gcc version 6.5.0b 221001103737 (GCC) 
COLLECT_GCC_OPTIONS='-D' 'HAVE_VISIBILITY' '-D' 'LIBHEIF_EXPORTS' '-D' 'heif_EXPORTS' '-I' '/home/krabob/Code/gcc-amiga/hief/build-libheif-AmigaGcc-Debug' '-I' '/home/krabob/Code/gcc-amiga/hief/libheif' '-I' '/home/krabob/Code/gcc-amiga/hief/libheif/include/libheif' '-I' '/home/krabob/Code/gcc-amiga/hief/libheif/include' '-O2' '-D' 'AMIGA' '-D' '__AMIGA__=1' '-noixemul' '-v' '-mcpu=68060' '-g' '-fPIC' '-fvisibility=hidden' '-fvisibility-inlines-hidden' '-Wall' '-Werror' '-Wsign-compare' '-Wconversion' '-Wno-sign-conversion' '-Wno-error=conversion' '-Wno-error=unused-parameter' '-Wno-error=deprecated-declarations' '-std=c++11' '-o' 'CMakeFiles/heif.dir/bitstream.cc.o' '-c' '-B' '/opt/amiga/m68k-amigaos/libnix/lib/'
 /opt/amiga/libexec/gcc/m68k-amigaos/6.5.0b/cc1plus -quiet -v -I /home/krabob/Code/gcc-amiga/hief/build-libheif-AmigaGcc-Debug -I /home/krabob/Code/gcc-amiga/hief/libheif -I /home/krabob/Code/gcc-amiga/hief/libheif/include/libheif -I /home/krabob/Code/gcc-amiga/hief/libheif/include -imultilib libm060 -iprefix /opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/ -isysroot /opt/amiga -isystem /opt/amiga/include -isystem /opt/amiga/m68k-amigaos/libnix/include -Dlibnix -D__libnix__ -D__libnix -D HAVE_VISIBILITY -D LIBHEIF_EXPORTS -D heif_EXPORTS -D AMIGA -D __AMIGA__=1 /home/krabob/Code/gcc-amiga/hief/libheif/libheif/bitstream.cc -quiet -dumpbase bitstream.cc -mcpu=68060 -auxbase-strip CMakeFiles/heif.dir/bitstream.cc.o -g -O2 -Wall -Werror -Wsign-compare -Wconversion -Wno-sign-conversion -Wno-error=conversion -Wno-error=unused-parameter -Wno-error=deprecated-declarations -std=c++11 -version -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -o /tmp/ccERPcC0.s
GNU C++11 (GCC) version 6.5.0b 221001103737 (m68k-amigaos)
	compiled by GNU C version 9.4.0, GMP version 6.2.0, MPFR version 4.0.2, MPC version 1.1.0, isl version none
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring nonexistent directory "/opt/amiga/libexec/gcc/m68k-amigaos/lib/gcc/m68k-amigaos/6.5.0b/include/c++"
ignoring nonexistent directory "/opt/amiga/libexec/gcc/m68k-amigaos/lib/gcc/m68k-amigaos/6.5.0b/include/c++/m68k-amigaos/libm060"
ignoring nonexistent directory "/opt/amiga/libexec/gcc/m68k-amigaos/lib/gcc/m68k-amigaos/6.5.0b/include/c++/backward"
ignoring nonexistent directory "/opt/amiga/libexec/gcc/m68k-amigaos/lib/gcc/m68k-amigaos/6.5.0b/include"
ignoring nonexistent directory "/opt/amiga/libexec/gcc/m68k-amigaos/m68k-amigaos/ndk-include"
ignoring nonexistent directory "/opt/amiga/libexec/gcc/m68k-amigaos/m68k-amigaos/sys-include"
ignoring nonexistent directory "/opt/amiga/libexec/gcc/m68k-amigaos/m68k-amigaos/include"
ignoring nonexistent directory "/home/krabob/Code/gcc-amiga/hief/libheif/include/libheif"
ignoring nonexistent directory "/home/krabob/Code/gcc-amiga/hief/libheif/include"
#include "..." search starts here:
#include <...> search starts here:
 /home/krabob/Code/gcc-amiga/hief/build-libheif-AmigaGcc-Debug
 /home/krabob/Code/gcc-amiga/hief/libheif
 /opt/amiga/include
 /opt/amiga/m68k-amigaos/libnix/include
 /opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/include/c++
 /opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/include/c++/m68k-amigaos/libm060
 /opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/include/c++/backward
 /opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/include
 /opt/amiga/m68k-amigaos/ndk-include
 /opt/amiga/m68k-amigaos/sys-include
 /opt/amiga/m68k-amigaos/include
End of search list.
GNU C++11 (GCC) version 6.5.0b 221001103737 (m68k-amigaos)
	compiled by GNU C version 9.4.0, GMP version 6.2.0, MPFR version 4.0.2, MPC version 1.1.0, isl version none
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
Compiler executable checksum: a6fe1c29d310183a8b022fa071e1a2fa
/home/krabob/Code/gcc-amiga/hief/libheif/libheif/bitstream.cc: In constructor 'heif::StreamReader_memory::StreamReader_memory(const uint8_t*, int64_t, bool)':
/home/krabob/Code/gcc-amiga/hief/libheif/libheif/bitstream.cc:77:32: warning: conversion to 'size_t {aka unsigned int}' from 'int64_t {aka long long int}' may alter its value [-Wconversion]
     memcpy(m_owned_data, data, m_length);
                                ^~~~~~~~
/home/krabob/Code/gcc-amiga/hief/libheif/libheif/bitstream.cc: In member function 'bool heif::BitstreamRange::read(uint8_t*, int64_t)':
/home/krabob/Code/gcc-amiga/hief/libheif/libheif/bitstream.cc:271:36: warning: conversion to 'size_t {aka unsigned int}' from 'int64_t {aka long long int}' may alter its value [-Wconversion]
   bool success = istr->read(data, n);
                                    ^
/home/krabob/Code/gcc-amiga/hief/libheif/libheif/bitstream.cc: In constructor 'heif::StreamReader_istream::StreamReader_istream(std::unique_ptr<std::basic_istream<char> >&&)':
/home/krabob/Code/gcc-amiga/hief/libheif/libheif/bitstream.cc:38:1: internal compiler error: in print_operand_address2, at config/m68k/m68k.c:5445
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
make[2]: *** [libheif/CMakeFiles/heif.dir/build.make:64: libheif/CMakeFiles/heif.dir/bitstream.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:300: libheif/CMakeFiles/heif.dir/all] Error 2
make: *** [Makefile:130: all] Error 2`

**Comment by bebbo** [comment]
using options like `-fPIC` aren't supposed to work.

**Comment by krabobmkd** [comment]
Ok, so very simply, libheif has CMAKE_POSITION_INDEPENDENT_CODE=ON forced in its CMakelists.txt, (not as an option) which forces -fPIC. just setting it to OFF make the comiler work ! Thank you.

**Comment by bebbo** [comment]
There is no plan to support `-fPIC` or so.
