### ISSUE TITLE
Undefined reference to _EH_FRAME_BEGINS__ / _EH_FRAME_OBJECTS__

### ISSUE THREAD

**Issue by Midar** [bebbo/amiga-gcc#311]
Since today, when using the Docker image on GitHub CI, I get undefined reference for both. (Haven't updated my local install yet)

**Comment by bebbo** [comment]
use this:
```
 #ifdef OF_AMIGAOS_M68K
__attribute__((section(".list___CTOR_LIST__")))
uintptr_t __CTOR_LIST__[0] = {0};
__attribute__((section(".list___EH_FRAME_BEGINS__")))
const void * _EH_FRAME_BEGINS__ = 0;
__attribute__((section(".dlist___EH_FRAME_OBJECTS__")))
void * _EH_FRAME_OBJECTS__ = 0;
 #endif
```
and in the endfile:
```
__attribute__((section(".list___CTOR_LIST__")))
long __end_of__CTOR_LIST__ = 0;
__attribute__((section(".list___EH_FRAME_BEGINS__")))
long __end_of__EH_FRAME_BEGINS__ = 0;
__attribute__((section(".dlist___EH_FRAME_OBJECTS__")))
long __end_of__EH_FRAME_OBJECTS__ = 0;
```

**Comment by Midar** [comment]
Any reason those got removed? Would be great to not need that :).
Also, is the ABI for those gonna be stable eventually?

**Comment by bebbo** [comment]
these are still there somewhere, but you are linking without stdlibs

**Comment by Midar** [comment]
Did it slightly differently in the end, so that I don't need to skip the first entry like in cxxglue.c.

Will it stay this way now or are further changes planned?

**Comment by bebbo** [comment]
> Did it slightly differently in the end, so that I don't need to skip the first entry like in cxxglue.c.
> 
> Will it stay this way now or are further changes planned?

There are no planned changes. Well I didn't plan any change at all, it just was necessary, since CONSTRUCTORS are buggy.

**Comment by Midar** [comment]
Cool, thanks!

It compiles for now, but still doesn't work. But neither does it when disabling .library support entirely, so there's something else that changes in amiga-gcc that's currently breaking it. Closing, as this is probably a different bug.
