### ISSUE TITLE
macOS Ventura (on M1) discoveries and skipping gdb

### ISSUE THREAD

**Issue by acf** [bebbo/amiga-gcc#316]
I'm doing a fresh install onto a new Mac, spec as above.   

The **first** issue I hit (same as #301) is fixed by replacing `gcc-11` with `gcc-12` in the Homebrew instructions in the readme.  I'll make a PR for this. ( https://github.com/bebbo/amiga-gcc/pull/317 )

The **second** issue I hit was a permissions problem with` /opt/amiga` which I fixed for now with a `chmod -R 777 /opt/amiga` until the installation is done.  I could use another prefix but I like it there.  I suspect with Homebrew installing in `/opt` on arm64 that might have something to do with it.

The **third** issue I have, I have not been able to resolve. I don't expect you to debug it, and I don't have enough skill to help, so I'm just looking to workaround....

** Is it possible to "build-all-but-skip-gdb". I don't use it directly, but maybe it's a dependency of something else and can't be avoided? **

```
gmake[8]: Nothing to be done for 'all-am'.
gmake[8]: Leaving directory '/Users/acf/work/amiga-gcc/build-Darwin/binutils/gnulib/import'
gmake[7]: Leaving directory '/Users/acf/work/amiga-gcc/build-Darwin/binutils/gnulib/import'
gmake[6]: Leaving directory '/Users/acf/work/amiga-gcc/build-Darwin/binutils/gnulib/import'
gmake[6]: Entering directory '/Users/acf/work/amiga-gcc/build-Darwin/binutils/gnulib'
gmake[6]: Leaving directory '/Users/acf/work/amiga-gcc/build-Darwin/binutils/gnulib'
gmake[5]: Leaving directory '/Users/acf/work/amiga-gcc/build-Darwin/binutils/gnulib'
gmake[4]: Leaving directory '/Users/acf/work/amiga-gcc/build-Darwin/binutils/gnulib'
gmake[3]: Leaving directory '/Users/acf/work/amiga-gcc/build-Darwin/binutils/gdb'
  CXXLD  gdb
Undefined symbols for architecture arm64:
  "__ZTH25thread_local_segv_handler", referenced from:
      __Z12gdb_demanglePKci in cp-support.o
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
gmake[2]: *** [Makefile:1859: gdb] Error 1
make binutils gdb...failed
use less "log/make binutils gdb.log" to view the full log and search for ***
gmake: *** [Makefile:387: /Users/acf/work/amiga-gcc/build-Darwin/binutils/_gdb] Error 2
```

**Comment by acf** [comment]
In the end I just removed gdb from all in the makefile.  I should have spotted min :-)

Sadly though min doesn't work either because I hit a problem with libnix.

```
/Users/acf/work/amiga-gcc/projects/libnix/sources/amiga/misc/ArgArray.c: In function 'ArgString':
/Users/acf/work/amiga-gcc/projects/libnix/sources/amiga/misc/ArgArray.c:55:23: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
   if (!entry || !(str=FindToolType(tt,entry)))
                       ^~~~~~~~~~~~
/Users/acf/work/amiga-gcc/projects/libnix/sources/amiga/misc/ArgArray.c: In function 'ArgInt':
/Users/acf/work/amiga-gcc/projects/libnix/sources/amiga/misc/ArgArray.c:64:21: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
   if (entry && (str=FindToolType(tt,entry)))
                     ^~~~~~~~~~~~
cc1: all warnings being treated as errors
gmake[3]: *** [/Users/acf/work/amiga-gcc/projects/libnix/Makefile.gcc6:239: libnix13.a] Error 1
make libnix...failed
```

**Comment by acf** [comment]
I'll stick to SAS/C tonight I think :-)

**Comment by bebbo** [comment]
> I'll stick to SAS/C tonight I think :-)

fine for me

**Comment by bebbo** [comment]
> In the end I just removed gdb from all in the makefile. I should have spotted min :-)
> 
> Sadly though min doesn't work either because I hit a problem with libnix.
> 
> ```
> /Users/acf/work/amiga-gcc/projects/libnix/sources/amiga/misc/ArgArray.c: In function 'ArgString':
> /Users/acf/work/amiga-gcc/projects/libnix/sources/amiga/misc/ArgArray.c:55:23: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
>    if (!entry || !(str=FindToolType(tt,entry)))
>                        ^~~~~~~~~~~~
> /Users/acf/work/amiga-gcc/projects/libnix/sources/amiga/misc/ArgArray.c: In function 'ArgInt':
> /Users/acf/work/amiga-gcc/projects/libnix/sources/amiga/misc/ArgArray.c:64:21: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
>    if (entry && (str=FindToolType(tt,entry)))
>                      ^~~~~~~~~~~~
> cc1: all warnings being treated as errors
> gmake[3]: *** [/Users/acf/work/amiga-gcc/projects/libnix/Makefile.gcc6:239: libnix13.a] Error 1
> make libnix...failed
> ```

how do you built it?

**Comment by acf** [comment]
`CC=gcc-12 CXX=g++-12 gmake all NDK=3.2 `

**Comment by bebbo** [comment]
> `CC=gcc-12 CXX=g++-12 gmake all NDK=3.2 `

ok, can happen if NDK3.2 changes ...

**Comment by acf** [comment]
Ah ok, so maybe I try again with 39 and see if I get further

**Comment by acf** [comment]
Yeah seems to make it past libnix with 39.   3.2 NDK hasn't changed since March (R4) so that's a bit puzzling.

**Comment by acf** [comment]
I'll close this ticket

**Comment by Guddler** [comment]
I just hit the same issue of undefined symbols in GDB. I'm just running a 'make min' now to see if that works.

Is this issue related to the comment "ALSO NOTE If you want m68k-amigaos-gdb then you have to build it with gcc" ?
