### ISSUE TITLE
make clean-prefix wipes out your entire prefix!

### ISSUE THREAD

**Issue by gbin** [bebbo/amiga-gcc#318]
```
sal ➜  amiga-gcc (master) make clean-prefix
rm -rf /home/gbin/prefix/bin
[...]
```

ouch I had a lot of other things in my prefix.

The intended behavior would be to only remove files that were initially installed in the prefix.

Thanks

**Comment by bebbo** [comment]
it's in the READ.me:
```
make clean-prefix           remove all content from the prefix folder
```

**Comment by gbin** [comment]
Yeah but this is not how prefix generally behaves.

Usually prefix is like a mini system FS in your user directory, this is
made to be shared.

**Comment by bebbo** [comment]
I renamed `clean-prefix` into `drop-prefix` maybe that's more explicite.

**Comment by gbin** [comment]
LGTM! Thank you so much!
