### ISSUE TITLE
Cannot get any combiled binary to run on stock 68000 A500

### ISSUE THREAD

**Issue by rjflory** [bebbo/amiga-gcc#327]
Help-  I can't get simple hello_world program to run on a stock 68000 A500.  
I always get "file is not an object module" error or guru hit.

yes, file has "rwed" attribs on target FS.

I'm a longtime embedded developer with lots of cross-compilers experience, but just haven't hit on the magic combination of switches/libs to produce a working target executable on real A500 hardware.

/opt/amiga/cross_tools/bebbo/bin/m68k-amigaos-gcc hello_world.c -o hello_world_gcc
/opt/amiga/cross_tools/bebbo/bin/m68k-amigaos-gcc -mcrt=nix13 hello_world.c -o hello_world_gcc_nix13
/opt/amiga/cross_tools/bebbo/bin/vc hello_world.c -o hello_world_vbcc
/opt/amiga/cross_tools/bebbo/bin/vc +kick13 hello_world.c -o hello_world_vbcc_kick13

I tried all the invocations above- all fail or explode on target.
I did try "-m68000" switch with gcc build, but objdump shows the output is identical to default settings.

help!, i must be missing something obvious/simple...

**Comment by bebbo** [comment]
Assume your source file `hello_world.c` is:
```
#include <stdio.h>
int main() {
  puts("Hullow!");
  return 0;
}
```
Then the first 3 commands are creating an executable which is working on kickstart 2.0.
The 4th will work too after the next update (I added the kick13 target to vbcc)

Only the kick13 versions will run on kick13.

If the vbcc does not work on kick13, it's likely that there are unsupported hunk types... no idea how to fix that^^

here is what I used/created
[agc327.zip](https://github.com/bebbo/amiga-gcc/files/10713311/agc327.zip)

**Comment by rjflory** [comment]
well, that didn't exactly work, but I learned some important things during the long side-trip....  ;)
 
 The hard lesson I learned was that Linux loopback-mounting an amiga 880k floppy affs ADF file does **_NOT_** correctly write files into the ADF.  I found that even your  _hello_world.c_  text-file did not look right (it was empty) on the real A500 when using "TYPE hello_world.c HEX".

 I switched to using xdftools and wrote some wrapper scripts to make it civilized to use.

 Things started to make a little more sense, TYPE-ing your  _hello_world.c_  file looked fine on A500 target, but the   _hello_world_vbcc_kick13_  exec still reports " :file is not an object module" -  but doing this no longer crashes the machine, which is a big improvement in my view.   ;)

**Comment by rjflory** [comment]
hi, just some feedback (not a complaint). 

 I noticed the amiga-gcc  .md  file mentions make "_**clean-prefix**_" several times.  This target does not actually exist, so make returns an error:
 
make PREFIX=/opt/amiga/cross_tools/bebbo/ clean-prefix
make: *** No rule to make target 'clean-prefix'.  Stop.

**Comment by mheyer32** [comment]
The target is now called "drop-prefix" as it removes the whole prefix directory(?).

**Comment by bebbo** [comment]
I updated the READM.md file.

Note that you need to do a `git pull` first before running any `make ...` commands! The kick13 target for vbcc is live.

**Comment by MBeijer** [comment]
Try `protect <file-name> +e` in Amiga SHELL where `<file-name>` is the name
of your file. The executable flag from Linux FS is not the same as on Amiga
FS. I suggest compressing the file with lha, as lha stores the Linux
executable flag so when the file is extracted on Amiga the file will retain
the executable flag. Then you should be able to run your application on
your Amiga by simply typing your file-name. You don't need to execute it
with the `exec` command.

**Comment by bebbo** [comment]
I rather suspect that the generated files contains a HUNK_DREL32 hunk, which is unknown to Kick13.
Using the provided kick13 config:
```
vc +kick13 hello_world.c -o hello_world_vbcc_kick13
```
yields now an executable without those hunks:
```
[stefan@HP agc327]$ hunkdump hello_world_vbcc_kick13
reading hello_world_vbcc_kick13
hunk 000003f3,      HUNK_HEADER,          0
6 sections, 0 - 5 
sizes: 3032, 52, 12, 12, 16, 24
hunk 000003e9,        HUNK_CODE,       3032
hunk 000003ec,     HUNK_RELOC32,        100
HUNK_END
hunk 000003ea,        HUNK_DATA,          8
HUNK_END
hunk 000003ea,        HUNK_DATA,         12
HUNK_END
hunk 000003ea,        HUNK_DATA,         12
hunk 000003ec,     HUNK_RELOC32,          4
HUNK_END
hunk 000003ea,        HUNK_DATA,         16
hunk 000003ec,     HUNK_RELOC32,          8
HUNK_END
hunk 000003eb,         HUNK_BSS,         24
HUNK_END
```
and it runs on kick13.

**Comment by rjflory** [comment]
Hi-

 Some quick feedback.  I was able to produce an executable that worked on a  KS/WB1.3 A500.  I took awhile to figure out, but I had to supply the  _+kick13_  commandline switch as "**_+kick13.config_**" -  plain "**_+kick13_**" would always fail with "**No config file!**" .

 /opt/amiga/cross_tools/bebbo/bin/vc _+kick13_ hello_world.c -o hello_world_vbcc_kick13 
No config file!
echo $?
1

/opt/amiga/cross_tools/bebbo/bin/vc _+kick13.config_ hello_world.c -o hello_world_vbcc_kick13
echo $?
0

 I'm very happy with this.   **_Thank you very much_** for putting in the extra time to make these tools available to the community.

ron

**Comment by bebbo** [comment]
Hm, I already added a patch to the vc frontend to append `.config` if nothing was found yet and it works locally...
... maybe you had not picked up the recent changes.
But anyway, it's working now for you. great!
