### ISSUE TITLE
Amiga lib issue.

### ISSUE THREAD

**Issue by m1awicki** [bebbo/amiga-gcc#329]
I have recently updated `amiga-gcc` to the newest version and noticed problem with `libamiga`. Attempt to create message port;
`port = CreatePort(0, 0);`
causes message:
 `../../out/game.exe: _NewList reloc for _NewList is out of range: 00000000`
and when run, application crash on call to `CreatePort`. It was working correctly on older version of the toolchain.

**Comment by bebbo** [comment]
This seems to be a bug in the amiga.lib from NDK_3.2, which is now used.
Guess I'll roll this change back. The old `libamiga.a` is still present in the folder `lib`. Replace the current libamiga.a with that one.

**Comment by m1awicki** [comment]
Thank you for quick reply!
I can confirm that this is in fact caused by `libamiga` itself. Replacing `/opt/amiga/m68k-amigaos/lib/libamiga.a` with `lib/libamiga.a` fixed the problem
