### ISSUE TITLE
Can't build on Debian

### ISSUE THREAD

**Issue by tehKaiN** [bebbo/amiga-gcc#33]
`make update` works well, but `make all` fails mysteriously:

https://pastebin.com/TzU6H37j

Running on debian: `4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux`

**Comment by bebbo** [comment]
there is no log for `make all` ?

**Comment by tehKaiN** [comment]
Sorry, wrong pastebin ;)

https://pastebin.com/ikwi7D11

**Comment by bebbo** [comment]
you did not install `texinfo`...

**Comment by tehKaiN** [comment]
`texinfo is already the newest version (6.3.0.dfsg.1-1+b2).`

Any other ideas?

**Comment by bebbo** [comment]
coreutils, bash?

**Comment by tehKaiN** [comment]
`bash is already the newest version (4.4-5).`
`coreutils is already the newest version (8.26-3).`

Perhaps some of packages from previous toolchain? Not all of them are in Debian repos, so I can't check quickly.

**Comment by bebbo** [comment]
sorry - I pass on this - can't support all distros.
