### ISSUE TITLE
MUI patch made not using mui.lib impossible

### ISSUE THREAD

**Issue by mheyer32** [bebbo/amiga-gcc#332]
I don't think your patch to proto/muimaster_lib.h in #288 is good as it basically prevents one from using the inline function path. 

b9ed9db

In particular, it disables inline function macros like NewObject(). It would have been better if @walkero-gr made the choice to use or not use the INLINE macros in his projects.

I just ran into an issue with a MUI project that does not attempt to link against mui.lib and because of this patch runs into unresolved symbols.

**Comment by bebbo** [comment]
Well: simply provide a solution to make nested `NewObject()` calls work with INLINE macros.

**Comment by mheyer32** [comment]
Nested calls? Can you elaborate please?

**Comment by bebbo** [comment]
the typical mui stuff looks like
```
	app = ApplicationObject,
		MUIA_Application_Title      , "Project",
		MUIA_Application_Version    , "$VER: Project X.X (XX.XX.XX)",
		MUIA_Application_Copyright  , " ",
		MUIA_Application_Author     , " ",
		MUIA_Application_Description, " ", 
		MUIA_Application_Base       , " ",

		MUIA_Application_Window, win1 = WindowObject,
			MUIA_Window_Title, "Window Title",
			MUIA_Window_ID   , MAKE_ID('E','M','R','T'),
			WindowContents, VGroup,
				Child, MUI_MakeObject(MUIO_Label,"I am MUI Application on Amiga 3.X",NULL),
			TAG_DONE),
		TAG_DONE),
		
//	End
	TAG_DONE);
```
which resolves into nested `NewObject(...)` calls.

**Comment by mheyer32** [comment]
I see. Does that mean, we should make MUI not use inline macros in first place? I.e. use some other mode like "clib-only" and thus enforce linking against mui.lib?

**Comment by bebbo** [comment]
> I see. Does that mean, we should make MUI not use inline macros in first place? I.e. use some other mode like "clib-only" and thus enforce linking against mui.lib?

the current patch makes MUI not use inline macros.
