### ISSUE TITLE
Binaries build with 13.1.1 not executable

### ISSUE THREAD

**Issue by isoriano1968** [bebbo/amiga-gcc#343]
Hi,

did some testing using the Docker Crosstools (https://github.com/AmigaPorts/docker-amiga-gcc) from AmigaPorts with your 6.5 and 13.1.1 AMIGA gcc-cc using the P96Developer Examples. 

While the 6.5b executables run as expected the 13.1.1 binaries thow an error.

No magic used when compiling: gcc test.c -o test

![gcc](https://github.com/bebbo/amiga-gcc/assets/81116077/685f1fa2-b29a-4a91-a580-99937514bcfc)

**Comment by bebbo** [comment]
please check the version of the linker, current is:
```
GNU ld (GNU Binutils) 2.39.0.230505-185525
```

**Comment by jeffv03** [comment]
Hello :)

Le 13/05/2023 à 07:30, isoriano1968 a écrit :
>
> Hi,
>
> did some testing using the Docker Crosstools 
> (https://github.com/AmigaPorts/docker-amiga-gcc) from AmigaPorts with 
> your 6.5 and 13.1.1 AMIGA gcc-cc using the P96Developer Examples.
>
> While the 6.5b executables run as expected the 13.1.1 binaries thow an 
> error.
>
> No magic used when compiling: gcc test.c -o test
>

hum, perhaps the 13.1.1 haven't set the right protection bits on the 
file when saving the exe just created ? did you've check it ?


Jeff

**Comment by isoriano1968** [comment]
Hi Jeff,

attributes "rwed" were not set on both executables .. but made no difference to the execution. Added rwed to both no change in the execution of the failing one.

**Comment by isoriano1968** [comment]
> please check the version of the linker, current is:
> 
> ```
> GNU ld (GNU Binutils) 2.39.0.230505-185525
> ```

Can confirm the same version for ld.

![Screenshot from 2023-05-13 11-01-43](https://github.com/bebbo/amiga-gcc/assets/81116077/3122756b-516a-4cf1-b2da-71f510c29011)

**Comment by MBeijer** [comment]
@isoriano1968 with gcc 13.1, have you tried explicitly defining `-mcrt=nix20`?

**Comment by isoriano1968** [comment]
> @isoriano1968 with gcc 13.1, have you tried explicitly defining `-mcrt=nix20`?

Mate, that did it! Works now.

**Comment by MBeijer** [comment]
Which means something with newlib is broken then? or default crt is different on gcc 13.1?

**Comment by bebbo** [comment]
no idea how recent that docker thing is. sorry.

**Comment by MBeijer** [comment]
It's super recent, I built a new version yesterday...

**Comment by bebbo** [comment]
There's always a next version.

**Comment by MBeijer** [comment]
I mean, I update the amigadev/crosstools docker image regularly, especially now when 13.1 is in development.

**Comment by bebbo** [comment]
and I mean, that it is time to update the docker image.

**Comment by bebbo** [comment]
dang - baserel^^
rinse and repeat pls.

**Comment by isoriano1968** [comment]
ei ei ei .. the "won't fix" label still accurate? :-)

**Comment by bebbo** [comment]
> ei ei ei .. the "won't fix" label still accurate? :-)

I can't fix your docker image.
