### ISSUE TITLE
.bsschip and .datachip directives not supported anymore

### ISSUE THREAD

**Issue by jotd666** [bebbo/amiga-gcc#345]
Just updated the toolchain with prebuilt windows setup and while it fixed a link problem on some C program, my asm sources won't build anymore

    amiga/amiga.68k:2573: Error: unknown pseudo-op: `.bsschip'
    amiga/amiga.68k:2604: Error: unknown pseudo-op: `.datachip'

What is the replacement for this?

**Comment by bebbo** [comment]
you need to add a `.section` statement, e.g.
```
    .section .bsschip
```

**Comment by jotd666** [comment]
oh, yes, that works. Thank you so much!
