### ISSUE TITLE
Error: amiga-gcc 13.1 - unknown type name 'off_t'

### ISSUE THREAD

**Issue by isoriano1968** [bebbo/amiga-gcc#349]
Hi,

was trying out the latest 13.1 branch and during make min receiving the following error:

bgcc/../gcc -I/home/isoriano/Sources/amiga-gcc/projects/gcc/libgcc/../include  -DHAVE_CC_TLS -DUSE_EMUTLS  -o _gcov_merge_add.o -MT _gcov_merge_add.o -MD -MP -MF _gcov_merge_add.dep -DL_gcov_merge_add -c /home/isoriano/Sources/amiga-gcc/projects/gcc/libgcc/libgcov-merge.c
In file included from /home/isoriano/Sources/amiga-gcc/projects/gcc/libgcc/libgcov.h:49,
                 from /home/isoriano/Sources/amiga-gcc/projects/gcc/libgcc/libgcov-merge.c:26:
/opt/amiga/m68k-amigaos/sys-include/sys/mman.h:34:68: error: unknown type name 'off_t'
   34 | void *mmap(void *addr, size_t length, int prot, int flags, int fd, off_t offset);
      |                                                                    ^~~~~
make[4]: *** [Makefile:924: _gcov_merge_add.o] Error 1
make libgcc...failed
use less "log/make libgcc.log" to view the full log and search for ***
make: *** [Makefile:866: /home/isoriano/Sources/amiga-gcc/build-Linux-m68k-amigaos/gcc/_libgcc_done] Error 2

I just added `#include <sys/types.h>` to `amiga-gcc/projects/gcc/libgcc/libgcov.h` which fixed it.

**Comment by bebbo** [comment]
there reference build is ok: https://ci.appveyor.com/project/bebbo/amiga-gcc-13-1

**Comment by isoriano1968** [comment]
And your are right once again, when I did the update-gcc no missing <sys/types.h> anymore ..

**Comment by isoriano1968** [comment]
Non existent anymore ..
