### ISSUE TITLE
[MSYS2 on Windows, building w/ gcc amiga13.1] configure libdebug...failed,  fatal error: cannot find 'ld'

### ISSUE THREAD

**Issue by jbilander** [bebbo/amiga-gcc#354]
Hi Stefan, thanks for all your great work with this toolchain. I tried building amiga-gcc with your gcc 13 (amiga13.1) branch and all goes well on a linux-vm but I get a problem on Windows (using MSYS2) when libdebug is being built. This is an old Win8.1 Pro machine so I don't have WSL unfortunately.

Here is how I built from scratch:

```
git clone https://github.com/bebbo/amiga-gcc
cd amiga-gcc
make update
make clean
make branch branch=amiga13.1 mod=gcc
make all NDK=3.2 -j4
```

Here is the error I get when running the last (make all NDK=3.2 -j4) command.
![libdebug_failed](https://github.com/bebbo/amiga-gcc/assets/1673918/3889b6b0-f0c1-4710-88d8-a4a8af85a42e)

The full copy-paste of my commands and their output here:
https://pastebin.com/P04dXFYC

config.log:
![libdebug_failed_2](https://github.com/bebbo/amiga-gcc/assets/1673918/0ddb08fa-f26a-46cc-b4f5-15a540401dd4)

And here is the full log from config.log:
https://pastebin.com/DEwY8vTp

It seems that it cannot find 'ld', very strange since everything is in there...

![build_listing](https://github.com/bebbo/amiga-gcc/assets/1673918/3f51b204-e2ed-4334-a085-afe9a56c108b)

Do you by any chance know how to fix this?

My MSYS2 installation is updated to latest with `$ pacman -Suy`

Thankful for any input you might have.
Regards, J

**Comment by jbilander** [comment]
I tried compiling a hello world and get the same error:

```
m68k-amigaos-gcc -Wall -c -o hello.o hello.c
m68k-amigaos-gcc -Wall -nostdlib -o hello hello.o
collect2: fatal error: cannot find 'ld'
compilation terminated.
make: *** [Makefile:11: hello] Error 1
```

verbose output here:
https://pastebin.com/1CRtefJy

and the exact same on the linux-vm works:
https://pastebin.com/X6Hy6mgm

**Comment by jbilander** [comment]
a quick follow up, I tried building amiga-gcc 6.5.0b and that works so something is up with gcc 13 when building in MSYS2.

complete copy-paste log here:

https://pastebin.com/Tmgecx9V

**Comment by bebbo** [comment]
It builds locally these days. It's usually an MSYS2 issue.
rinse and repeat^^
