### ISSUE TITLE
Building GCC and binutils gdb on MacOS started to fail

### ISSUE THREAD

**Issue by steen-lund** [bebbo/amiga-gcc#355]
Not sure what has caused the issue but building on macOS doesn't work any more. Probably a because of a newer version of XCode.

I searched the compile errors and found the fixes that I have included in the attached patch. I don't remember where I found the fixes for aarch64 but the fixes to graphite comes from here https://github.com/cpackham/crosstool-ng/commit/adf74e615d3c0ef4ad3e47d7654fea98d3e44335

[gcc-22.37.43.patch](https://github.com/bebbo/amiga-gcc/files/11825843/gcc-22.37.43.patch)

binutils gdb fails to build because of the enum split_style::DOT, seems like DOT collides with a previous define, so I simply renamed DOT to something else

**Comment by bebbo** [comment]
You simply have to use the correct ISL version.

see https://github.com/bebbo/amiga-gcc/issues/341
or https://github.com/bebbo/amiga-gcc/issues/336#issuecomment-1510043901
