### ISSUE TITLE
Build failing on Arch Linux

### ISSUE THREAD

**Issue by OwenTheBowen** [bebbo/amiga-gcc#357]
Most of the build goes fine, up until it tries to build GCC.

I've attached a file of the errors it prints.

I'm using Arch Linux, 4GB of memory, 4-core x86_64 CPU.
[Build Errors.txt](https://github.com/bebbo/amiga-gcc/files/12189816/Build.Errors.txt)

**Comment by bebbo** [comment]
I guess your version of ISL does not match.

**Comment by OwenTheBowen** [comment]
Currently I have **libisl-0.26-1**.

**Comment by bebbo** [comment]
There is a script `amiga-gcc/projects/gcc/contrib/download_prerequisites` to download working versions.
Once present these should be picked up automatically...

**Comment by jezze** [comment]
I got this same issue. How did you solve it exactly?

**Comment by bebbo** [comment]
Enter the directory `amiga-gcc/projects/gcc` then run the script `contrib/download_prerequisites`.
Now the build should work and use the downloaded versions.

**Comment by jezze** [comment]
yes that seems to work! thanks!
