### ISSUE TITLE
[output][question][terminal] Is any terminal library present?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [bebbo/amiga-gcc#36]
Is any terminal library present?
I mean something like ncurses or conio or just plain terminal escape/control codes such as adm3a, VT52 or VT100?

**Comment by bebbo** [comment]
no.

**Comment by Fabrizio-Caruso** [comment]
Thanks @bebbo ! 
Any chance to see some minimal support for plain simple terminal output? (Just cursor control)
Can you confirm that standard Amiga terminals do not understand any control or escape codes? (I mean the terminals and not your compiler/lib).

**Comment by bebbo** [comment]
The Amiga console supports (full) ANSI escape codes.

You might be able to cross-compile ncurses or a similar library.

**Comment by bebbo** [comment]
it's ANSI X3.64

**Comment by Fabrizio-Caruso** [comment]
Thanks a lot!
