### ISSUE TITLE
Compiling with any optimization other than -O0 leads to various miscompilations

### ISSUE THREAD

**Issue by Midar** [bebbo/amiga-gcc#360]
It seems that with any level > -O0, there are a lot of miscompilations. I tried -O1, -O2 and -Os and they all lead to different miscompiles. Since these are various different miscompiles, I'm not sure how to report those. It can be very easily reproduced by compiling ObjFW with amiga-gcc, testing the resulting "tests" binary, then replacing -O0 with any other optimization level in buildsys.mk and rebuilding and see it crash (sooner with -O2, later with the other optimization levels).

**Comment by bebbo** [comment]
this was moved to https://github.com/bebbo/gcc/issues/207

**Comment by Midar** [comment]
Ah, sorry. I was sure I had already reported it, but couldn’t find it and so thought I hadn’t. Sorry for the noise.
