### ISSUE TITLE
Problems compiling on MacOS

### ISSUE THREAD

**Issue by hitman-codehq** [bebbo/amiga-gcc#361]
Hello Bebbo.

It seems that I am no longer able to compile gcc on MacOS on an Intel system.  I have ensured that I am using all of the required BREW utilities.  I get different results depending on what command line I use.  The three I tried are:

gmake -j4 all SHELL=$(brew --prefix)/bin/bash
gmake -j4 all SHELL=$(brew --prefix)/bin/bash (with GNU bison)
CC=gcc-12 CXX=g++-12 gmake all SHELL=$(brew --prefix)/bin/bash

The first one fails trying to compile gdb, which is expected as it's using Apple's bison, but in the past gdb wasn't included in the all target so this wasn't a problem.

The second one fails when compiling gcc with errors like "error: use of undeclared identifier 'isl_val_free'"

The third one fails when compiling binutils with "error: unrecognized command-line option '-V'"

I have attached a zip file containing the logs from the 3 different invocations.  It would be appreciated if you could look into this!

[gcc_build.zip](https://github.com/bebbo/amiga-gcc/files/12772824/gcc_build.zip)

**Comment by bebbo** [comment]
see https://github.com/bebbo/amiga-gcc/issues/341
or https://github.com/bebbo/amiga-gcc/issues/336#issuecomment-1510043901
