### ISSUE TITLE
6.5.0b/libstdc++.a(iostream-inst.o): duplicate section - problem with std::setfill

### ISSUE THREAD

**Issue by tdolphin-org** [bebbo/amiga-gcc#364]
for such simple C++ program
```
#include <iomanip>
#include <iostream>

int main(int argc, char *argv[])
{
    std::cout << std::setfill('0') << std::endl;
}
```

cross compilation on linux, gives such errors:

_$ m68k-amigaos-g++ -lstdc++ -o setfill-error setfill-error.cpp_

**/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/libstdc++.a(iostream-inst.o): duplicate section `.text._ZSt7setfillIcESt8_SetfillIT_ES1_' has different size**

**/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/libstdc++.a(iostream-inst.o): duplicate section `.text._ZSt7setfillIcESt8_SetfillIT_ES1_' has different size**

**Comment by bebbo** [comment]
That's a warning not an error.
The inline function in your file is compiled with a different option as the built library. Try `-Os`.
I also recommend adding `-noixemul`.
