### ISSUE TITLE
_custom , ciaa and ciaab should be marked as "far"

### ISSUE THREAD

**Issue by mheyer32** [bebbo/amiga-gcc#365]
Not sure if this belongs here or to libnix. 
amiga.lib defines _custom, ciaa and ciab. But when linking against amiga.lib in a -fbaserel project (in my case a library), at least accessing ciaa caused a linker error:

```
_o/s3trio64/chip_s3trio64.o: in function `SetMemoryClock':
/home/matze/p96drivers/s3trio64/chip_s3trio64.c:282:(.text+0x628): relocation truncated to fit: DREL16 against `ciaa'
_o/s3trio64/chip_s3trio64.o: in function `SetClock':
/home/matze/p96drivers/s3trio64/chip_s3trio64.c:1033:(.text+0x1644): relocation truncated to fit: DREL16 against `ciaa'
collect2: error: ld returned 1 exit status
```

I helped myself with qualifying the declarations with "FAR" (__far) . I think the alib.h should do the same.

**Comment by bebbo** [comment]
now the baserel lib is copied too, no need to change headers.

**Comment by bebbo** [comment]
any update here? with the baserel lib that issue should be solved.
