### ISSUE TITLE
Emit native Windows directories under Cygwin

### ISSUE THREAD

**Issue by tehKaiN** [bebbo/amiga-gcc#37]
My VSCode gets very confused by gcc/g++ emitting warnings/errors with cygpaths. Also, latest WnUAE debugging feature doesn't like them in debugging symbols. Also when logging, having `__FILE__` macro emitting native windows paths would be helpful

- [x] GCC Error/Warning/Note paths
- [x] G++ Error/Warning/Note paths
- [ ] GCC Debugging symbols paths
- [ ] G++ Debugging symbols paths
- [ ] `__FILE__` paths

**Comment by bebbo** [comment]
please test :-)

Note that you have to use a prefix with drive! E.g. `/cygdrive/c/opt/amiga`

**Comment by tehKaiN** [comment]
Errors/warnings are fine, but `__FILE__` is still an absolute cygpath. It's not that critical, so I'll not whine that much about it ;)

Haven't tested debugging symbols yet.

**Comment by bebbo** [comment]
the msys base setup-amiga-gcc.exe should be fine
