### ISSUE TITLE
I managed to build bebbo amiga gcc cross-compiler on MSYS2 to a point where linker

### ISSUE THREAD

**Issue by kaarlo52** [bebbo/amiga-gcc#370]
cant find:

crt0.o
-lstubs
-lamiga
-lgcc

everything was build to .exe windows executables with MSYS2.

**Comment by bebbo** [comment]
the README says:

`Also note that you MUST cd into an absolute path e.g. cd /c/msys64/home/test/amiga-gcc/ before running make, or builds may fail, because some files aren't found correctly (that's a msys2 bug).`

maybe that affects you too.
