### ISSUE TITLE
Add supported processors to README

### ISSUE THREAD

**Issue by danboid** [bebbo/amiga-gcc#371]
I've not tried amiga-gcc yet but I'd like to use it to build for my unaccelerated A600 w/ Kickstart 3.1. Does it support building for the 68000? It says it supports Kickstart 1.3 so I presume it supports the 68000 as a build target?

It would be good if the README covered which 680XX CPUs amiga-gcc supports. Does it support and can it optimize for everything from the 68000 all the way through to the 68060? Are there any exceptions or gotchas?

**Comment by MBeijer** [comment]
All of them, even some optimizations for the Vampire/Apollo 68080

**Comment by danboid** [comment]
Excellent!

That is the response I was hoping for. Maybe add a note that that is the case to the README?

**Comment by MBeijer** [comment]
You could always make a PR to add this information.

**Comment by danboid** [comment]
Will do.

Thanks
