### ISSUE TITLE
Cannot build on MacOS due to CC_FOR_BUILD error

### ISSUE THREAD

**Issue by hitman-codehq** [bebbo/amiga-gcc#373]
When following the instructions in https://github.com/bebbo/amiga-gcc/issues/367 and running contrib/download_prerequisites to download the right version of isl, I get the following error when building on MacOS:

```
checking how to run the C preprocessor... gcc -E
checking build system compiler gcc... no
configure: error: Specified CC_FOR_BUILD doesn't seem to work
gmake[1]: *** [Makefile:4561: configure-gmp] Error 1
make gcc...failed
```

There is no other useful information given.  Any ideas?

This ISL problem seems to be causing issues for quite a few people.  Should we patch the source to GCC so that it works with the new version?

[make gcc.log](https://github.com/bebbo/amiga-gcc/files/13783340/make.gcc.log)

**Comment by bebbo** [comment]
try
`export CC_FOR_BUILD=/path/to/working/gcc`
and use the path that matches your system.

seems to be some Xcode problem, similar as here: https://github.com/ghaerr/elks/issues/774
