### ISSUE TITLE
Arch Linux "make update" Problem

### ISSUE THREAD

**Issue by OwenTheBowen** [bebbo/amiga-gcc#375]
I'm having a problem building on Arch Linux. When I run "make update" it only runs this command:
```
cd /home/Steamranger/Automatic Build Scripts/Repository Builds/amiga-gcc/download && wget https://github.com/SDL-mirror/SDL_ttf/archive/SDL-1.2.tar.gz -O SDL_ttf-SDL-1.2.tar.gz
```
Then it outputs a **ton** of warnings and ends with these errors:
```
make: Circular /home/Steamranger/Automatic <- /home/Steamranger/Automatic dependency dropped.
make: Circular Build <- /home/Steamranger/Automatic dependency dropped.
make: Circular Build <- Build dependency dropped.
make: Circular Scripts/Repository <- /home/Steamranger/Automatic dependency dropped.
make: Circular Scripts/Repository <- Build dependency dropped.
make: Circular Scripts/Repository <- Scripts/Repository dependency dropped.
/usr/bin/bash: line 1: cd: too many arguments
make: *** [Makefile:1358: Builds/amiga-gcc/download/SDL_ttf-SDL-1.2.tar.gz] Error 1
```
I'm very confused as to what's happenning. My best guess would be that there's some kind of make compatibility problem, so for reference I'm using `make 4.4.1-2`.

**Comment by bebbo** [comment]
don't use white spaces in your path...

**Comment by OwenTheBowen** [comment]
I can confirm that removing spaces from my path has allowed me to run `make update`. I'll get back confirming if the rest of the build is succesful.

**Comment by OwenTheBowen** [comment]
I've managed to complete the build successfully, using an additional fix mentioned in [this issue.](https://github.com/bebbo/amiga-gcc/issues/357).
