### ISSUE TITLE
gcc build fails on Fedora 39

### ISSUE THREAD

**Issue by Q-coder** [bebbo/amiga-gcc#383]
Trying to compile gcc fails on Fedora 39 attached is the build log.
I'm running Fedora for Arm on VMware Fusion 13 on an M2 Macbook pro.
[make gcc.log](https://github.com/bebbo/amiga-gcc/files/14156074/make.gcc.log)

I did follow the read.me guide and also ran:
contrib/download_prerequisites

Maybe just to mention it compiles correctly on Ubuntu-64 for Arm Server 22.04.3 with the same Fusion 13 on the same M2 Macbook pro.

**Comment by bebbo** [comment]
That's an issue with your environment. Please ask in an Fedora/M2 forum.
