### ISSUE TITLE
gcc build fails in graphite-isl-ast-to-gimple.c

### ISSUE THREAD

**Issue by supernobby** [bebbo/amiga-gcc#386]
Hi,
maybe more a question than an issue. But I try to build things with "make all". But the gcc build fails with:

`/media/Data/nobby/Builds/amiga-gcc/projects/gcc/gcc/graphite-isl-ast-to-gimple.c: In Elementfunktion »tree_node* translate_isl_ast_to_gimple::gcc_expression_from_isl_expr_int(tree, isl_ast_expr*)«:
/media/Data/nobby/Builds/amiga-gcc/projects/gcc/gcc/graphite-isl-ast-to-gimple.c:349:3: Fehler: »isl_val_free« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »isl_vec_free«?
  349 |   isl_val_free (val);
      |   ^~~~~~~~~~~~
      |   isl_vec_free
/media/Data/nobby/Builds/amiga-gcc/projects/gcc/gcc/graphite-isl-ast-to-gimple.c: In Funktion »isl_ast_expr* get_upper_bound(isl_ast_node*)«:
/media/Data/nobby/Builds/amiga-gcc/projects/gcc/gcc/graphite-isl-ast-to-gimple.c:752:11: Fehler: »isl_val_int_from_si« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »isl_val_int_from_gmp«?
`
I am on Arch Linux and the ISL package installed is 0.26 as far as I can say. I found this [bug report](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113188) , talking about, that this could be too new. But what version of ISL is required? [GCC prerequisites](https://gcc.gnu.org/install/prerequisites.html) talks about at least 0.15. But the [infrastructure](https://gcc.gnu.org/pub/gcc/infrastructure/) folder has several versions. And if I download one of the still compatible ISL package version, how can I corretly supply the path to it to the build process?

Thanks,
Andreas

**Comment by bebbo** [comment]
Enter the `contrib` folder of `gcc` and execute `download_prerequisites`.

**Comment by supernobby** [comment]
Thanks, this worked!
