### ISSUE TITLE
Question: Optional libraries... possible?

### ISSUE THREAD

**Issue by anchor76** [bebbo/amiga-gcc#388]
Hello,

Not an issue, but question: Is it possible to use a library optionally? I would like to use picasso96API.library optionally.
So if it's not installed, just skip it, and use intuition + graphics libraries. As i see if a referenced lib is unable to open, the app is not starting. (failing with openlibrary() error at startup)

Is there any compile option for this?

Thanks :)

**Comment by bebbo** [comment]
You have to open that library by yourself. To disable the auto opening for a library, define and initialize that library in your code:

```
struct Library *P96Base = 0;
```

Then open/close it yourself and use it, if available.

**Comment by anchor76** [comment]
Thanks for your quick response :)
