### ISSUE TITLE
@isoriano1968 - "make min" in a pristine  repo (and sub project repos) seems to be OK.  I'll open another issue for the oddities I noticed.

### ISSUE THREAD

**Issue by isoriano1968** [bebbo/amiga-gcc#390]
@isoriano1968 - "make min" in a pristine  repo (and sub project repos) seems to be OK.  I'll open another issue for the oddities I noticed.

_Originally posted by @nbriggs in https://github.com/bebbo/amiga-gcc/issues/258#issuecomment-1565709590_

Hi,

did you had the chance to dig into this topic again? 

Recent tries on OpenIndiana and Solaris 11.4.42 CBE with the 13.1 and 13.2 branches still fail at fd2sfd.

Btw. added an

ifeq ($(UNAME_S) SunOS)

to the Makefile to get it starting and the .repos was missing the proper gcc URL when issuing a

gmake branch branch=amiga13.2 mod=gcc

Cheers

Iggi

**Comment by nbriggs** [comment]
I have not been back to this recently.  The project that was doing the amiga-gcc cross-compiling on Solaris is currently dormant.  I'll try to remember to put a note back here if anything happens.
