### ISSUE TITLE
Update VASM (1.9a to 1.9f)

### ISSUE THREAD

**Issue by erique** [bebbo/amiga-gcc#398]
`default-repos` for vasm currently points to [`mheyer32/vasm`](https://github.com/mheyer32/vasm) ; vasm1.9a.
This version is a bit older than the latest available from http://sun.hasenbraten.de/vasm, which is 1.9f.

Unless there is a specific reason to keep it at 1.9a (regressions in 1.9f?) it would probably worth upgrading it..

**Comment by bebbo** [comment]
Sorry, I can't update repos of other persons.
Open a ticket there.

**Comment by erique** [comment]
Yeah - I understand that ;)

But afaict [mheyer32/vasm](https://github.com/mheyer32/vasm) is not an official repo either so perhaps worth pointing that elsewhere.
Even the upstream of mheyer32/vasm (which is a fork of [Leffmann/vasm](https://github.com/Leffmann/vasm)) is more recent (albeit also not an official repo, I think)

**Comment by bebbo** [comment]
You can change where your checked out vasm points to.
Maybe you can convince the vasm owners to create an official repo?
