### ISSUE TITLE
Building amiga-gcc fails at making binutils on aarch64-linux-android

### ISSUE THREAD

**Issue by PTz0uAH** [bebbo/amiga-gcc#401]
Hoi Stefan.. I cannot complete the minimal build due to errors..

sys: aarch64-linux-android
flavour: termux on android 13
gcc: 10
binutils: 2.42

I am building a cross dev environment on my android device.. vbcc, vasm(1.9f) vlink work fine and allowed me to create the crosscompiler needed to crossbuild from trunk, the full distri of FreePascal compiler v3.3.1 for m68k Amiga..

Now I really miss amiga-gcc in my collection of cross dev tools.. it builds fine on WSL but I prefer to have it all available on the 8GB RAM tablet device..

Tried to get it to work but the build process stopped during the binutils build.. so can you please take a look at it.. would appreciate it very much..

with kind regards.. Peter

![debug_make_min_amiga-gcc_001](https://github.com/user-attachments/assets/97235ee5-1d2f-4cd3-be56-687f77285b44)

**Comment by bebbo** [comment]
I guess that configure already did something wrong, since HAVE_BFD_ELF must be undefined.

**Comment by bebbo** [comment]
please provide a bluestacks VM to reproduce.
