### ISSUE TITLE
GCC 13.2 failes to generate proper binary: m68k-amigaos-strip: ./hello: file format not recognized

### ISSUE THREAD

**Issue by pottendo** [bebbo/amiga-gcc#406]
hi,
this ticket is close to this: https://github.com/bebbo/amiga-gcc/issues/402
however, here my observation. 
I've followed the instruction to build gcc-13.2. 
The resulting binaries generated by this gcc build seem to be not right:
```
pottendo@vm:~/gh$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble
pottendo@vm:~/gh$ /opt/amiga-gcc13/bin/m68k-amigaos-gcc -g -Wall -N -o hello hello.c
pottendo@vm:~/gh$ ls -l hello
-rwxrwxr-x 1 pottendo pottendo 18460 Oct  2 14:17 hello
pottendo@vm:~/gh$ file hello
hello: AmigaOS loadseg()ble executable/binary
pottendo@vm:~/gh$ /opt/amiga-gcc13/bin/m68k-amigaos-strip ./hello
/opt/amiga-gcc13/bin/m68k-amigaos-strip: ./hello: file format not recognized
pottendo@vm:~/gh$ /opt/amiga-gcc13/bin/m68k-amigaos-gcc -v
Using built-in specs.
COLLECT_GCC=/opt/amiga-gcc13/bin/m68k-amigaos-gcc
COLLECT_LTO_WRAPPER=/opt/amiga-gcc13/libexec/gcc/m68k-amigaos/13.2.0/lto-wrapper
Target: m68k-amigaos
Configured with: /home/pottendo/gh/amiga-gcc/projects/gcc/configure --prefix=/opt/amiga-gcc13 --target=m68k-amigaos --enable-languages=c,c++,objc, --enable-version-specific-runtime-libs --disable-libssp --disable-nls --with-headers=/home/pottendo/gh/amiga-gcc/projects/newlib-cygwin/newlib/libc/sys/amigaos/include/ --disable-shared --enable-threads=no --with-stage1-ldflags='-dynamic-libgcc -dynamic-libstdc++' --with-boot-ldflags='-dynamic-libgcc -dynamic-libstdc++'
Thread model: single
Supported LTO compression algorithms: zlib
gcc version 13.2.0 (GCC) 
pottendo@vm:~/gh$ /opt/amiga-gcc13/bin/m68k-amigaos-strip --version
GNU strip (GNU Binutils) 2.39.0.240624-095649
Copyright (C) 2022 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
```

I've not (yet) tried to run that exact binary on my Amiga setup. However, I did observe this already with gcc-13.1 and trying to run it back then, it failed to run on the Amiga with some error code, similar as reported in the other ticket.

I've used `-N` above, as I read that this may improve image size. Removing it on the gcc commandline above doesn't make a difference.
Gcc 6.x generates running binaries (tested on Kick13 and newer).

bye, pottendo

Here `hello.c`:
```
#include <stdio.h>

int main(int argc, char *argv[])
{
  printf("hello world\n");
  return 0;
}
```

**Comment by bebbo** [comment]
please retest

**Comment by bebbo** [comment]
thank you for reporting, kick 1.3 should link again now.

**Comment by bebbo** [comment]
you need to run `make clean-libnix && make libnix`

**Comment by pottendo** [comment]
hi, 
thanks for the quick response.
`-mcrt=nix13` works now for C programs. 

For C++ a bit more tricks around locale is needed, but as the binaries are that big as soon as something from the C++ libs is used, the whole sense is screwed to use C++ for kick13 (aka the platform for A500's, which seldomly exceed the 1MB memory). If you have an Amiga (500 or newer) pimped with more memory, you probably can also use Kick2 or later ROMs, if C++ is your desire.
I worked around locally in my tree, but probably not the way as it should be done:
add  `	$(root)/sources/nix20/locale/setlocale.c \`  to steal.me
and in this `setlocale.c`:
remove the `#ifndef __KICK13__` and corresponding `#endif`
add `unsigned char *_ctype_;` somewhere in the beginning.

for sure that's not correct, but at least I can build C++ apps now for all kickXX roms.

happy hacking, pottendo

**Comment by pottendo** [comment]
Thanks for the fixes and hints!

Minor issue still left for C++.
C++ with Kick13 fails when touching locale, e.g. when iostream is included (as my testcase had):
```
/opt/amiga13/bin/m68k-amigaos-g++ -mcrt=nix13 -N -o hello-cpp hello-cpp.o
/opt/amiga13/lib/gcc/m68k-amigaos/13.2.0/../../../../m68k-amigaos/bin/ld: /opt/amiga13/lib/gcc/m68k-amigaos/13.2.0/libstdc++.a(ctype_configure_char.o): in function `_EH_FRAME_BEGIN__':
ctype_configure_char.o:(.text._ZNSt5ctypeIcE13classic_tableEv+0x2): undefined reference to `_ctype_'
/opt/amiga13/lib/gcc/m68k-amigaos/13.2.0/../../../../m68k-amigaos/bin/ld: ctype_configure_char.o:(.text._ZNSt5ctypeIcEC2EPiPKcbm+0x7a): undefined reference to `_ctype_'
/opt/amiga13/lib/gcc/m68k-amigaos/13.2.0/../../../../m68k-amigaos/bin/ld: ctype_configure_char.o:(.text._ZNSt5ctypeIcEC1EPiPKcbm+0x7a): undefined reference to `_ctype_'
/opt/amiga13/lib/gcc/m68k-amigaos/13.2.0/../../../../m68k-amigaos/bin/ld: ctype_configure_char.o:(.text._ZNSt5ctypeIcEC2EPKcbm+0x7a): undefined reference to `_ctype_'
/opt/amiga13/lib/gcc/m68k-amigaos/13.2.0/../../../../m68k-amigaos/bin/ld: ctype_configure_char.o:(.text._ZNSt5ctypeIcEC1EPKcbm+0x7a): undefined reference to `_ctype_'

```
I know, it's useless (for me)... still worth to report, imho.

It works when building for Kick2 or newer.

bye, pottendo

**Comment by bebbo** [comment]
builds and runs now with `-mcrt=nix13` and also with `-mcrt=library`
