### ISSUE TITLE
Link-time optimizations ain't working

### ISSUE THREAD

**Issue by tehKaiN** [bebbo/amiga-gcc#41]
When building with `-flto` added to gcc flags I get:

```
Building src/ace/managers/timer.c
AppData/Local/Temp/cc8OKrbX.s: Assembler messages:
AppData/Local/Temp/cc8OKrbX.s:2: Error: unknown pseudo-op: `.gnu.lto_.profile.f22a9330a406fcee'
AppData/Local/Temp/cc8OKrbX.s:5: Error: unknown pseudo-op: `.gnu.lto_.icf.f22a9330a406fcee'
AppData/Local/Temp/cc8OKrbX.s:10: Error: unknown pseudo-op: `.gnu.lto_.jmpfuncs.f22a9330a406fcee'
AppData/Local/Temp/cc8OKrbX.s:17: Error: unknown pseudo-op: `.gnu.lto_.inline.f22a9330a406fcee'
AppData/Local/Temp/cc8OKrbX.s:27: Error: unknown pseudo-op: `.gnu.lto_.pureconst.f22a9330a406fcee'
AppData/Local/Temp/cc8OKrbX.s:30: Error: unknown pseudo-op: `.gnu.lto_timercreate.f22a9330a406fcee'
AppData/Local/Temp/cc8OKrbX.s:37: Error: unknown pseudo-op: `.gnu.lto_g_stimermanager.f22a9330a406fcee'
AppData/Local/Temp/cc8OKrbX.s:41: Error: unknown pseudo-op: `.gnu.lto_timerdestroy.f22a9330a406fcee'
AppData/Local/Temp/cc8OKrbX.s:49: Error: unknown pseudo-op: `.gnu.lto_timerget.f22a9330a406fcee'
AppData/Local/Temp/cc8OKrbX.s:63: Error: unknown pseudo-op: `.gnu.lto_timeroninterrupt.f22a9330a406fcee'
AppData/Local/Temp/cc8OKrbX.s:73: Error: unknown pseudo-op: `.gnu.lto_timergetprec.f22a9330a406fcee'
AppData/Local/Temp/cc8OKrbX.s:103: Error: unknown pseudo-op: `.gnu.lto_timergetdelta.f22a9330a406fcee'
AppData/Local/Temp/cc8OKrbX.s:120: Error: unknown pseudo-op: `.gnu.lto_timerpeek.f22a9330a406fcee'
AppData/Local/Temp/cc8OKrbX.s:131: Error: unknown pseudo-op: `.gnu.lto_timercheck.f22a9330a406fcee'
AppData/Local/Temp/cc8OKrbX.s:152: Error: unknown pseudo-op: `.gnu.lto_timerprocess.f22a9330a406fcee'
AppData/Local/Temp/cc8OKrbX.s:176: Error: unknown pseudo-op: `.gnu.lto_timerformatprec.f22a9330a406fcee'
AppData/Local/Temp/cc8OKrbX.s:196: Error: unknown pseudo-op: `.gnu.lto_timerwaitus.f22a9330a406fcee'
AppData/Local/Temp/cc8OKrbX.s:210: Error: unknown pseudo-op: `.gnu.lto_.symbol_nodes.f22a9330a406fcee'
AppData/Local/Temp/cc8OKrbX.s:216: Error: unknown pseudo-op: `.gnu.lto_.refs.f22a9330a406fcee'
AppData/Local/Temp/cc8OKrbX.s:221: Error: unknown pseudo-op: `.gnu.lto_.decls.f22a9330a406fcee'
AppData/Local/Temp/cc8OKrbX.s:302: Error: unknown pseudo-op: `.gnu.lto_.symtab.f22a9330a406fcee'
AppData/Local/Temp/cc8OKrbX.s:388: Error: unknown pseudo-op: `.gnu.lto_.opts'
```

Setting `-fbbb=-` doesn't help, so it's not something that you messed up, my guess is it's rather unimplemented. Anything to do about it?

PS. Don't you miss our noobish questions on slack? 'cuz we miss asking them ;)

**Comment by bebbo** [comment]
Maybe I'll work on lto...
... and maybe I'm missing slack.

**Comment by mheyer32** [comment]
This could potentially help ScummVM alot - mostly for executable size.
 It has a lot of code that'll eventually be unused in Amiga executable, but as far as I understand the linker currently does not do 'tree shaking' to remove unused functions.

**Comment by bebbo** [comment]
having `-flto` support will also allow to specify `-fwhole-program`.

For `tscp181` it yields a ~2.5% smaller executable but no gain in performance.

**Comment by mheyer32** [comment]
This is exciting! :-D Thanks!
I updated to the latest top-of-tree Amiga-GCC and it works out of the box.

But bad news is, when adding -flto to the CXXFLAGS and LDFLAGS in the ScummVM configure script, the configure step will hang indefinitely in a "lto-wrapper" process :-(

**Comment by bebbo** [comment]
so configure is broken, no?^^

**Comment by bebbo** [comment]
I should learn how to copy my own code^^
configure is working again

**Comment by bebbo** [comment]
@mheyer32: the current Makefile won't work since lto files in libs are not supported.

**Comment by mheyer32** [comment]
So, this is to be expected in case of ScummVM? (It only happens with LTO enabled)
If so, I'm cool with it, just going to wait until libs are working. If this is not expected, I can prepare a full bug report.

```
make: *** [engines/scumm/bomp.o] Error 1
In file included from ./engines/scumm/scumm.h:28:0,
                 from engines/scumm/boxes.cpp:23:
./common/endian.h:233:10: internal compiler error: in mangle_decl, at cp/mangle.c:3659
   struct Unaligned16 { uint16 val; } __attribute__ ((__packed__, __may_alias__));
          ^~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
Makefile.common:121: recipe for target 'engines/scumm/boxes.o' failed
```

**Comment by bebbo** [comment]
uhm, isn't this already fixed?

**Comment by mheyer32** [comment]
Oh, there was another update in meantime (you're too fast! ;-) )... let me check and get back to you.

**Comment by bebbo** [comment]
you could expand the scummvm local libs into objects and specify the objects. I think @files will do, one per lib,
having lto for libs requires lto as linker plugin...
... more work

**Comment by tehKaiN** [comment]
and having LTO for libs is exactly what I need ;)

**Comment by mheyer32** [comment]
Confirmed, ScummVM get s past the internal compiler error now!

To clear things: when we're talking about libs, we talk about .a files, right?

**Comment by bebbo** [comment]
libs = .a file.

The problems won't end there - they will start^^.

you can try exporting all .o files from thelib.a, create a file listfile with all .o names in it, then use @listfile instead of the thelib.a

**Comment by tehKaiN** [comment]
or "just" put whole lib in single .c file and compile to single .o file. Each of such approaches requires additional, unconventional build steps. :(

**Comment by bebbo** [comment]
Now I understand:

  -flto is a superfluous braid that belongs cut off

**Comment by mheyer32** [comment]
Hu, what just happened?

**Comment by bebbo** [comment]
When I feel pissed off by someone, I close their tickets and banish them.

Please open your own tickets if you have issues.
