### ISSUE TITLE
ndk13 has incomplete GfxBase

### ISSUE THREAD

**Issue by tehKaiN** [bebbo/amiga-gcc#42]
While compiling using `#include <graphics/gfxbase.h>`:

```
68k-amigaos/ndk13-include/graphics/gfxbase.h:119:30: error: field 'MonitorVBlank' has incomplete type
  struct AnalogSignalInterval MonitorVBlank;
```

from what I've gathered monitor.h is empty on nix13. Filling it with with content from e.g. [here](http://amiga.nvg.org/amiga/reference/Includes_and_Autodocs_2._guide/node00A7.html) solves this problem.

**Comment by SamuraiCrow** [comment]
Those are from Kickstart 2.04 since 1.3 didn't have those functions.

**Comment by tehKaiN** [comment]
Still, `GfxBase` needs `AnalogSignalInterval`, so either `GfxBase` should be smaller on 1.3 or something is missing.

**Comment by dwhinham** [comment]
The workaround I've been using for now is to copy the file `m68k-amigaos\ndk-include\graphics\monitor.h` to `m68k-amigaos\ndk13-include\graphics\monitor.h`, overwriting the empty file.

Would be really nice to get this fixed though. 😄

**Comment by bebbo** [comment]
please test

**Comment by dwhinham** [comment]
Works fine for me - thanks!

Just added a `-D__KICK13__` in my CFLAGS for VBCC (my project builds with both compilers using your installer).
