### ISSUE TITLE
make: *** No rule to make target 'projects/newlib-cygwin/configure', needed by 'build/newlib/newlib/Makefile'.  Stop.

### ISSUE THREAD

**Issue by tschak909** [bebbo/amiga-gcc#44]
This happens even when building under Linux. :(

-Thom

**Comment by bebbo** [comment]
That is not a useful bug description - sorry

**Comment by bebbo** [comment]
no feedback

**Comment by anchor76** [comment]
hello, i getting the same problem under cygwin32.
"make: *** No rule to make target 'projects/newlib-cygwin/configure', needed by 'build-CYGWIN_NT-6.1-WOW/newlib/newlib/Makefile'.  Stop."

there is no "newlib-cygwin" folder in projects/, and no "newlib" folder in build-CYGWIN_NT-6.1-WOW/.

i had problem with vbcc_target_m68k-amigaos.lha too. i had to create a "download" folder.

**Comment by bebbo** [comment]
run
```
git pull
make clean
make update
make all
```
as separate commands

**Comment by anchor76** [comment]
ah, thanks! it seems the "make update" is mandatory before "make all".
