### ISSUE TITLE
make all borks under cygwin with spurious newlines in makefile

### ISSUE THREAD

**Issue by tschak909** [bebbo/amiga-gcc#45]
cd build/binutils && CFLAGS="-Os" CPPFLAGS="-Os" CXXFLAGS="-Os" LIBCFLAGS_FOR_TARGET="-Os -g -fomit-frame-pointer" /home/thomc/Workspace/amiga-gcc/projects/binutils/configure --prefix=/opt/amiga --target=m68k-amigaos --disable-plugins --disable-werror
/home/thomc/Workspace/amiga-gcc/projects/binutils/configure: line 14: $'\r': command not found
/home/thomc/Workspace/amiga-gcc/projects/binutils/configure: line 29: syntax error near unexpected token `newline'
'home/thomc/Workspace/amiga-gcc/projects/binutils/configure: line 29: `     ;;
make: *** [Makefile:346: build/binutils/gas/Makefile] Error 2

-Thom

**Comment by tschak909** [comment]
So where is this toolchain supposed to work ,exactly? I have tried to build this under multiple systems, and there is something broken in each of them. sigh.

-Thom

**Comment by bebbo** [comment]
Please provide all information that's necessary to redo your problem.

**Comment by bebbo** [comment]
no feedback
