### ISSUE TITLE
-m68020-40 and -m68020-60 don't link libnix libm020

### ISSUE THREAD

**Issue by githubaf** [bebbo/amiga-gcc#47]
I compile with libnix for different CPUs.
When I start a program compiled for a higher CPU I get usually the message 'Need a 68020 or higher CPU', and that is what I expect.

When I however compile with either -m68020-40 or -m68020-60 this does not happen!

I looked at the linker and it does
-m68020
(/home/osboxes/opt/m68k-amigaos_03Aug18/lib/gcc/m68k-amigaos/6.4.1b/../../../../m68k-amigaos/lib/libm020/libstubs.a)__cpucheck.o
 
-m68020-60
(/home/osboxes/opt/m68k-amigaos_03Aug18/lib/gcc/m68k-amigaos/6.4.1b/../../../../m68k-amigaos/lib/libstubs.a)__cpucheck.o

So I seem to get the wrong cpucheck...

I guess there is something missing in the spec-file?

**Comment by bebbo** [comment]
the specs are a mess...
... hang on

**Comment by githubaf** [comment]
Tested sucessfully with you last commit fro 24.10.
e8ea2d8c2cf1cc6b0775f00138db0dbf3b08bdd3

Thanks!
