### ISSUE TITLE
Please un-archive libdebug to allow for pull requests

### ISSUE THREAD

**Issue by mheyer32** [bebbo/amiga-gcc#48]
Please consider un-archiving libdebug. I have found a bug in there and like to contribute a pull request. Thank you!

https://github.com/mheyer32/libdebug/commit/8a898f8f91385be3dcc7eee10b24b3fda3a70ed3

**Comment by bebbo** [comment]
unarchived

**Comment by mheyer32** [comment]
Thanks! Closing.
