### ISSUE TITLE
Profiling: orphaned memcpy() and strange percentages after struct passed by value

### ISSUE THREAD

**Issue by githubaf** [bebbo/amiga-gcc#59]
I further experimented with -pg.
It looks quite good for simple tests. (nested function calls, functions with many parameters, recursive functions, lots of variables inside functions etc.

Eventually I tried to pass a struct by value to a function.
Now I see a lonely memcpy() in the tree (apparently) called by nobody. The memcopy propably copies the struct, but shouldn't it come from main then?
Additionally the percentage values now look strange to me.
![output](https://user-images.githubusercontent.com/28429123/49016922-cc950f80-f187-11e8-8a18-1e5989d49732.png)
[profiler_main.c.gz](https://github.com/bebbo/amiga-gcc/files/2615737/profiler_main.c.gz)

**Comment by bebbo** [comment]
if you want the library functions in the graph, then build these libraries with `-pg`.

**Comment by githubaf** [comment]
Maybe a misunderstanding.

I did no want to see all library-functions (at the moment). I was surprised to see that memcpy() at all!
And furthermore I am surprised that main does not consume 100%

I will try to build libnix with -pg and see, what happens...

**Comment by githubaf** [comment]
I see. Its not very comfortable if it necessary to rebuild the library/ies before using the profiler, but on the other hand it gives an interesting picture at the end.
With your fix the tree starts with _stext but the (never intentionally called) memcpy is still lose on the top.
![output3](https://user-images.githubusercontent.com/28429123/49051381-ef571080-f1e7-11e8-9d30-d7aca8915bb8.png)

When trying again with -pg recompiled libnix we get a nice interesting picture.
(I am not sure about _exitcpp and _initcpp (the example has only a c source)) 
![output4](https://user-images.githubusercontent.com/28429123/49051418-144b8380-f1e8-11e8-8fda-4e5ca91fd4e0.png)

**Comment by bebbo** [comment]
nice diagram, isn't it?

The reason `__initcpp` and `__exitcpp` are showing up as loose nodes is its call via asm, which does not use the framepointer.

And since there is only one startup regardless if you link, it's ok that `__initcpp` and `__exitcpp` are invoked. There are few more functions which are invoked during start/exit. Due to the timer's resolution not all show up.

**Comment by githubaf** [comment]
Ok, thanks for the clarification!
