### ISSUE TITLE
cybergraphics.h looking for non-existant header

### ISSUE THREAD

**Issue by mheyer32** [bebbo/amiga-gcc#6]
```
In file included from amiga_video.c:6:0:
/home/matze/amigatoolchain/amiga-gcc-out/m68k-amigaos/include/proto/cybergraphics.h:6:34: fatal error: clib/cybergfx_protos.h: No such file or directory
 #include <clib/cybergfx_protos.h>
```

I found it under a different name, though:

```
matze@ubuntu-VirtualBox:~/amigatoolchain/amiga-gcc-out$ find ./ -name cybergraphics_protos.h
./m68k-amigaos/include/clib/cybergraphics_protos.h

```

**Comment by bebbo** [comment]
the archive from aminet contains:
```
[generic]                  661    2368  27.9% -lh5- 5f58 Jul 15  1998 CGraphX/C/Include/clib/cybergraphics_protos.h
```

So I suggest you fix it in your code.

**Comment by mheyer32** [comment]
The problem is not that cybergraphics_protos.h does not exist. The problem is  that proto/cybergraphics.h tries to include "clib/cybergfx_protos.h"

/home/matze/amigatoolchain/amiga-gcc-out/m68k-amigaos/include/proto/cybergraphics.h  is not my code.

I'll try rebuilding the toolchain and see if it helps.

**Comment by bebbo** [comment]
sfdc is using the library name to create the includes...
... I extended the sdk format perform an optional rename

PUSH

please test and reinstall the cgx.sdk

**Comment by mheyer32** [comment]
Thanks! That fixed it :-)
