### ISSUE TITLE
Profiling: main() vanishes from tree when using optimization

### ISSUE THREAD

**Issue by githubaf** [bebbo/amiga-gcc#63]
While playing with function pointers (that work correctly in this example) main() suddenly disappeared from the call tree when using an optimization other than -O0.

In previous examples the tree usually started with_stext  calling main.
In the attached example the tree starts either directly with main() (-O0) or with fct_1() (-O2, -O3)

So no s_text nor main any longer. Is that normal?

![output](https://user-images.githubusercontent.com/28429123/49466176-aadafe80-f7ff-11e8-9489-68a64c2f1d88.png)
 

[test.tar.gz](https://github.com/bebbo/amiga-gcc/files/2645669/test.tar.gz)

**Comment by bebbo** [comment]
I get
```
index % time    self  children    called     name
                0.00    0.00       1/1           main [52]
[1]      0.0    0.00    0.00       1         fct_1 [1]
                0.00    0.00       1/1           fct_2 [2]                                                                                                                                   ```

**Comment by githubaf** [comment]
I see. So it might be a problem of gprof2dot visualizer? I just asked there.

**Comment by bebbo** [comment]
any news here?

**Comment by githubaf** [comment]
I opened an issue here:
https://github.com/jrfonseca/gprof2dot/issues/55

No comments do far.

**Comment by bebbo** [comment]
please retest

**Comment by bebbo** [comment]
you might retest this due to the recent changes, no?

**Comment by githubaf** [comment]
We just got a reply from https://github.com/jrfonseca/gprof2dot/issues/55

> 
> There are 2 problems here:
> 
>     gprof couldn't figure out who called strlen. Perhaps because libc had no debug information, or due to some limitation with m68k architecture (e.g., no stack frame pointer by default)?
> 
>     gprof lists main as a caller (ie, an edge on the call graph), but didn't create a node for it in the report. No idea why. I never seen this with x86. Perhaps gprof's -c/--static-call-graph help.
> 
> Both issues are in gcc/gprof domain, not the gprof2dot tool. The missing main issue is minor IMO. But the strlen is a showstopper -- if time spent in libc functions is not accurately billed to the callers, then the whole graph will end up biased and useless.
> 
> I hope this helps.
>

**Comment by bebbo** [comment]
then you need libs compiled with -pg.
not a real issue.

**Comment by githubaf** [comment]
I don't understand why main gets lost when compiling with any optimization level, but yes, it seems compiling libnix with -pg seems to help. So we can close this issue.

Would it make sense to compile the libs (libnix) additionally with -pg during toolchain-installation and use this -pg-compiled version automatically when compiling an executable with -pg?

(I currently build two versions (-g and -pg) of libnix into different directories and have a symbolic link "libnix" pointing to of these two directories)
