### ISSUE TITLE
compiling for profile guided optimization?

### ISSUE THREAD

**Issue by githubaf** [bebbo/amiga-gcc#65]
I' not shure if it's just my incorrect usage.
I try to compile/link with -fprofile-generate
When the program is ran a profile should be generated that can then be used in a secomd compilation for better optimization by usage of -fprofile-use.

I compile s simple hello-world program with the following command line:

`~/opt/m68k-amigaos_19Dec18/bin/m68k-amigaos-gcc test2.c  -o test2  -fprofile-generate=$(pwd | cut -c2-)  # remove first "/" from pwd -> VBox:home/...`

Compilation stops with several __gcov_something linker errors. On linux gcc does not need any other options.

Is that supposed to work that way?

**Comment by bebbo** [comment]
` -lgcov`

**Comment by githubaf** [comment]
I see. I was experimenting and was confused by error messages.
-lgcov is necessary for -fprofile-generate as you wrote.
When using -fprofile-use in the next compiler run we have to add
-Wno-error=coverage-mismatch because we have different path on linux and on (emulated) amiga.

And it indeed can optimize a little bit better with fprofile-use!

I wonder how to write a reasonable Makefile for this scenario...
compiling/linking with -fprofile-generate and -lgcov
run the program (maybe via vamos?)
compiling/linking with -fprofile-use
