### ISSUE TITLE
compiling problem with cygwin32

### ISSUE THREAD

**Issue by anchor76** [bebbo/amiga-gcc#67]
hello, i got compile error at some point.

output:

$ make all PREFIX=/opt/m68k-amigaos-bebbo
configure binutils...done
make binutils...done
install binutils...done
configure gcc...done
make gcc...done
install gcc...done
configure gprof...done
make gprof...done
install gprof...done
configure fd2sfd...done
make fd2sfd...done
install fd2sfd...done
make fd2sfd...done
install fd2sfd...done
make ira...done
install ira...done
configure sfdc...done
make sfdc...done
install sfdc...done
make vbcc dtgen...done
run vbcc dtgen...done
make vbcc...done
install vbcc...done
make vasm...done
install vasm...done
make vlink...done
install vlink...done
downloading vbcc_target...done
unpack vbcc_target_m68k-amigaos...done
copying vbcc headers...done
copying vbcc headers...done
creating vbcc config...done
configure newlib...done
sfdc inline amigaguide.h...done
sfdc inline aml.h...done
sfdc inline arexx.h...done
sfdc inline asl.h...done
sfdc inline battclock.h...done
sfdc inline battmem.h...done
sfdc inline bevel.h...done
sfdc inline bitmap.h...done
sfdc inline bullet.h...done
sfdc inline button.h...done
sfdc inline card.h...done
sfdc inline checkbox.h...done
sfdc inline chooser.h...done
sfdc inline cia.h...done
sfdc inline clicktab.h...done
sfdc inline colorwheel.h...done
sfdc inline commodities.h...done
sfdc inline console.h...done
sfdc inline datatypes.h...done
sfdc inline datebrowser.h...done
sfdc inline diskfont.h...done
sfdc inline disk.h...done
sfdc inline dos.h...done
sfdc inline drawlist.h...done
sfdc inline dtclass.h...done
sfdc inline exec.h...done
sfdc inline expansion.h...done
sfdc inline fuelgauge.h...done
sfdc inline gadtools.h...done
sfdc inline getfile.h...done
sfdc inline getfont.h...done
sfdc inline getscreenmode.h...done
sfdc inline glyph.h...done
sfdc inline graphics.h...done
sfdc inline icon.h...done
sfdc inline iffparse.h...done
sfdc inline input.h...done
sfdc inline integer.h...done
sfdc inline intuition.h...done
sfdc inline keymap.h...done
sfdc inline label.h...done
sfdc inline layers.h...done
sfdc inline layout.h...done
sfdc inline listbrowser.h...done
sfdc inline locale.h...done
sfdc inline lowlevel.h...done
sfdc inline mathffp.h...done
sfdc inline mathieeedoubbas.h...done
sfdc inline mathieeedoubtrans.h...done
sfdc inline mathieeesingbas.h...done
sfdc inline mathieeesingtrans.h...done
sfdc inline mathtrans.h...done
sfdc inline misc.h...done
sfdc inline nonvolatile.h...done
sfdc inline palette.h...done
sfdc inline penmap.h...done
sfdc inline popcycle.h...done
sfdc inline potgo.h...done
sfdc inline radiobutton.h...done
sfdc inline ramdrive.h...done
sfdc inline realtime.h...done
sfdc inline requester.h...done
sfdc inline resource.h...done
sfdc inline rexxsyslib.h...done
sfdc inline scroller.h...done
sfdc inline slider.h...done
sfdc inline space.h...done
sfdc inline speedbar.h...done
sfdc inline string.h...done
sfdc inline texteditor.h...done
sfdc inline timer.h...done
sfdc inline translator.h...done
sfdc inline utility.h...done
sfdc inline virtual.h...done
sfdc inline wb.h...done
sfdc inline window.h...done
sfdc lvo amigaguide_lib.i...done
sfdc lvo aml_lib.i...done
sfdc lvo arexx_lib.i...done
sfdc lvo asl_lib.i...done
sfdc lvo battclock_lib.i...done
sfdc lvo battmem_lib.i...done
sfdc lvo bevel_lib.i...done
sfdc lvo bitmap_lib.i...done
sfdc lvo bullet_lib.i...done
sfdc lvo button_lib.i...done
sfdc lvo card_lib.i...done
sfdc lvo checkbox_lib.i...done
sfdc lvo chooser_lib.i...done
sfdc lvo cia_lib.i...done
sfdc lvo clicktab_lib.i...done
sfdc lvo colorwheel_lib.i...done
sfdc lvo commodities_lib.i...done
sfdc lvo console_lib.i...done
sfdc lvo datatypes_lib.i...done
sfdc lvo datebrowser_lib.i...done
sfdc lvo diskfont_lib.i...done
sfdc lvo disk_lib.i...done
sfdc lvo dos_lib.i...done
sfdc lvo drawlist_lib.i...done
sfdc lvo dtclass_lib.i...done
sfdc lvo exec_lib.i...done
sfdc lvo expansion_lib.i...done
sfdc lvo fuelgauge_lib.i...done
sfdc lvo gadtools_lib.i...done
sfdc lvo getfile_lib.i...done
sfdc lvo getfont_lib.i...done
sfdc lvo getscreenmode_lib.i...done
sfdc lvo glyph_lib.i...done
sfdc lvo graphics_lib.i...done
sfdc lvo icon_lib.i...done
sfdc lvo iffparse_lib.i...done
sfdc lvo input_lib.i...done
sfdc lvo integer_lib.i...done
sfdc lvo intuition_lib.i...done
sfdc lvo keymap_lib.i...done
sfdc lvo label_lib.i...done
sfdc lvo layers_lib.i...done
sfdc lvo layout_lib.i...done
sfdc lvo listbrowser_lib.i...done
sfdc lvo locale_lib.i...done
sfdc lvo lowlevel_lib.i...done
sfdc lvo mathffp_lib.i...done
sfdc lvo mathieeedoubbas_lib.i...done
sfdc lvo mathieeedoubtrans_lib.i...done
sfdc lvo mathieeesingbas_lib.i...done
sfdc lvo mathieeesingtrans_lib.i...done
sfdc lvo mathtrans_lib.i...done
sfdc lvo misc_lib.i...done
sfdc lvo nonvolatile_lib.i...done
sfdc lvo palette_lib.i...done
sfdc lvo penmap_lib.i...done
sfdc lvo popcycle_lib.i...done
sfdc lvo potgo_lib.i...done
sfdc lvo radiobutton_lib.i...done
sfdc lvo ramdrive_lib.i...done
sfdc lvo realtime_lib.i...done
sfdc lvo requester_lib.i...done
sfdc lvo resource_lib.i...done
sfdc lvo rexxsyslib_lib.i...done
sfdc lvo scroller_lib.i...done
sfdc lvo slider_lib.i...done
sfdc lvo space_lib.i...done
sfdc lvo speedbar_lib.i...done
sfdc lvo string_lib.i...done
sfdc lvo texteditor_lib.i...done
sfdc lvo timer_lib.i...done
sfdc lvo translator_lib.i...done
sfdc lvo utility_lib.i...done
sfdc lvo virtual_lib.i...done
sfdc lvo wb_lib.i...done
sfdc lvo window_lib.i...done
sfdc proto amigaguide.h...done
sfdc proto aml.h...done
sfdc proto arexx.h...done
sfdc proto asl.h...done
sfdc proto battclock.h...done
sfdc proto battmem.h...done
sfdc proto bevel.h...done
sfdc proto bitmap.h...done
sfdc proto bullet.h...done
sfdc proto button.h...done
sfdc proto card.h...done
sfdc proto checkbox.h...done
sfdc proto chooser.h...done
sfdc proto cia.h...done
sfdc proto clicktab.h...done
sfdc proto colorwheel.h...done
sfdc proto commodities.h...done
sfdc proto console.h...done
sfdc proto datatypes.h...done
sfdc proto datebrowser.h...done
sfdc proto diskfont.h...done
sfdc proto disk.h...done
sfdc proto dos.h...done
sfdc proto drawlist.h...done
sfdc proto dtclass.h...done
sfdc proto exec.h...done
sfdc proto expansion.h...done
sfdc proto fuelgauge.h...done
sfdc proto gadtools.h...done
sfdc proto getfile.h...done
sfdc proto getfont.h...done
sfdc proto getscreenmode.h...done
sfdc proto glyph.h...done
sfdc proto graphics.h...done
sfdc proto icon.h...done
sfdc proto iffparse.h...done
sfdc proto input.h...done
sfdc proto integer.h...done
sfdc proto intuition.h...done
sfdc proto keymap.h...done
sfdc proto label.h...done
sfdc proto layers.h...done
sfdc proto layout.h...done
sfdc proto listbrowser.h...done
sfdc proto locale.h...done
sfdc proto lowlevel.h...done
sfdc proto mathffp.h...done
sfdc proto mathieeedoubbas.h...done
sfdc proto mathieeedoubtrans.h...done
sfdc proto mathieeesingbas.h...done
sfdc proto mathieeesingtrans.h...done
sfdc proto mathtrans.h...done
sfdc proto misc.h...done
sfdc proto nonvolatile.h...done
sfdc proto palette.h...done
sfdc proto penmap.h...done
sfdc proto popcycle.h...done
sfdc proto potgo.h...done
sfdc proto radiobutton.h...done
sfdc proto ramdrive.h...done
sfdc proto realtime.h...done
sfdc proto requester.h...done
sfdc proto resource.h...done
sfdc proto rexxsyslib.h...done
sfdc proto scroller.h...done
sfdc proto slider.h...done
sfdc proto space.h...done
sfdc proto speedbar.h...done
sfdc proto string.h...done
sfdc proto texteditor.h...done
sfdc proto timer.h...done
sfdc proto translator.h...done
sfdc proto utility.h...done
sfdc proto virtual.h...done
sfdc proto wb.h...done
sfdc proto window.h...done
make newlib...done
install newlib...done
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/dos/datetime.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/dos/dos.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/dos/dosextens.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/dos/doshunks.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/dos/exall.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/dos/filehandler.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/devices/audio.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/devices/bootblock.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/devices/clipboard.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/devices/console.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/devices/conunit.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/devices/gameport.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/devices/hardblocks.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/devices/input.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/devices/inputevent.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/devices/keyboard.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/devices/keymap.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/devices/narrator.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/devices/parallel.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/devices/printer.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/devices/prtbase.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/devices/prtgfx.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/devices/scsidisk.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/devices/serial.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/devices/timer.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/devices/trackdisk.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/exec/alerts.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/exec/devices.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/exec/errors.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/exec/exec.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/exec/execbase.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/exec/interrupts.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/exec/io.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/exec/libraries.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/exec/lists.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/exec/memory.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/exec/nodes.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/exec/ports.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/exec/resident.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/exec/semaphores.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/exec/tasks.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/exec/types.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/graphics/clip.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/graphics/collide.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/graphics/copper.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/graphics/display.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/graphics/gels.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/graphics/gfx.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/graphics/gfxbase.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/graphics/gfxmacros.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/graphics/gfxnodes.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/graphics/graphint.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/graphics/layers.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/graphics/rastport.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/graphics/regions.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/graphics/sprite.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/graphics/text.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/graphics/view.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/hardware/adkbits.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/hardware/blit.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/hardware/cia.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/hardware/custom.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/hardware/dmabits.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/hardware/intbits.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/intuition/intuition.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/intuition/intuitionbase.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/intuition/preferences.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/intuition/screens.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/libraries/configregs.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/libraries/configvars.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/libraries/diskfont.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/libraries/dos.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/libraries/dosextens.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/libraries/expansion.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/libraries/expansionbase.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/libraries/filehandler.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/libraries/mathffp.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/libraries/mathieeedp.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/libraries/mathlibrary.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/libraries/translator.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/resources/cia.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/resources/disk.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/resources/filesysres.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/resources/mathresource.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/resources/misc.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/resources/potgo.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/workbench/icon.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/workbench/startup.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/workbench/workbench.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/proto/alib.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/inline/stubs.h'$'\r' sikertelen: No such file or directory
cp: stat '/opt/m68k-amigaos-bebbo/m68k-amigaos/ndk-include/inline/macros.h'$'\r' sikertelen: No such file or directory
make: *** [Makefile:692: build-CYGWIN_NT-6.1-WOW/ndk-include_ndk13] Error 1

note: the headers above are exist. is the $ sign and \r really needed there?

**Comment by bebbo** [comment]
what's the output of `make update`?

The Amiga-NDK seems to be mssing.

**Comment by anchor76** [comment]
wow, thanks for the quick response! here is the 'make update' output:

$ make update
Cloning into 'gcc'...
remote: Enumerating objects: 101696, done.
remote: Counting objects: 100% (101696/101696), done.
remote: Compressing objects: 100% (77611/77611), done.
remote: Total 101696 (delta 27573), reused 66913 (delta 22412), pack-reused 0
Receiving objects: 100% (101696/101696), 124.31 MiB | 2.89 MiB/s, done.
Resolving deltas: 100% (27573/27573), done.
Checking out files: 100% (97028/97028), done.
Already up to date.
Cloning into 'binutils'...
remote: Enumerating objects: 36226, done.
remote: Counting objects: 100% (36226/36226), done.
remote: Compressing objects: 100% (27330/27330), done.
remote: Total 36226 (delta 12330), reused 22028 (delta 7792), pack-reused 0
Receiving objects: 100% (36226/36226), 58.48 MiB | 3.00 MiB/s, done.
Resolving deltas: 100% (12330/12330), done.
Checking out files: 100% (31831/31831), done.
Already up to date.
Cloning into 'fd2sfd'...
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 42 (delta 10), reused 39 (delta 10), pack-reused 0
Unpacking objects: 100% (42/42), done.
for i in $(find patches/fd2sfd/ -type f); \
do if [[ "$i" == *.diff ]] ; \
        then j=${i:8}; patch -N "projects/${j%.diff}" "$i"; fi ; done
(Stripping trailing CRs from patch; use --binary to disable.)
patching file projects/fd2sfd/fd2inline.c
Already up to date.
Cloning into 'fd2pragma'...
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 53 (delta 19), reused 45 (delta 17), pack-reused 0
Unpacking objects: 100% (53/53), done.
Already up to date.
Cloning into 'ira'...
remote: Enumerating objects: 62, done.
remote: Counting objects: 100% (62/62), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 62 (delta 9), reused 62 (delta 9), pack-reused 0
Unpacking objects: 100% (62/62), done.
Checking out files: 100% (41/41), done.
Already up to date.
Cloning into 'sfdc'...
remote: Enumerating objects: 56, done.
remote: Counting objects: 100% (56/56), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 56 (delta 24), reused 23 (delta 13), pack-reused 0
Unpacking objects: 100% (56/56), done.
for i in $(find patches/sfdc/ -type f); \
do if [[ "$i" == *.diff ]] ; \
        then j=${i:8}; patch -N "projects/${j%.diff}" "$i"; fi ; done
(Stripping trailing CRs from patch; use --binary to disable.)
patching file projects/sfdc/sfdc
Already up to date.
Cloning into 'vasm'...
remote: Enumerating objects: 249, done.
remote: Counting objects: 100% (249/249), done.
remote: Compressing objects: 100% (179/179), done.
remote: Total 249 (delta 83), reused 143 (delta 68), pack-reused 0
Receiving objects: 100% (249/249), 445.48 KiB | 2.28 MiB/s, done.
Resolving deltas: 100% (83/83), done.
Already up to date.
Cloning into 'vbcc'...
remote: Enumerating objects: 170, done.
remote: Counting objects: 100% (170/170), done.
remote: Compressing objects: 100% (117/117), done.
remote: Total 170 (delta 48), reused 143 (delta 45), pack-reused 0
Receiving objects: 100% (170/170), 652.20 KiB | 1.99 MiB/s, done.
Resolving deltas: 100% (48/48), done.
Already up to date.
Cloning into 'vlink'...
remote: Enumerating objects: 143, done.
remote: Counting objects: 100% (143/143), done.
remote: Compressing objects: 100% (67/67), done.
remote: Total 143 (delta 84), reused 102 (delta 76), pack-reused 0
Receiving objects: 100% (143/143), 229.18 KiB | 1.66 MiB/s, done.
Resolving deltas: 100% (84/84), done.
Already up to date.
Cloning into 'libnix'...
remote: Enumerating objects: 627, done.
remote: Counting objects: 100% (627/627), done.
remote: Compressing objects: 100% (468/468), done.
remote: Total 627 (delta 161), reused 402 (delta 130), pack-reused 0
Receiving objects: 100% (627/627), 254.67 KiB | 4.04 MiB/s, done.
Resolving deltas: 100% (161/161), done.
Already up to date.
Cloning into 'ixemul'...
remote: Enumerating objects: 2783, done.
remote: Total 2783 (delta 0), reused 0 (delta 0), pack-reused 2783
Receiving objects: 100% (2783/2783), 3.13 MiB | 2.74 MiB/s, done.
Resolving deltas: 100% (1893/1893), done.
Checking out files: 100% (1185/1185), done.
Already up to date.
Cloning into 'clib2'...
remote: Enumerating objects: 1054, done.
remote: Counting objects: 100% (1054/1054), done.
remote: Compressing objects: 100% (989/989), done.
remote: Total 1054 (delta 801), reused 129 (delta 55), pack-reused 0
Receiving objects: 100% (1054/1054), 839.71 KiB | 3.09 MiB/s, done.
Resolving deltas: 100% (801/801), done.
Already up to date.
Cloning into 'libdebug'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 29 (delta 9), reused 28 (delta 9), pack-reused 0
Unpacking objects: 100% (29/29), done.
Already up to date.
Cloning into 'libSDL12'...
remote: Enumerating objects: 743, done.
remote: Counting objects: 100% (743/743), done.
remote: Compressing objects: 100% (434/434), done.
remote: Total 743 (delta 285), reused 711 (delta 276), pack-reused 0
Receiving objects: 100% (743/743), 985.08 KiB | 2.25 MiB/s, done.
Resolving deltas: 100% (285/285), done.
Already up to date.
--2018-12-26 12:31:22--  http://www.haage-partner.de/download/AmigaOS/NDK39.lha
www.haage-partner.de (www.haage-partner.de) feloldása… 217.160.0.120
Csatlakozás a következőhöz: www.haage-partner.de (www.haage-partner.de)[217.160.0.120]:80… kapcsolódva.
HTTP kérés elküldve, várakozás válaszra… 200 OK
Hossz: 3082305 (2,9M) [application/x-lha]
Mentés ide: „NDK39.lha”

NDK39.lha                             100%[======================================================================>]   2,94M  2,58MB/s    idő 1,1s

2018-12-26 12:31:24 (2,58 MB/s) -- „NDK39.lha” mentve [3082305/3082305]

mkdir -p build-CYGWIN_NT-6.1-WOW
make projects/NDK_3.9.info
make[1]: Entering directory '/cygdrive/c/!/_development/amiga-gcc'
unpack ndk...done
patch ndk...done
make[1]: Leaving directory '/cygdrive/c/!/_development/amiga-gcc'
Cloning into 'newlib-cygwin'...
remote: Enumerating objects: 5048, done.
remote: Counting objects: 100% (5048/5048), done.
remote: Compressing objects: 100% (3650/3650), done.
remote: Total 5048 (delta 2269), reused 2236 (delta 1333), pack-reused 0
Receiving objects: 100% (5048/5048), 8.47 MiB | 3.02 MiB/s, done.
Resolving deltas: 100% (2269/2269), done.
Checking out files: 100% (5009/5009), done.
Already up to date.
Cloning into 'amiga-netinclude'...
remote: Enumerating objects: 102, done.
remote: Counting objects: 100% (102/102), done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 102 (delta 34), reused 94 (delta 31), pack-reused 0
Receiving objects: 100% (102/102), 133.96 KiB | 6.70 MiB/s, done.
Resolving deltas: 100% (34/34), done.
Already up to date.

**Comment by anchor76** [comment]
update: if i have no ! in my path, i still get the same error :(

**Comment by bebbo** [comment]
well, I guess you did not follow the reciepe and something is bogus on your side. I just verified:

 - setup a new Windows 10 VM
 - install cygwin 32 bit
 - install wget, then
 - `wget https://raw.githubusercontent.com/transcode-open/apt-cyg/master/apt-cyg`
 - `install apt-cyg /bin`
 - `apt-cyg install gcc-core gcc-g++ python git perl-Pod-Simple gperf patch automake make makedepend bison flex libncurses-devel python-devel gettext-devel libgmp-devel libmpc-devel libmpfr-devel`
 - `git clone https://github.com/bebbo/amiga-gcc`
 - `cd amiga-gcc`
 - `make update`
 - `make all`

and it finished without error.

**Comment by bebbo** [comment]
how do you specify your custom prefix?

`make all` must be run with the same prefix.

**Comment by anchor76** [comment]
i tried with ubuntu 18.04 (VirtualBox) - compiles fine. (~1 hour)
now i completely restarted in cygwin from non ! path. waiting for the result (several hours)
i use: `make update` then `make all PREFIX=/opt/m68k-amigaos-bebbo`

**Comment by bebbo** [comment]
you must specify the prefix during update too:
```
make update PREFIX=/opt/m68k-amigaos-bebbo
make all PREFIX=/opt/m68k-amigaos-bebbo
```
and also add `-j n` with n the count of cpus you wanna use for the build.

On a decent machine you can build it in ~11 mins running Linux.
Windows gains speed, if you disable antivirus while building.

**Comment by anchor76** [comment]
ok, it was the `!` in my path...  thanks!

**Comment by bebbo** [comment]
https://unix.stackexchange.com/questions/3747/understanding-the-exclamation-mark-in-bash
