### ISSUE TITLE
Can't debug with gdb if linking manually

### ISSUE THREAD

**Issue by ShidenFudo** [bebbo/amiga-gcc#68]
As background I am using vscode and gdb for debugger 
 I have the following code, in my main.cpp
``` javascript
int main()
{  
    return 0;
} 
```

If I compile with the following command line.

```
m68k-amigaos-g++  -v main.cpp -g -noixemul -fno-exceptions -m68000 -o main.exe 
```
it compiles fine and I can use the debugger on vscode. 
on the amiga I can see the following 
```
hunk at: 0x400af76c sz=000013e8
hunk at: 0x4009101c sz=000001d0
hunk at: 0x400911f4 sz=000000a4
```
This is awesome!!!, but now the problems. 

### Adding -nostdlib, gdb doesn't work anymore.
Amiga cli says 
```
hunk at: 0x4002d834 sz=0000000c
```

now the program is really light, which is what I want finally, but now gdb doesn't stop at main or recognize the debugging information.
```
Loaded on MonAm
__stext:
    link a5,#0,
    moveq #0,d0
    unlk a5
    rts
```
### Compiling and linking manually gdb doesn't work.

```
m68k-amigaos-g++  -v main.cpp -g -noixemul -fno-exceptions -m68000 -o main.o
m68k-amigaos-ld -amiga-debug-hunk --no-strip-discarded -lstdc++ -L/opt/amiga/m68k-amigaos/libnix/lib -L/opt/amiga/lib/gcc/m68k-amigaos/6.4.1b -L/opt/amiga/lib/gcc -L/opt/amiga/lib/gcc/m68k-amigaos/6.4.1b/../../../../m68k-amigaos/lib -lm -lnixmain -lnix -lnix20 -lamiga -lstubs -lgcc -lnix -lnix20 -lstubs -lm -amiga-debug-hunk  main.o  -o main.exe -I /opt/amiga/m68k-amigaos/ndk-include/ 
```

This code produces the same binary as -nostdlib, which doesn't work either, I would like to not add the std initialization as I would like to replace it, but apparently not being there seems to confuse the debugger.
```
Loaded on MonAm
__stext:
    link a5,#0,
    moveq #0,d0
    unlk a5
    rts
```

### Questions 

Do you have any clue how can I work around this problem? I would like to mix c++ and asm I have but as soon I do the above I lose this fantastic feature of using GDB :(. 

am I doing something wrong or this can't be done in the current status of gdb for amiga?

Thanks a lot!

**Comment by bebbo** [comment]
first issue:

if you compile a source file to object you have to specify `-c`:
```
m68k-amigaos-g++  -v main.cpp -g -noixemul -fno-exceptions -m68000 -o main.o -c
```

2nd issue:

it seems the debugger relies on all sections to be present, so you have to extend your minimum example a bit:
```
int a=1; // data
int b; // bss
int main()
{  
    return 0;
} 
```
Then also
```
 m68k-amigaos-g++  -v main.cpp -g -noixemul -fno-exceptions -m68000 -o main3.exe -nostdlib
```
yields the desired result.

**Comment by ShidenFudo** [comment]
oh, sorry, my mistake on the '-c' I already had that but I copied the wrong line.

Interesting all sections must be there!, that is the real issue!, thanks a lot for the help!

I did already an example mixing code compiled with vasmm68k_mot and c++ using the debugger and it works perfectly, but I can't debug assembly on visual code :P.

Thanks, you are the best 🥇!

**Comment by bebbo** [comment]
gdb does also display the assembly code and allows breakpoints, stepping etc.

have fun.
