### ISSUE TITLE
building with m2sys/64 pacman -S rsync

### ISSUE THREAD

**Issue by pellicus** [bebbo/amiga-gcc#76]
Hey there! :D 
I'm trying to install amiga-gcc on msys2 64
it's seems ok but while installing things i get this:
...
install fd2sfd...done
make ira...done
install ira...done
/bin/bash: rsync: command not found
make: *** [Makefile:484: build-MSYS_NT-10.0/sfdc/Makefile] Error 127
...

so , asking me rsync 
I solved with a pacman -S rsync
and then 'make all' again.
so It should be placed in the 
....
Windows with msys2
pacman -S git base-devel gcc flex gmp-devel mpc-devel mpfr-devel ncurses-devel rsync
.....
instructions block.

now... my objective is to compile C++ code for amiga500 kick1.3 ... but this is another issue :D 
anyway, You made great job! Thank you!

pellicus.

**Comment by bebbo** [comment]
please test

**Comment by SamuraiCrow** [comment]
Aminet's webserver is down at the moment but the FTP would work if WGet only knew to look there.

**Comment by pellicus** [comment]
tested on another machine and it builds with no complaint. thanks!
