### ISSUE TITLE
Building toolchain broken

### ISSUE THREAD

**Issue by githubaf** [bebbo/amiga-gcc#79]
Tried last commit from yesterday

```
Saving to: ‘download/m68k-amigaos-ahidev.lha’

     0K                                                        1013K=0s

2019-02-25 15:06:30 (1013 KB/s) - ‘download/m68k-amigaos-ahidev.lha’ saved [29]

~/amiga-gcc_24Feb19/build/ahi ~/amiga-gcc_24Feb19
/home/developer/amiga-gcc_24Feb19/sdk/install: line 36: /home/developer/opt/m68k-amigaos_24Feb19/bin/lha: No such file or directory
~/amiga-gcc_24Feb19

```

**Comment by bebbo** [comment]
nothing changed there.

Did you remove your installed lha?

**Comment by SamuraiCrow** [comment]
Aminet's webserver was down for a while.On Feb 25, 2019 8:52 AM, bebbo <notifications@github.com> wrote:nothing changed there.
Did you remove your installed lha?

**Comment by githubaf** [comment]
I always build from scratch, i.e. completely new download directory and new prefix. I will investigate further.

**Comment by githubaf** [comment]
Sorry for false alarm. In the 3rd attempt it eventually buld successfully. So mayby Aminet eas fooling me indeed.
