### ISSUE TITLE
Would it be possible to include bsdsocket.library into the SDK?

### ISSUE THREAD

**Issue by mheyer32** [bebbo/amiga-gcc#8]
(this is a nice-to-have)

It looks like the way sockets work through clib2/libnix right now by implicitly opening bsdsocket.library.
If its not available, program start will fail.

I'd rather use bsdsocket dynamically.... i.e. have no networking available, when bsdsocket can't be opened.

Therefore  it'd be really nice to have bsdsocket as part of the SDK :-)

**Comment by MBeijer** [comment]
Nice one! Yes, this would be very good. I hope that most useful SDK's will be added in the long run. And an easy way to add new SDK's would be very good, so we can maintain and add new SDK's ourselves without having to touch too much of the main Makefile.

**Comment by bebbo** [comment]
Since this is a **cross-development** toolchain, a real Amiga library does not help, since those files are needed on the Amiga side.

In addition to this architectural problem it's not possible to provide the correct bsdsocket.library:
* with UAE you don't need one, it's built in
* on real Amigas that library is provided by the TCP/IP stack and there are different providers and versions out there.

And the good news: You can add new SDKs easily, Just write a sdk file e.g. `myfirst.sdk`- look into the existing ones, there is no documentation yet - and run it with `make sdk=myfirst`. If it's working provide it somehow (pull request, email, attached to an issue, ...)

**Comment by mheyer32** [comment]
I think there's a misunderstanding. I am not asking to include bsdsocket.library as physical file (for the reasons you gave), but rather the headers and inline/trampoline functions (which should be compatible with all bsdsocket.library implementations, aren't they?) - much like all OS provided libraries.

I'll take a look at the sdk stuff. As always, time is limited :-)

**Comment by mheyer32** [comment]
Mhhm, this might be harder than anticipated. AMITCP comes with a few files that conflict with the regular include files that come with clib/libnix ( the ones going to <proto/> <clib/> and <inline/> . Might it even be possible that when the AMITCP sdk gets installed, it overwrites some of the standard headers(?)

I just tried to switch to the bsdsocket headers, but it doesn't work. What happens is that the bsdsocket headers clash with the standard system headers. 
standard header. Now I'm getting conflicting function prototypes.

Consider this small test case:

```
#include <netinclude/bsdsocket.h>

int main(void)
{
}
```

results in:

```
In file included from /home/matze/amigatoolchain/amiga-gcc-out/m68k-amigaos/include/inline/socket.h:602:0,
                 from /home/matze/amigatoolchain/amiga-gcc-out/m68k-amigaos/include/netinclude/bsdsocket.h:16,
                 from amiga_net.c:17:
/home/matze/amigatoolchain/amiga-gcc-out/m68k-amigaos/include/clib/socket_inlines.h:22:3: error: conflicting types for 'select'
   select(LONG nfds, fd_set *readfds, fd_set *writefds, fd_set *exeptfds,

```

I think, all bsdsocket stuff needs to be put into its own directory ("netinclude/" ?) , separate from the regular system includes (and the headers need to be patched up to refer  to the amitcp headers, to not accidentally include the regular system headers).

I am aware that I will have to #ifdef around a few functions in  order to  support both, libnix and bsdsocket, but right now the biggest problem is that the headers need to be able to coexist.

Also, why not use:
http://aminet.net/package/comm/tcp/AmiTCP-SDK-4.3   ? ;-)

**Comment by bebbo** [comment]
Guess we can simply omit many files...

**Comment by patrikaxelsson** [comment]
Try the Roadshow SDK.

**Comment by bebbo** [comment]
I will not add a complete SDK. It's the headers (proto/inline) for the libraries

**Comment by patrikaxelsson** [comment]
Sorry for not clarifying the reason for my comment.

The includes in the Roadshow SDK generally has much lesser chance of clashing as it does not include for example own standard library headers (like stdio), which the includes in the AmiTCP SDK does.

**Comment by bebbo** [comment]
netinclude headers are present now
