### ISSUE TITLE
Install will fail if lha is already installed

### ISSUE THREAD

**Issue by mheyer32** [bebbo/amiga-gcc#81]
I happened to have 'lhasa' installed on machine, but that broke installing a fresh install of the toolchain:

Apparently the sdk install script expects lha in 'home/matze/amigatoolchain/amiga-gcc-out//bin/lha'

```
sdk ahi...failed
Short: retargetable audio library
Version: 6.0
~/amigatoolchain/amiga-gcc/build/ahi ~/amigatoolchain/amiga-gcc
/home/matze/amigatoolchain/amiga-gcc/sdk/install: line 34: /home/matze/amigatoolchain/amiga-gcc-out//bin/lha: No such file or directory
~/amigatoolchain/amiga-gcc
cp build/ahi/m68k-amigaos-ahi/Developer/Docs/ahi.doc /home/matze/amigatoolchain/amiga-gcc-out//m68k-amigaos/doc/ahi.doc
cp: cannot stat 'build/ahi/m68k-amigaos-ahi/Developer/Docs/ahi.doc': No such file or directory
```

**Comment by bebbo** [comment]
check your installation.

First the **default** lha is tried:
```
lha x "../../download/$file" && $3/bin/lha x "../../download/$file"
```

**Comment by bebbo** [comment]
maybe your lha can't handle that archive?

**Comment by mheyer32** [comment]
I don't know... that lhasa thingy can definitely not pack, only unpack.

Anyways, after 
sudo apt-get remove lhasa

and letting the toolchain build its own lha, I'm now getting:

~/amigatoolchain/amiga-gcc/build/ahi ~/amigatoolchain/amiga-gcc
LHa: Error: Unknown level header (level 32)
~/amigatoolchain/amiga-gcc
cp build/ahi/m68k-amigaos-ahi/Developer/Docs/ahi.doc /home/matze/amigatoolchain/amiga-gcc-out//m68k-amigaos/doc/ahi.doc
cp: cannot stat 'build/ahi/m68k-amigaos-ahi/Developer/Docs/ahi.doc': No such file or directory


So I think you're right and the archive is broken. Aminet is really flaky recently. Case closed :-)
