### ISSUE TITLE
Building clib2 with parallel make

### ISSUE THREAD

**Issue by th-otto** [bebbo/amiga-gcc#84]

**Comment by th-otto** [comment]
When building with "make -j8 all" after a fresh clone, the build errored on clib2. When i started "make all" after that, it continued to build libgcc first, so i think that it is a problem of a missing dependency, and clib2 is built before libgcc finishes.

**Comment by bebbo** [comment]
guess you forgot to run `make update`

**Comment by th-otto** [comment]
Erm, no, forgot to mention it, but all directories in projects where there.

**Comment by bebbo** [comment]
please attach the log from the failed build

**Comment by th-otto** [comment]
As usual, i cannot reproduce anymore. hm.

**Comment by bebbo** [comment]
reopen if you have a recipe to reproduce

**Comment by th-otto** [comment]
ok, thx for looking to it, and sorry for wasted time. Dunno what i did the first time...
