### ISSUE TITLE
fatal error: SDL.h: No such file or directory

### ISSUE THREAD

**Issue by githubaf** [bebbo/amiga-gcc#86]
Compiling SAM failes now with the message above.
Last working toolchain was from 15.Mar
First bad Toolchain is from 16.Mar

**Comment by bebbo** [comment]
sorry - you have to change your Makefile, since I decided that provided libs and headers have to live inside the m68k-amigaos folder to separate these from the users include/libs

old
```
CFLAGS += -Iamiga/ -Iamiga/portaudio/ -I. -I$(COMPILER_INSTALL_DIR)/include/SDL
```
new
```
CFLAGS += -Iamiga/ -Iamiga/portaudio/ -I. -I$(COMPILER_INSTALL_DIR)/m68k-amigaos/include/SDL
```

**Comment by githubaf** [comment]
I see. Works well with your expaination. Thanks.
