### ISSUE TITLE
Have to run make all multiple times

### ISSUE THREAD

**Issue by MBeijer** [bebbo/amiga-gcc#9]
After doing make clean I have to run make all multiple times until it says "make: Nothing to be done for 'all'."

So there seems to be breakpoints after each sub-makefile.

Also, clean doesn't properly remove previously unpacked archives so it asks to overwrite previously written files. Possibly remove the files automatically on clean or automatically overwrite the files if not or possibly both.

**Comment by bebbo** [comment]
Looks like a problem with your environment. (e,g. bash on windows)

**Comment by MBeijer** [comment]
Debian GNU/Linux, bash, and this is the first time this happens. Could it be because of -j8?

**Comment by bebbo** [comment]
could be, maybe not enough memory for j8 - then processes are killed in panic...

**Comment by MBeijer** [comment]
The VM I'm doing the compiling on has at least 6 GB ram and mainly is my
Amiga Dev machine for crosscompiling, so the process has 6GB of RAM to deal
use. So I doubt that. It's running on a Xeon dedicated server I have.

**Comment by bebbo** [comment]
for -j8 1GB ram is sufficient.

Do you use a buggy make? 3.81?
I'm using GNU Make 4.1

**Comment by MBeijer** [comment]
$ make -v
GNU Make 4.2.1

**Comment by bebbo** [comment]
http://lists.gnu.org/archive/html/bug-make/2017-11/msg00041.html

**Comment by bebbo** [comment]
http://lists.gnu.org/archive/html/bug-make/2017-08/msg00034.html

**Comment by MBeijer** [comment]
Last one is regarding Mac and APFS which is not my case. The first one is very vague and might be SBS.

**Comment by MBeijer** [comment]
The make process work as it should now, so I think there was a bug in GNU Make itself. So I'm closing this!
