### ISSUE TITLE
First function isn't necessarily put first in executable

### ISSUE THREAD

**Issue by patrikaxelsson** [bebbo/amiga-gcc#94]
Using todays version of https://github.com/sebastianbergmann/docker-amiga-gcc

I have spent some time creating an executable with its own startup code.

The executable file produced works as long as it is very simple and say just returns a value, but the executable file for say a hello world style program will crash the Amiga.

Hello world example:
```
root@b46883abff97:~# m68k-amigaos-gcc --version
m68k-amigaos-gcc (GCC) 6.5.0b 190415210100
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@b46883abff97:~# cat hello.c 
#include <exec/exec.h>
#include <dos/dos.h>

#include <proto/exec.h>
#include <proto/dos.h>

LONG hello() {
	struct ExecBase *SysBase = *(struct ExecBase **) 4;
	struct DosLibrary *DOSBase = (void *) OpenLibrary("dos.library", 0);
	if (NULL != DOSBase) {
		Write(Output(), "Hello world!\n", 13);
		CloseLibrary((void *) DOSBase);
	}
	return 0;
}
root@b46883abff97:~# m68k-amigaos-gcc -nostartfiles -O2 -o hello.gcc hello.c
root@b46883abff97:~# ira hello.gcc

IRA V2.09 (Apr 16 2019)
(c)1993-1995 Tim Ruehsen (SiliconSurfer/PHANTASM)
(c)2009-2015 Frank Wille
(c)2014-2017 Nicolas Bastien

Symbol ___a4_init value $00008056 not in section limits.

SOURCE : "hello.gcc"
TARGET : "hello.asm"
MACHINE: MC68000
OFFSET : $00000000
codeAdrs: 0   codeAdrMax: 16
CodeArea[0]: 00000000 - 00000058


Pass 1: 100%
Pass 2: correcting labels
Pass 2: writing mnemonics
100%


root@b46883abff97:~# cat hello.asm
; IRA V2.09 (Apr 16 2019) (c)1993-1995 Tim Ruehsen
; (c)2009-2015 Frank Wille, (c)2014-2017 Nicolas Bastien

ABSEXECBASE	EQU	$4




	SECTION S_0,CODE

__stext:
	DC.W	$646f
	DC.W	$732e
	DC.W	$6c69
	DC.W	$6272
	DC.W	$6172
	DC.W	$7900
LAB_0001:
	DC.W	$4865
	DC.W	$6c6c
	BLE.S	LAB_0003
	DC.W	$776f
	MOVEQ	#108,D1
	DC.W	$6421
	EORI.B	#$00,D0
_hello:
	MOVEM.L	D2-D5/A6,-(A7)
	MOVEA.L	ABSEXECBASE.W,A6
	MOVE.L	A6,D5
	MOVEQ	#0,D0
	LEA	__stext(PC),A1
	JSR	-552(A6)
	MOVE.L	D0,D4
LAB_0003:
	BEQ.S	LAB_0004
	MOVEA.L	D0,A6
	JSR	-60(A6)
	MOVE.L	D0,D1
	MOVEQ	#13,D3
	MOVE.L	#LAB_0001,D2
	JSR	-48(A6)
	MOVEA.L	D4,A1
	MOVEA.L	D5,A6
	JSR	-414(A6)
LAB_0004:
	MOVEQ	#0,D0
	MOVEM.L	(A7)+,D2-D5/A6
__etext:
	RTS
	END
```

It appears it is putting the string data before the first function ($646f $732e $6c69  = "dos.li" ..), which the Amiga then tries to execute and crashes.

I found that it is possible to create a working version of this hello world executable by adding a small function at top of the file, which justs calls the second one. This shouldn't be necessary though:
```
root@b46883abff97:~# cat hello2.c 
#include <exec/exec.h>
#include <dos/dos.h>

#include <proto/exec.h>
#include <proto/dos.h>

LONG hello();

LONG start() {
	return hello();
}

LONG hello() {
	struct ExecBase *SysBase = *(struct ExecBase **) 4;
	struct DosLibrary *DOSBase = (void *) OpenLibrary("dos.library", 0);
	if (NULL != DOSBase) {
		Write(Output(), "Hello world!\n", 13);
		CloseLibrary((void *) DOSBase);
	}
	return 0;
}
root@b46883abff97:~# m68k-amigaos-gcc -nostartfiles -O2 -o hello2.gcc hello2.c
root@b46883abff97:~# ira hello2.gcc

IRA V2.09 (Apr 16 2019)
(c)1993-1995 Tim Ruehsen (SiliconSurfer/PHANTASM)
(c)2009-2015 Frank Wille
(c)2014-2017 Nicolas Bastien

Symbol ___a4_init value $00008056 not in section limits.

SOURCE : "hello2.gcc"
TARGET : "hello2.asm"
MACHINE: MC68000
OFFSET : $00000000
codeAdrs: 0   codeAdrMax: 16
CodeArea[0]: 00000000 - 00000058


Pass 1: 100%
Pass 2: correcting labels
Pass 2: writing mnemonics
100%


root@b46883abff97:~# cat hello2.asm
; IRA V2.09 (Apr 16 2019) (c)1993-1995 Tim Ruehsen
; (c)2009-2015 Frank Wille, (c)2014-2017 Nicolas Bastien

ABSEXECBASE	EQU	$4




	SECTION S_0,CODE

_start:
	BRA.S	_hello
LAB_0001:
	DC.W	$646f
	DC.W	$732e
	DC.W	$6c69
	DC.W	$6272
	DC.W	$6172
	DC.W	$7900
LAB_0002:
	DC.W	$4865
	DC.W	$6c6c
	BLE.S	LAB_0004
	DC.W	$776f
	MOVEQ	#108,D1
	DC.W	$6421
	DC.W	$0a00
_hello:
	MOVEM.L	D2-D5/A6,-(A7)
	MOVEA.L	ABSEXECBASE.W,A6
	MOVE.L	A6,D5
	MOVEQ	#0,D0
	LEA	LAB_0001(PC),A1
	JSR	-552(A6)
	MOVE.L	D0,D4
	BEQ.S	LAB_0005
LAB_0004:
	MOVEA.L	D0,A6
	JSR	-60(A6)
	MOVE.L	D0,D1
	MOVEQ	#13,D3
	MOVE.L	#LAB_0002,D2
	JSR	-48(A6)
	MOVEA.L	D4,A1
	MOVEA.L	D5,A6
	JSR	-414(A6)
LAB_0005:
	MOVEQ	#0,D0
	MOVEM.L	(A7)+,D2-D5/A6
__etext:
	RTS
	END
```

**Comment by bebbo** [comment]
That's exactly how gcc works.

**Comment by patrikaxelsson** [comment]
Is there any point in creating hunk executables for the amiga where the first code hunk starts with data?

**Comment by bebbo** [comment]
The compiler does not know how to link one or many objects and the linker expects as first file a file that starts with code: the startup file.

If you omit this, you have to take care of it yourself.

So this is a user error

**Comment by patrikaxelsson** [comment]
What I want to do is handle the startup in C for a minimal project, only using the AmigaOS API.

In the example in this issue, the first and only function was the startup code, but as the compiler(?) put the "dos.library" string and other constant data first in the code segment/hunk, it is not usable as startup file.

Is it correct that it will place data first in the code segment before the actual code as soon as the function contains some constant data like strings?

One workaround which seems to work consistently is to create a pre-startup function in a separate file, specified first. That pre-startup function only calls the real startup code and as it has no constant data, it will start with code.

I would prefer to keep the little startup code needed in one function in one file if possible. Is there no way to tell the compiler to place the data after the code in the first example?

**Comment by bebbo** [comment]
> I would prefer to keep the little startup code needed in one function in one file if possible. Is there no way to tell the compiler to place the data after the code in the first example?

Sorry, not that I know of.
